In [34]:
# !pip install pandas
# !pip install numpy
# !pip install matplotlib
# !pip install networkx
# !pip install requests
# !pip install openai
# !pip install nest_asyncio
# !pip install tqdm
# !pip install Jinja2
# USA = [TOP3000, TOP1000, TOP500, TOP200, ILLIQUID_MINVOL1M, TOPSP500]

# GLB = [TOP3000, MINVOL1M, TOPDIV3000]

# EUR = [TOP2500, TOP1200, TOP800, TOP400, ILLIQUID_MINVOL1M]

# ASI = [MINVOL1M, ILLIQUID_MINVOL1M]

# LLM으로 알파 생성하기
* LLM이 발달하면서 이제 mini 등 가벼운 모델로도 알파를 꽤나 쉽게 만들 수 있는 환경이 되었습니다. 
* 오늘 돌리면서 한 쿼리를 6번 정도 날렸는데 $0.4 정도가 나왔습니다. 
* 한 번 알파 100개 만드는 시도를 할 때 약 100원 정도 들어간다고 생각하시면 될 것 같습니다.
* 사양이 괜찮으신 분들은 (또는 최신 맥북을 쓰신다면) ollama로 로컬 LLM도 한번 써보세요! 생각보다 괜찮습니다 성능이

# 데이터필드 정보 저장하기
현재 설정: **REGION / UNIVERSE** (글로벌 변수 참조)
처음 실행 시 30분-1시간 정도 걸리는 작업입니다.

In [35]:
# 처음에만 진행하시면 됩니다.
# 🔧 REGION / UNIVERSE GLOBALIZED - 글로벌 설정
REGION = "EUR"
UNIVERSE = "TOP2500"
DELAY = "1"

import AAF as aaf
import ace_lib as ace

# 세팅 
settings = {

    "nan_handling" : "OFF",
    "instrumentType": "EQUITY",      # FIXED
    "delay"          : 1,
    "universe"       : UNIVERSE,     # 🔧 REGION / UNIVERSE GLOBALIZED
    "truncation"     : 0.01,
    "unitHandling"   : "VERIFY",     # FIXED
    "pasteurization" : "ON",
    "region"         : REGION,       # 🔧 REGION / UNIVERSE GLOBALIZED
    "language"       : "FASTEXPR",   # FIXED
    "neutralization" : "INDUSTRY",     # Can be varied
    "visualization"  : False
}

In [36]:
s = ace.start_session()
operators = ace.get_operators(s)

# aaf.initiate_datafield(s,settings)

Complete biometrics authentication and press any key to continue:
https://api.worldquantbrain.com/authentication/persona?inquiry=inq_WaTMmpYU5vRLH3dHEgF2wE2M3GP3

In [37]:
# 🔧 REGION / UNIVERSE GLOBALIZED
datasets_df = ace.get_datasets(
    s, 
    instrument_type='EQUITY', 
    region=REGION, 
    universe=UNIVERSE,
    delay=1, 
)
selected_datasets_df = datasets_df[
    (datasets_df["alphaCount"] >-1)]
selected_datasets_df

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
0,analyst10,Performance-Weighted Analyst Estimates,"This dataset provides ""smart estimates,"" which...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.7760,...,926,3515,916,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,analyst11,ESG scores,This dataset provides a comprehensive mapping ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8489,...,179,426,445,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
2,analyst14,Estimations of Key Fundamentals,This dataset reports many items from financial...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.5000,...,819,2859,121,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,analyst15,Earnings forecasts,This dataset provides bottom-up forecast data ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.9102,...,1448,10756,1701,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,analyst39,Analyst estimates & financial ratios,This dataset contains detailed point-in-time c...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8755,...,597,3148,24,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,shortinterest6,SmartHoldings Model,This dataset is a global stock selection model...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-estimates-models', 'name': 'Esti...",EUR,1,TOP2500,1.0,1.0000,...,50,130,11,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-estimates-models,Estimates Models
126,socialmedia12,Sentiment Data for Equity,This dataset aggregates and analyzes social me...,"{'id': 'socialmedia', 'name': 'Social Media'}","{'id': 'socialmedia-social-media', 'name': 'So...",EUR,1,TOP2500,1.0,0.7836,...,474,1367,6,1.1,[],"[{'type': 'research', 'title': 'Creating D0 Al...",socialmedia,Social Media,socialmedia-social-media,Social Media
127,socialmedia15,Sentiment Indicators,A dataset model providing normalized sentiment...,"{'id': 'socialmedia', 'name': 'Social Media'}","{'id': 'socialmedia-social-media', 'name': 'So...",EUR,1,TOP2500,1.0,0.2726,...,290,740,13,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",socialmedia,Social Media,socialmedia-social-media,Social Media
128,univ1,Universe Dataset,No dataset description,"{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",EUR,1,TOP2500,1.0,0.7500,...,0,0,4,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",pv,Price Volume,pv-price-volume,Price Volume
129,univ2,Universe Dataset,No dataset description,"{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",EUR,1,TOP2500,NaN,0.6700,...,0,0,1,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",pv,Price Volume,pv-price-volume,Price Volume

In [38]:
selected_df = datasets_df[datasets_df['alphaCount']>100]
#     "USA": ['analyst12', 'analyst2', 'analyst48', 'analyst9', 'fundamental21', 'fundamental85',
#  'fundamental91', 'macro10', 'macro52', 'model239', 'model240', 'model46', 'model54',
#  'model57', 'news31', 'news5', 'news50', 'news54', 'news79', 'option10', 'option13',
#  'option22', 'other323', 'other492', 'other696', 'sentiment18', 'shortinterest3',
#  'shortinterest36', 'socialmedia3', 'socialmedia8']
# ,
#     "EUR": ['analyst39', 'earnings3', 'model109', 'model138', 'model139', 'model176', 'model25',
#  'model28', 'model30', 'model39', 'news104', 'news17', 'news23', 'news46', 'news79',
#  'other197', 'other455', 'other696', 'risk59', 'risk60', 'risk88',
#  'shortinterest3', 'shortinterest37', 'socialmedia39']
# ,
#     "ASI": ['analyst44', 'analyst48', 'analyst69', 'analyst9', 'fundamental17', 'fundamental21',
#  'fundamental23', 'fundamental28', 'fundamental44', 'fundamental6', 'fundamental72',
#  'model106', 'model109', 'model138', 'model16', 'model262', 'model53', 'model77',
#  'other128', 'other455', 'other463', 'other675', 'pv13', 'risk74', 'risk88',
#  'shortinterest37']
# ,
#     "GLB": ['analyst11', 'analyst35', 'analyst44', 'analyst48', 'analyst82', 'analyst9',
#  'fundamental45', 'fundamental46', 'fundamental6', 'fundamental7', 'fundamental72',
#  'model106', 'model16', 'model162', 'model262', 'news52', 'news76', 'other128',
#  'other169', 'other463', 'other675', 'pv13', 'pv30', 'pv53', 'risk74', 'risk88',
#  'shortinterest37']
dataset_ids =  ['analyst39', 'earnings3', 'model109', 'model138', 'model139', 'model176', 'model25',
  'model28', 'model30', 'model39', 'news104', 'news17', 'news23', 'news46', 'news79',
  'other197', 'other455', 'other696', 'risk59', 'risk60', 'risk88',
  'shortinterest3', 'shortinterest37', 'socialmedia39']
saved_fields =[]

# 🔧 REGION / UNIVERSE GLOBALIZED
for i in range (0,len(dataset_ids)):
    datafields_df = ace.get_datafields(s, dataset_id=dataset_ids[i], delay=1, region=REGION, universe=UNIVERSE)
    saved_fields.append(datafields_df[:2])

2026-02-07 13:23:40,842 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=earnings3

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 13:23:41,830 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=model176

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 13:23:43,530 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=news23

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 13:23:44,130 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=other197

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 13:23:44,681 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=risk59

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 13:23:45,811 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=socialmedia39

In [39]:
filtered_df = selected_df[
    selected_df['id'].str.split('_').str[0].isin(dataset_ids)
]
filtered_df = filtered_df.sort_values(
    by='alphaCount',
    ascending=False
)

filtered_df

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
41,model25,Earnings Quality,This model dataset provides with financial sta...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-revisions-models', 'name': 'Revi...",EUR,1,TOP2500,1.0,0.6591,...,1156,7036,199,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-revisions-models,Revisions Models
4,analyst39,Analyst estimates & financial ratios,This dataset contains detailed point-in-time c...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8755,...,597,3148,24,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
32,model138,Stock Selection from Accounting-based Factors,This dataset contains a comprehensive suite of...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-mlai-models', 'name': 'ML/AI Mod...",EUR,1,TOP2500,1.0,0.5537,...,651,2723,120,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-mlai-models,ML/AI Models
92,other455,Relationship enhanced with AI/ML,Grouping data. Generated using deep learning m...,"{'id': 'other', 'name': 'Other'}","{'id': 'other-aiml-data', 'name': 'AI/ML Data'}",EUR,1,TOP2500,1.0,0.6380,...,495,2596,1200,1.6,[],"[{'type': 'discussion', 'title': 'Getting star...",other,Other,other-aiml-data,AI/ML Data
47,model30,EPS Estimate Model,This dataset provides detailed metrics on anal...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-estimates-models', 'name': 'Esti...",EUR,1,TOP2500,1.0,0.7130,...,448,1358,77,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-estimates-models,Estimates Models
115,risk60,Securities Lending Insight Data,"The dataset provides list of metrics, covering...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,1.0,0.9372,...,484,978,4,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",risk,Risk,risk-risk-models,Risk Models
55,model39,Valuation Momentum Data,This dataset integrates two advanced quantitat...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-valuation-models', 'name': 'Valu...",EUR,1,TOP2500,1.0,0.8044,...,285,954,24,1.4,[],"[{'type': 'research', 'title': 'Research Paper...",model,Model,model-valuation-models,Valuation Models
60,news17,PR Edition Data,"This dataset analyzes and structures news, pre...","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",EUR,1,TOP2500,1.0,0.8014,...,214,516,75,1.5,[],"[{'type': 'discussion', 'title': 'Getting star...",news,News,news-news,News
69,news46,Relevant News Analytics Data,This dataset provides a comprehensive mapping ...,"{'id': 'news', 'name': 'News'}","{'id': 'news-news-sentiment', 'name': 'News Se...",EUR,1,TOP2500,1.0,0.9382,...,125,263,30,1.5,[],"[{'type': 'research', 'title': 'Creating D0 Al...",news,News,news-news-sentiment,News Sentiment
46,model28,Structural Credit Risk Model,This dataset provides a comprehensive mapping ...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-risk-based-models', 'name': 'Ris...",EUR,1,TOP2500,1.0,0.8281,...,103,247,43,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-risk-based-models,Risk Based Models
64,news23,MnA Deals Data,This dataset offers detailed information on me...,"{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",EUR,1,TOP2500,1.0,0.4462,...,88,145,136,1.5,[],"[{'type': 'discussion', 'title': 'Getting star...",news,News,news-news,News

In [41]:
# 특정 dataset_id에 속하는 datafield 스펙 보기
TARGET_DATASET_IDS = ["risk60"]  # 원하는 dataset id로 변경 (복수 가능)

# 🔧 REGION / UNIVERSE GLOBALIZED
for _ds_id in TARGET_DATASET_IDS:
    # Brain API에서 해당 dataset의 datafield 목록 가져오기
    datafields_spec = ace.get_datafields(
        s, 
        region=REGION,
        universe=UNIVERSE,
        dataset_id=_ds_id,
        data_type='ALL'
    )

    # 표시할 컬럼 선택 (존재하는 컬럼만)
    display_cols = ['id', 'description', 'type', 'alphaCount', 'userCount', 'coverage']
    display_cols = [col for col in display_cols if col in datafields_spec.columns]

    # alphaCount 기준 내림차순 정렬 후 표시
    # datafields_spec = datafields_spec[display_cols].sort_values(by='alphaCount', ascending=False)
    print(f"\nDataset: {_ds_id} | Total datafields: {len(datafields_spec)}")
    display(datafields_spec)

Dataset: risk60 | Total datafields: 4

,id,description,dataset,category,subcategory,region,delay,universe,type,dateCoverage,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,rsk60_crowding,Crowding is a daily score for shorting and cov...,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,0.8089,...,67,124,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models
1,rsk60_datatime,Time data,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,1.0000,...,50,94,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models
2,rsk60_last,The last rate is the financing rate at which w...,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,1.0000,...,262,434,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models
3,rsk60_offer,The offer rate is the financing rate at which ...,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,1.0000,...,253,442,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models

# Expression Sanity checker
데이터필드 정보를 이용해서, LLM이 만든 expression이 실제 브레인에서 돌아갈 수 있는지를 체크합니다.

In [42]:
import llm_functions as llm
from parser import *
import ace_lib as ace
import numpy as np
import pandas as pd
import os 
import json
import asyncio



# 🔧 REGION / UNIVERSE GLOBALIZED
datafields = llm.import_json(f'datafield/1/{REGION}/{UNIVERSE}/1_{REGION}_{UNIVERSE}_total.json')
operators = llm.import_json('operators_list.json')

def return_type(node, operators, datafields):
    if node.node_type == 'operator':
        return operators[node.value]['output']

    elif node.node_type == 'number':
        return "NUMBER"

    elif node.node_type == 'datafield':
        if node.value.lower() == 'nan':
            return "MATRIX"
        return datafields[node.value]['type']

    else:
        return "SPECIAL_ARGUMENT"


def check_input(operator_inputs, children_types, _debug = False):
    if _debug: print(operator_inputs)
    while len(operator_inputs) != 0:

        operator_input = operator_inputs.pop(0)
        if _debug: print(f"operator input: {operator_input}, remain inputs: {len(operator_inputs)}" )

        if operator_input == '_SPECIAL_ARGUMENT':
            if len(children_types) == 0:
                pass
            elif children_types[0] == '_SPECIAL_ARGUMENT':
                if _debug: print(operator_input)
                if _debug: print(children_types.pop(0))
            else:
                pass

        else:
            if len(children_types) == 0:
                return False

            children_type = children_types.pop(0)
            if operator_input == "MATRIX" and children_type == "NUMBER":
                pass
            elif operator_input != children_type:
                if _debug: print(operator_input ,children_type, operator_input == children_type)
                return False

    return True


def sanity_checker(exp, _debug=False):

    try:
        exp_tree = tree_node(exp)

        for node in [node for node in exp_tree.collect_all_nodes() if node.node_type == "operator"]:

            if check_input(eval(operators[node.value]['input']), [return_type(x,operators, datafields) for x in node.children]):
                if _debug: print(check_input(eval(operators[node.value]['input']), [return_type(x) for x in node.children]))
            else:
                return False
        if return_type(exp_tree,operators, datafields)=="MATRIX":
            return True

        else:
            return False
    except Exception as e:
        print(f"err: {e}")
        return False

## Sanity check 예시

In [43]:
sanity_checker('bucet(rank(mdl138_4idpc), range="0,100,10)")') # 이상한 수식, False

err: 'bucet'

False

In [44]:
sanity_checker('ts_backfill(mdl138_4idpc,60)') # 정상적인 expression, True

True

# 탐색 데이터셋 설정
여기서는 데이터셋 카테고리별로 User Count가 가장 높은 순으로 정렬해서 탐색

In [45]:
#s = ace.start_session()

# 🔧 REGION / UNIVERSE GLOBALIZED - 글로벌 변수 사용
region = REGION
universe = UNIVERSE

datafields = llm.import_json(f'datafield/1/{region}/{universe}/1_{region}_{universe}_total.json')
operators = llm.import_json('operators_list.json')

# ============================================================
# 탐색할 dataset 직접 지정 (하드코딩)
# ============================================================
ALLOWED_DATASETS = TARGET_DATASET_IDS  # 위에서 설정한 리스트 그대로 사용

# Brain API에서 전체 datasets 정보 가져오기 (datasets_dict 구성용)
datasets = ace.get_datasets(s, region=region, universe=universe)
datasets = datasets.drop_duplicates(['id'])

# ALLOWED_DATASETS에 있는 것만 datasets_dict에 포함
datasets_filtered = datasets[datasets['id'].isin(ALLOWED_DATASETS)]
datasets_dict = {row['id']: row.to_dict() for _, row in datasets_filtered.iterrows()}

# datasets_list는 ALLOWED_DATASETS 그대로 사용
datasets_list = ALLOWED_DATASETS

print(f"Exploring datasets: {datasets_list}")

Exploring datasets: ['risk60']

## 시뮬레이션 하기에 앞서...
* 저카운트와 필드카운트에 따라 몇번 expression을 생성하고 돌릴지 결정 
* llm으로 만드는 알파들을 따로 json으로 저장
* csv 로드하고 저장하는 함수

In [46]:
# 유저카운트와 필드카운트로 몇번 expression을 생성하고 돌릴지 결정 
# 한번에 100개씩 generate하니까 10은 알파를 1000개 만들어서 돌리겠다는 뜻
def datset_to_simnum(dataset):
    score = int(np.log10(datasets_dict[dataset]['userCount']+1) + datasets_dict[dataset]['fieldCount'])

    if score <= 3:
        return 1
    elif score <= 10:
        return 2
    elif score <= 50:
        return 3
    elif score <= 100:
        return 10
    else:
        return 20


# llm으로 알파 리스트를 만들면 json도 저장해주기
def get_json_num(dataset):

    json_list = [x for x in os.listdir('./gen_json/') if dataset in x]
    if len(json_list) == 0:
        return 0
    nums = [int(x.split('_')[-1].split('.')[0]) for x in json_list]

    return max(nums)+1

# csv 로드하고 저장하는 함수
def load_csv(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        return pd.DataFrame()
    df = pd.read_csv(path) # index_col=None(기본값): 인덱스 컬럼으로 읽지 않음
    # 과거에 인덱스가 저장되어 있으면 'Unnamed: 0' 같은 컬럼 제거
    df = df.loc[:, ~df.columns.str.match(r'^Unnamed: \d+$')]
    return df

def save_csv(df: pd.DataFrame, path: str) -> None:
    df.to_csv(path, index=False)

def append_and_save_csv(path: str, new_rows: pd.DataFrame) -> pd.DataFrame:
    base = load_csv(path)
    out = pd.concat([base, new_rows], ignore_index=True) # 인덱스 재부여
    save_csv(out, path) # index=False
    return out

# ============================================================
# good_alpha_list.json 자동 저장 함수
# - 시뮬레이션 결과에서 0-fail 알파를 추출하여 자동 저장
# ============================================================
from datetime import datetime

GOOD_ALPHA_PATH = "./good_alpha_list.json"

def load_good_alpha_list(path=GOOD_ALPHA_PATH):
    """good_alpha_list.json 로드"""
    if not os.path.exists(path):
        return []
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_good_alpha_list(data, path=GOOD_ALPHA_PATH):
    """good_alpha_list.json 저장"""
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def extract_good_alphas(sim_results):
    """sim_results (Brain API raw response list)에서 0-fail 알파를 추출하여 good_alpha_list 형식으로 반환"""
    good = []
    now = datetime.now().isoformat()
    
    for result in sim_results:
        if not isinstance(result, dict) or 'id' not in result:
            continue
        
        is_data = result.get('is', {})
        checks = is_data.get('checks', [])
        fail_count = sum(1 for c in checks if c.get('result') == 'FAIL')
        
        if fail_count == 0:
            entry = {
                'timestamp': now,
                'alpha_id': result['id'],
                'expression': result.get('regular', {}).get('code', ''),
                'is_sharpe': is_data.get('sharpe'),
                'is_fitness': is_data.get('fitness'),
                'is_turnover': is_data.get('turnover'),
                'settings': {
                    'region': result.get('settings', {}).get('region', ''),
                    'universe': result.get('settings', {}).get('universe', ''),
                    'delay': result.get('settings', {}).get('delay', 1),
                    'decay': result.get('settings', {}).get('decay', 0),
                    'truncation': result.get('settings', {}).get('truncation', 0.08),
                    'neutralization': result.get('settings', {}).get('neutralization', 'INDUSTRY'),
                    'pasteurization': result.get('settings', {}).get('pasteurization', 'ON'),
                    'nanHandling': result.get('settings', {}).get('nanHandling', 'OFF'),
                    'unitHandling': result.get('settings', {}).get('unitHandling', 'VERIFY'),
                    'language': result.get('settings', {}).get('language', 'FASTEXPR'),
                    'testPeriod': result.get('settings', {}).get('testPeriod', 'P0Y0M0D'),
                    'visualization': result.get('settings', {}).get('visualization', False)
                },
                'checks': [{'name': c.get('name', ''), 'result': c.get('result', '')} for c in checks]
            }
            good.append(entry)
    return good

def append_good_alpha_list(sim_results, path=GOOD_ALPHA_PATH):
    """sim_results에서 0-fail 알파를 추출하여 good_alpha_list.json에 추가, 추가된 개수 반환"""
    new_good = extract_good_alphas(sim_results)
    if not new_good:
        return 0
    
    existing = load_good_alpha_list(path)
    existing_ids = set(item['alpha_id'] for item in existing)
    
    # 중복 제거
    truly_new = [x for x in new_good if x['alpha_id'] not in existing_ids]
    if not truly_new:
        return 0
    
    merged = existing + truly_new
    save_good_alpha_list(merged, path)
    return len(truly_new)

# 시뮬레이션 돌리기
* 데이터셋에 따라 정해진 횟수에 맞추어 시뮬레이션 돌리기
* 원한다면 datasets_list를 조작하여 원하는 데이터셋에 맞추어 돌릴 수 있음

In [47]:
# ============================================================
# 시뮬레이션 돌리기 (Resume 지원 버전)
# - 이미 생성된 gen_json은 스킵하고 부족한 배치만 생성
# - 중간에 끊겨도 다시 실행하면 이어서 진행
# - 0-fail 알파는 good_alpha_list.json에 자동 저장
# ============================================================
# 🔧 NEW: Top N datafields 설정 - 각 dataset에서 alphaCount 상위 N개만 LLM에 전달
# This restricts the LLM to use only the top N datafields (by alphaCount) within each dataset
TOP_N_DATAFIELDS = 10
# ============================================================

import os
import json
import re

# ------------------------------------------------------------
# Resume 지원 함수들
# ------------------------------------------------------------

def get_existing_json_count(dataset, gen_dir="./gen_json"):
    """
    gen_dir에서 {dataset}_*.json 패턴 파일 개수를 반환
    """
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir, exist_ok=True)
        return 0
    
    pattern = re.compile(rf"^{re.escape(dataset)}_(\d+)\.json$")
    count = 0
    for filename in os.listdir(gen_dir):
        if pattern.match(filename):
            count += 1
    return count


def get_next_json_index(dataset, gen_dir="./gen_json"):
    """
    gen_dir에서 {dataset}_*.json 패턴 파일을 찾고
    가장 큰 k를 계산한 다음 max_k + 1 반환
    파일이 없으면 0 반환
    """
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir, exist_ok=True)
        return 0
    
    pattern = re.compile(rf"^{re.escape(dataset)}_(\d+)\.json$")
    max_k = -1
    
    for filename in os.listdir(gen_dir):
        match = pattern.match(filename)
        if match:
            k = int(match.group(1))
            if k > max_k:
                max_k = k
    
    return max_k + 1


def save_json_safe(data, filepath):
    """
    저장 직전에 파일 존재 여부 체크 (레이스 방지)
    이미 존재하면 저장하지 않고 False 반환
    """
    if os.path.exists(filepath):
        print(f"[WARN] File already exists, skipping: {filepath}")
        return False
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return True


# ------------------------------------------------------------
# 메인 루프 (Resume 지원)
# ------------------------------------------------------------

GEN_DIR = "./gen_json"
os.makedirs(GEN_DIR, exist_ok=True)
print(datasets_list)
print(f"[CONFIG] Using top {TOP_N_DATAFIELDS} datafields per dataset (by alphaCount)")

for dataset in datasets_list:
    
    # 목표 생성 횟수
    target_simnum = datset_to_simnum(dataset)
    
    # 현재 존재하는 파일 개수
    existing_count = get_existing_json_count(dataset, GEN_DIR)
    
    # 남은 생성 횟수
    remaining = target_simnum - existing_count
    
    # 다음 저장할 인덱스
    start_index = get_next_json_index(dataset, GEN_DIR)
    
    # 로그 출력
    print(f"\n{'='*60}")
    print(f"[DATASET] {dataset}")
    print(f"  existing={existing_count}  target={target_simnum}  remaining={remaining}  start_index={start_index}")
    print(f"{'='*60}")
    
    # 이미 완료된 경우 스킵
    if remaining <= 0:
        print(f"[SKIP] dataset={dataset} already complete ({existing_count}/{target_simnum})")
        continue
    
    dataset_category = datasets_dict[dataset]['category_id']
    batch_name = f"{region}_{universe}_{dataset_category}"
    
    # remaining 만큼만 생성
    for i in range(remaining):
        
        current_index = start_index + i
        save_path = f"{GEN_DIR}/{dataset}_{current_index}.json"
        
        # 저장 전 파일 존재 여부 재확인 (레이스 방지)
        if os.path.exists(save_path):
            print(f"[SKIP] {save_path} already exists, skipping this batch")
            continue
        
        print(f"\n--- [{dataset}] Batch {i+1}/{remaining} (index={current_index}) ---")
        print("--- Generating alphas with LLM ---")
        
        try:
            # 🔧 MODIFIED: top_n_datafields 파라미터 추가
            # LLM은 각 dataset에서 alphaCount 상위 N개 datafield만 사용
            response = llm.generate_expressions_from_dataset(
                s, region, universe, dataset, 
                model='gpt-5-mini-2025-08-07', 
                datafields_num_cap=500,
                top_n_datafields=TOP_N_DATAFIELDS  # 🔧 NEW: 상위 N개 datafield만 전달
            )
        except Exception as e:
            print(f"[ERROR] LLM generation failed: {e}")
            continue
        
        print("--- Received response ---")
        
        try:
            json_response = llm.cut_first_to_last_brace(response)
            alphas = json.loads(json_response)
            print(f"--- Alpha generated successfully ---")
        except Exception as e:
            print(f"[ERROR] JSON parsing failed: {e}")
            continue
        
        # JSON 저장 (안전하게)
        if not save_json_safe(alphas, save_path):
            print(f"[WARN] Could not save {save_path}, skipping simulation")
            continue
        
        print(f"[SAVED] {save_path}")
        
        # ------------------------------------------------------------
        # 시뮬레이션 실행
        # ------------------------------------------------------------
        
        # Sanity check로 유효한 알파만 필터링
        alpha_expressions = [
            x for x in alphas.get("results", []) 
            if sanity_checker(x.get('implementation', ''), _debug=False)
        ]
        
        if len(alpha_expressions) == 0:
            print(f"[WARN] No valid alphas after sanity check")
            continue
        
        alpha_list = [
            ace.generate_alpha(
                regular=x['implementation'], 
                region=region, 
                universe=universe, 
                neutralization="INDUSTRY"
            ) 
            for x in alpha_expressions
        ]
        
        len_alpha_list = len(alpha_list)
        print(f"[INFO] eligible_alpha_count: {len_alpha_list}")
        
        tags_list = [
            ['llm_test', f"confidence_{x.get('confidence_level', 0)}"] 
            for x in alpha_expressions
        ]
        descs_list = [x.get('description', '') for x in alpha_expressions]
        
        # 8개씩 배치로 시뮬레이션
        for rep in range(0, len_alpha_list, 8):
            
            # 세션 타임아웃 체크
            if ace.check_session_timeout(s) < 500:
                print("[INFO] Session timeout approaching, refreshing...")
                s = ace.start_session()
            
            batch_end = min(rep + 8, len_alpha_list)
            
            try:
                print(f"--- Simulating alpha batch {rep} to {batch_end} ---")
                
                sim_results = list(
                    ace.multi_simulate_alphas_map(
                        s,
                        alpha_list[rep:batch_end],
                        tags_list[rep:batch_end],
                        descs_list[rep:batch_end],
                        batch_end - rep
                    )
                )
                
                df = pd.DataFrame([
                    ace.flatten_dict(x) 
                    for x in sim_results 
                    if 'id' in x.keys()
                ])
                
                if len(df) > 0:
                    append_and_save_csv(f"./results/{batch_name}.csv", df)
                    print(f"[SAVED] {len(df)} results to ./results/{batch_name}.csv")
                
                # 0-fail 알파를 good_alpha_list.json에 자동 저장
                added = append_good_alpha_list(sim_results)
                if added > 0:
                    print(f"[GOOD] {added} zero-fail alphas added to good_alpha_list.json")
                    
            except Exception as e:
                print(f"[ERROR] Simulation failed: {e}")
                continue

print("\n" + "="*60)
print("[DONE] All datasets processed")
print("="*60)

['risk60']
[CONFIG] Using top 10 datafields per dataset (by alphaCount)

============================================================
[DATASET] risk60
  existing=0  target=2  remaining=2  start_index=0
============================================================

--- [risk60] Batch 1/2 (index=0) ---
--- Generating alphas with LLM ---
[INFO] Selected top 4 datafields for dataset 'risk60':
  - rsk60_offer (alphaCount: 442, type: VECTOR)
  - rsk60_last (alphaCount: 434, type: VECTOR)
  - rsk60_crowding (alphaCount: 124, type: VECTOR)
  - rsk60_datatime (alphaCount: 94, type: VECTOR)
{
  "results": [
    {
      "idea": "Short-rate momentum (offer): recent rise in borrow offer rate predicts negative future returns",
      "description": "Used rsk60_offer (high coverage and userCount). Applied SUGGESTION1 partially (single but high-quality field). SUGGESTION2 applied (vec_avg for VECTOR). SUGGESTION3 not required (coverage 0.9567) but ts_backfill used per KEEP_IN_MIND1 to reduce gaps. SUGGESTION4 satisfied by choosing high user/alpha count. Kept implementation simple and <=4 operators. Confidence: 0.75",
      "implementation": "ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),20)",
      "confidence_level": 0.75
    },
    {
      "idea": "Short-rate reversal (offer): extreme low borrow offer suggests upcoming short-covering bounce",
      "description": "Used rsk60_offer. Applied vec_avg (SUGGESTION2). Included ts_backfill for robustness (KEEP_IN_MIND1). Used ts_zscore to detect extremes. Did not use multiple fields to stay simple (SUGGESTION1 partially). Confidence: 0.70",
      "implementation": "reverse(ts_zscore(ts_backfill(vec_avg(rsk60_offer),10),30))",
      "confidence_level": 0.7
    },
    {
      "idea": "Short-rate momentum (last): momentum in last-seen borrow rate",
      "description": "Used rsk60_last (high counts). Applied vec_avg per SUGGESTION2. ts_backfill included. Kept operators <=3. Did not combine fields to keep signal pure. Confidence: 0.72",
      "implementation": "ts_zscore(ts_backfill(vec_avg(rsk60_last),5),15)",
      "confidence_level": 0.72
    },
    {
      "idea": "Rapid change in last borrow rate: ts_delta of last borrow rate",
      "description": "Used rsk60_last with vec_avg (SUGGESTION2). ts_backfill applied for safety. ts_delta used to capture recent jump. SUGGESTION1 not applied (single field) but chosen for high user/alphaCount. Confidence: 0.68",
      "implementation": "ts_zscore(ts_backfill(ts_delta(vec_avg(rsk60_last),5),5),20)",
      "confidence_level": 0.68
    },
    {
      "idea": "Crowding mean anomaly: high crowding score indicates heavy short interest",
      "description": "Used rsk60_crowding (VECTOR). Applied vec_avg per SUGGESTION2 and ts_backfill to be conservative. SUGGESTION1 not used multiple fields because crowding is direct signal. Chose despite lower userCount; coverage adequate. Confidence: 0.66",
      "implementation": "ts_zscore(ts_backfill(vec_avg(rsk60_crowding),3),10)",
      "confidence_level": 0.66
    },
    {
      "idea": "Crowding trend: momentum in crowding (ts_delta)",
      "description": "rsk60_crowding with vec_avg and ts_backfill used. ts_delta isolates rapid increases indicating fresh shorting. SUGGESTION4 less satisfied (crowding lower userCount) but signal is intuitive. Confidence: 0.64",
      "implementation": "ts_zscore(ts_backfill(ts_delta(vec_avg(rsk60_crowding),7),7),15)",
      "confidence_level": 0.64
    },
    {
      "idea": "Offer vs Last spread: offer - last indicates market tension in borrow pricing",
      "description": "Combined rsk60_offer and rsk60_last (SUGGESTION1) using vec_avg for each (SUGGESTION2). ts_backfill added for both. Kept operators count low. Rationale: persistent positive spread suggests illiquidity/pressure. Confidence: 0.78",
      "implementation": "ts_zscore(subtract(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5)),20)",
      "confidence_level": 0.78
    },
    {
      "idea": "Offer/Last ratio: relative markup as stress indicator",
      "description": "Used rsk60_offer and rsk60_last, vec_avg wrapped per SUGGESTION2. ts_backfill for both. divide used to form ratio then ts_zscore. Kept <=4 operators. Confidence: 0.76",
      "implementation": "ts_zscore(divide(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5)),20)",
      "confidence_level": 0.76
    },
    {
      "idea": "Offer short-term mean reversion: deviation from 5-day mean",
      "description": "rsk60_offer with vec_avg, ts_backfill, and ts_av_diff to get deviation then ts_zscore. Followed KEEP_IN_MINDs. SUGGESTION1 single-field used. Confidence: 0.69",
      "implementation": "ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_offer),5),5),15)",
      "confidence_level": 0.69
    },
    {
      "idea": "Last borrow rate volatility (short-term ts_std_dev)",
      "description": "Used rsk60_last vec_avg + ts_backfill + ts_std_dev to capture recent volatility in borrow activity. SUGGESTION1 single-field acceptable due to high alphaCount. Confidence: 0.65",
      "implementation": "ts_zscore(ts_backfill(ts_std_dev(vec_avg(rsk60_last),10),5),20)",
      "confidence_level": 0.65
    },
    {
      "idea": "Offer flow accumulation: ts_sum of offer to capture persistent high borrow costs",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_sum. SUGGESTION2 applied; kept simple. Persistent high sum suggests ongoing demand to borrow. Confidence: 0.67",
      "implementation": "ts_zscore(ts_backfill(ts_sum(vec_avg(rsk60_offer),20),5),20)",
      "confidence_level": 0.67
    },
    {
      "idea": "Crowding persistence: ts_sum of crowding scores to detect sustained shorting",
      "description": "rsk60_crowding vec_avg + ts_backfill + ts_sum. Used to detect persistent short bias. SUGGESTION4 partially (lower userCount) but crowding is specialized. Confidence: 0.62",
      "implementation": "ts_zscore(ts_backfill(ts_sum(vec_avg(rsk60_crowding),15),5),20)",
      "confidence_level": 0.62
    },
    {
      "idea": "Offer-last momentum divergence: recent divergence predicts mean reversion",
      "description": "Combined rsk60_offer and rsk60_last. Used ts_delta on their difference: vec_avg + ts_backfill for both, ts_delta and ts_zscore within operator budget. SUGGESTION1 applied. Confidence: 0.73",
      "implementation": "ts_zscore(ts_delta(subtract(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5)),5),20)",
      "confidence_level": 0.73
    },
    {
      "idea": "Crowding vs Offer correlation: high crowding with rising offer indicates acute short pressure",
      "description": "Used rsk60_crowding and rsk60_offer (SUGGESTION1). Wrapped both with vec_avg and ts_backfill (KEEP_IN_MIND1). ts_corr used to measure co-movement; then ts_zscore. Confidence: 0.74",
      "implementation": "ts_zscore(ts_corr(ts_backfill(vec_avg(rsk60_crowding),5),ts_backfill(vec_avg(rsk60_offer),5),20),20)",
      "confidence_level": 0.74
    },
    {
      "idea": "Last borrow peak detection (ts_arg_max on last)",
      "description": "rsk60_last vec_avg wrapped; ts_backfill used. ts_arg_max identifies if current day is local peak; zscore applied to convert signal. SUGGESTION2 applied. Confidence: 0.60",
      "implementation": "ts_zscore(ts_backfill(ts_arg_max(vec_avg(rsk60_last),10),5),10)",
      "confidence_level": 0.6
    },
    {
      "idea": "Offer extremes winsorized zscore (robust extreme detection)",
      "description": "rsk60_offer with vec_avg, ts_backfill, winsorize then ts_zscore to limit outliers per KEEP_IN_MIND1. Winsorize reduces tail risk. SUGGESTION1 single-field. Confidence: 0.68",
      "implementation": "ts_zscore(winsorize(ts_backfill(vec_avg(rsk60_offer),5),4),20)",
      "confidence_level": 0.68
    },
    {
      "idea": "Crowding last-change days: days_from_last_change on crowding to identify fresh shifts",
      "description": "Used rsk60_crowding with vec_avg and days_from_last_change then ts_zscore. SUGGESTION2 applied; detected fresh covering/shorting events. Confidence: 0.61",
      "implementation": "ts_zscore(days_from_last_change(ts_backfill(vec_avg(rsk60_crowding),5)),20)",
      "confidence_level": 0.61
    },
    {
      "idea": "Offer decelerating move: ts_regression slope negative indicates slowing borrow demand",
      "description": "rsk60_offer + vec_avg + ts_backfill + ts_regression (slope via rettype) then ts_zscore. SUGGESTION1 single-field. Kept operators count minimal. Confidence: 0.66",
      "implementation": "ts_zscore(ts_backfill(ts_regression(vec_avg(rsk60_offer),vec_avg(rsk60_offer),20,0,1),5),20)",
      "confidence_level": 0.66
    },
    {
      "idea": "Last rolling IR (ts_ir): stable signal normalization",
      "description": "Used rsk60_last vec_avg + ts_backfill + ts_ir to measure mean/std over lookback then ts_zscore. Normalizes signal and reduces noise. Confidence: 0.63",
      "implementation": "ts_zscore(ts_backfill(ts_ir(vec_avg(rsk60_last),20),5),20)",
      "confidence_level": 0.63
    },
    {
      "idea": "Offer short-term kurtosis: detect fat tails in borrow rate distribution",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_kurtosis then ts_zscore. SUGGESTION2 applied. High kurtosis flags jumps in borrowing behavior. Confidence: 0.58",
      "implementation": "ts_zscore(ts_backfill(ts_kurtosis(vec_avg(rsk60_offer),20),5),20)",
      "confidence_level": 0.58
    },
    {
      "idea": "Crowding sign flip signal: sign of recent ts_delta(crowding)",
      "description": "rsk60_crowding vec_avg + ts_backfill + ts_delta then sign to capture flip direction. zscore optional for scaling. SUGGESTION2 used. Confidence: 0.60",
      "implementation": "ts_zscore(sign(ts_backfill(ts_delta(vec_avg(rsk60_crowding),3),3)),10)",
      "confidence_level": 0.6
    },
    {
      "idea": "Offer fast mean reversion using ts_rank short lookback",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_rank (short d=5) then zscore to pick extreme ranks. SUGGESTION2 applied; quick-turn signal. Confidence: 0.67",
      "implementation": "ts_zscore(ts_backfill(ts_rank(vec_avg(rsk60_offer),5),3),10)",
      "confidence_level": 0.67
    },
    {
      "idea": "Last borrow rolling max drawdown (ts_max_diff)",
      "description": "rsk60_last vec_avg + ts_backfill + ts_max_diff to capture distance from recent high; ts_zscore for scaling. Useful for detecting sudden demand. Confidence: 0.64",
      "implementation": "ts_zscore(ts_backfill(ts_max_diff(vec_avg(rsk60_last),20),5),20)",
      "confidence_level": 0.64
    },
    {
      "idea": "Offer normalized by 60-day mean (zscore of x - mean)",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_av_diff (d=60) then ts_zscore to normalize. Longer-term context reduces noise. SUGGESTION2 applied. Confidence: 0.71",
      "implementation": "ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_offer),60),5),20)",
      "confidence_level": 0.71
    },
    {
      "idea": "Crowding vs last correlation change: ts_corr of crowding and last over rolling window",
      "description": "Used rsk60_crowding & rsk60_last (SUGGESTION1). vec_avg + ts_backfill for both and ts_corr for co-movement; zscore to standardize. Confidence: 0.72",
      "implementation": "ts_zscore(ts_corr(ts_backfill(vec_avg(rsk60_crowding),5),ts_backfill(vec_avg(rsk60_last),5),30),20)",
      "confidence_level": 0.72
    },
    {
      "idea": "Offer short-term product: capture days when both offer and last rise together",
      "description": "Combined rsk60_offer & rsk60_last via multiply after vec_avg and ts_backfill to detect simultaneous increase; then ts_zscore. SUGGESTION1 applied. Confidence: 0.69",
      "implementation": "ts_zscore(multiply(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5)),20)",
      "confidence_level": 0.69
    },
    {
      "idea": "Crowding extremes bucketed: bucket extreme crowding into signals",
      "description": "rsk60_crowding vec_avg + ts_backfill; bucket applied on ts_zscore to form categorical signals. Kept operator count low. SUGGESTION2 used. Confidence: 0.59",
      "implementation": "bucket(ts_zscore(ts_backfill(vec_avg(rsk60_crowding),5),20),range=\"-3,3,0.5\")",
      "confidence_level": 0.59
    },
    {
      "idea": "Offer decayed signal for turnover control: apply hump to zscore",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_zscore then hump to limit turnover per KEEP_IN_MIND1. SUGGESTION2 applied. Confidence: 0.66",
      "implementation": "hump(ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),20),hump=0.02)",
      "confidence_level": 0.66
    },
    {
      "idea": "Last returns correlation with offer (predictive coupling)",
      "description": "Combined rsk60_last (vec_avg) and rsk60_offer (vec_avg) with ts_corr to find predictive coupling, backfilled and zscored. SUGGESTION1 applied. Confidence: 0.68",
      "implementation": "ts_zscore(ts_corr(ts_backfill(vec_avg(rsk60_last),5),ts_backfill(vec_avg(rsk60_offer),5),15),20)",
      "confidence_level": 0.68
    },
    {
      "idea": "Offer relative momentum: ts_returns of vec_avg(offer)",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_returns then ts_zscore. Captures percentage moves. SUGGESTION2 applied. Confidence: 0.65",
      "implementation": "ts_zscore(ts_backfill(ts_returns(vec_avg(rsk60_offer),5,1),5),20)",
      "confidence_level": 0.65
    },
    {
      "idea": "Crowding short-cover signal: large negative crowding implies covering -> price uptick",
      "description": "rsk60_crowding vec_avg + ts_backfill + ts_zscore. Signal is sign-aware (reverse if negative). SUGGESTION2 applied; used direct field. Confidence: 0.63",
      "implementation": "reverse(ts_zscore(ts_backfill(vec_avg(rsk60_crowding),5),20))",
      "confidence_level": 0.63
    },
    {
      "idea": "Offer-day-of-week effect using datatime vector average",
      "description": "Used rsk60_datatime to see periodicities; vec_avg + ts_backfill + ts_rank to pick days with typical spikes. SUGGESTION2 applied. Coverage high. Confidence: 0.50",
      "implementation": "ts_zscore(ts_backfill(vec_avg(rsk60_datatime),7),20)",
      "confidence_level": 0.5
    },
    {
      "idea": "Last borrow decay-weighted (ts_decay_linear) to prioritize recent changes",
      "description": "rsk60_last vec_avg + ts_backfill + ts_decay_linear (d=10) then ts_zscore. Kept operator count low. SUGGESTION2 applied. Confidence: 0.66",
      "implementation": "ts_zscore(ts_backfill(ts_decay_linear(vec_avg(rsk60_last),10),5),20)",
      "confidence_level": 0.66
    },
    {
      "idea": "Offer vs crowding divergence (subtract crowding from offer)",
      "description": "Used rsk60_offer & rsk60_crowding. vec_avg & ts_backfill on both; subtract and ts_zscore. SUGGESTION1 applied to combine liquidity price with behavioural score. Confidence: 0.74",
      "implementation": "ts_zscore(subtract(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_crowding),5)),20)",
      "confidence_level": 0.74
    },
    {
      "idea": "Crowding volatility (vec_stddev) to identify erratic short interest",
      "description": "rsk60_crowding vec_avg + ts_backfill + vec_stddev to get intraday vector spread then ts_zscore. SUGGESTION2 applied; helps detect unstable shorts. Confidence: 0.60",
      "implementation": "ts_zscore(ts_backfill(vec_stddev(vec_avg(rsk60_crowding)),5),20)",
      "confidence_level": 0.6
    },
    {
      "idea": "Offer 10-day vs 60-day zscore difference: short-term vs long-term tension",
      "description": "rsk60_offer vec_avg with ts_backfill; compute ts_zscore with two different lookbacks and subtract to find regime shifts. SUGGESTION1 single-field used. Confidence: 0.70",
      "implementation": "subtract(ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),10),ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),60))",
      "confidence_level": 0.7
    },
    {
      "idea": "Last borrow count of NaNs (data sparsity) as risk indicator",
      "description": "rsk60_last vec_avg + ts_backfill + ts_count_nans to detect thinning borrow trades; zscore to normalize. SUGGESTION2 applied; coverage high so NaNs low but useful. Confidence: 0.55",
      "implementation": "ts_zscore(ts_backfill(ts_count_nans(vec_avg(rsk60_last),20),5),20)",
      "confidence_level": 0.55
    },
    {
      "idea": "Offer-time decay product with crowding: detect sustained expensive borrow with high crowding",
      "description": "rsk60_offer & rsk60_crowding combined. vec_avg + ts_backfill then multiply and ts_zscore. SUGGESTION1 used. Confidence: 0.73",
      "implementation": "ts_zscore(multiply(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_crowding),5)),20)",
      "confidence_level": 0.73
    },
    {
      "idea": "Crowding argmax to find recent peaks in shorting",
      "description": "rsk60_crowding vec_avg + ts_backfill + ts_arg_max then ts_zscore. Detects whether current day is local max. SUGGESTION2 applied. Confidence: 0.61",
      "implementation": "ts_zscore(ts_backfill(ts_arg_max(vec_avg(rsk60_crowding),10),5),10)",
      "confidence_level": 0.61
    },
    {
      "idea": "Offer normalized scale over 30 days (ts_scale)",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_scale(d=30) then ts_zscore for ranking. Simple normalized level signal. SUGGESTION2 applied. Confidence: 0.68",
      "implementation": "ts_zscore(ts_backfill(ts_scale(vec_avg(rsk60_offer),30),5),20)",
      "confidence_level": 0.68
    },
    {
      "idea": "Last borrow product of recent returns and crowding (interaction)",
      "description": "rsk60_last & rsk60_crowding combined. vec_avg+ts_backfill applied to both; multiply recent return (ts_returns) with crowding level then ts_zscore. SUGGESTION1 used. Confidence: 0.69",
      "implementation": "ts_zscore(multiply(ts_backfill(ts_returns(vec_avg(rsk60_last),5,1),5),ts_backfill(vec_avg(rsk60_crowding),5)),20)",
      "confidence_level": 0.69
    },
    {
      "idea": "Offer 3-day reversal (negative of short-term ts_rank)",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_rank(d=3) then reverse and ts_zscore for contrarian trades. SUGGESTION2 applied. Confidence: 0.66",
      "implementation": "ts_zscore(reverse(ts_backfill(ts_rank(vec_avg(rsk60_offer),3),3)),10)",
      "confidence_level": 0.66
    },
    {
      "idea": "Crowding count of recent non-NaN (vec_count) to measure activity breadth",
      "description": "Applied vec_count on crowding vector then ts_backfill and ts_zscore. SUGGESTION2 used. Measures how many venues reporting crowding, proxy for conviction. Confidence: 0.57",
      "implementation": "ts_zscore(ts_backfill(vec_count(vec_avg(rsk60_crowding)),5),20)",
      "confidence_level": 0.57
    },
    {
      "idea": "Offer - 20-day moving mean (difference) for medium-term deviation",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_av_diff(d=20) then ts_zscore. SUGGESTION2 applied. Balances responsiveness and noise. Confidence: 0.69",
      "implementation": "ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_offer),20),5),20)",
      "confidence_level": 0.69
    },
    {
      "idea": "Last borrow trend strength via ts_regression slope magnitude",
      "description": "rsk60_last vec_avg + ts_backfill + ts_regression (slope) then ts_zscore. SUGGESTION2 applied. Captures consistent trending in borrow trades. Confidence: 0.64",
      "implementation": "ts_zscore(ts_backfill(ts_regression(vec_avg(rsk60_last),vec_avg(rsk60_last),30,0,1),5),20)",
      "confidence_level": 0.64
    },
    {
      "idea": "Offer mean-variance signal using ts_ir to prefer stable high mean",
      "description": "rsk60_offer vec_avg + ts_backfill + ts_ir then ts_zscore. SUGGESTION2 applied. Targets high information ratio in borrow cost. Confidence: 0.65",
      "implementation": "ts_zscore(ts_backfill(ts_ir(vec_avg(rsk60_offer),30),5),20)",

2026-02-07 13:31:00,356 - ace - ERROR - Simulation failed. {'id': '4wGJlZ2LI4hl8DCUPVnOdhk', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 10, 'end': 58, 'property': 'regular'}}

{'id': 'QPr2r25p', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_offer),5),5),15)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:32:04-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:32:04-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1430544, 'bookSize': 20000000, 'longCount': 762, 'shortCount': 725, 'turnover': 0.9097, 'returns': 0.0139, 'drawdown': 0.0857, 'margin': 3e-05, 'sharpe': 0.46, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -429490, 'bookSize': 20000000, 'longCount': 834, 'shortCount': 788, 'turnover': 0.1999, 'returns': -0.0042, 'drawdown': 0.1128, 'margin': -4.2e-05, 'fitness': -0.02, 'sharpe': -0.13}, 'riskNeutralized': {'pnl': 1028976, 'bookSize': 20000000, 'longCount': 762, 'shortCount': 725, 'turnover': 0.9097, 'returns': 0.01, 'drawdown': 0.0944, 'margin': 2.2e-05, 'fitness': 0.04, 'sharpe': 0.4}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.46}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9097}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9097}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.24, 'value': 0.33}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.61, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Jj0g0gmA', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_sum(vec_avg(rsk60_crowding),15),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:32:02-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:32:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -936875, 'bookSize': 20000000, 'longCount': 874, 'shortCount': 922, 'turnover': 0.4364, 'returns': -0.0113, 'drawdown': 0.1019, 'margin': -5.2e-05, 'sharpe': -0.44, 'fitness': -0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -364093, 'bookSize': 20000000, 'longCount': 915, 'shortCount': 943, 'turnover': 0.1403, 'returns': -0.0044, 'drawdown': 0.123, 'margin': -6.2e-05, 'fitness': -0.03, 'sharpe': -0.16}, 'riskNeutralized': {'pnl': -34175, 'bookSize': 20000000, 'longCount': 874, 'shortCount': 922, 'turnover': 0.4364, 'returns': -0.0004, 'drawdown': 0.0521, 'margin': -2e-06, 'fitness': -0.0, 'sharpe': -0.02}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.44}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4364}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4364}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.23, 'value': -0.68}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.0, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'KPYXYXOj', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_delta(subtract(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5)),5),20)', 'description': None, 'operatorCount': 7}, 'dateCreated': '2026-02-06T23:32:09-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:32:10-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.73'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -145401, 'bookSize': 20000000, 'longCount': 923, 'shortCount': 896, 'turnover': 1.2366, 'returns': -0.0014, 'drawdown': 0.1054, 'margin': -2e-06, 'sharpe': -0.05, 'fitness': -0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -120794, 'bookSize': 20000000, 'longCount': 938, 'shortCount': 947, 'turnover': 0.2567, 'returns': -0.0012, 'drawdown': 0.1318, 'margin': -9e-06, 'fitness': -0.0, 'sharpe': -0.04}, 'riskNeutralized': {'pnl': 32322, 'bookSize': 20000000, 'longCount': 923, 'shortCount': 896, 'turnover': 1.2366, 'returns': 0.0003, 'drawdown': 0.0917, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.01}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.05}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.2366}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.2366}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.03, 'value': -0.11}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.7, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E50g0gQR', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_sum(vec_avg(rsk60_offer),20),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:32:12-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:32:12-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1524646, 'bookSize': 20000000, 'longCount': 911, 'shortCount': 938, 'turnover': 0.2305, 'returns': 0.0148, 'drawdown': 0.0804, 'margin': 0.000128, 'sharpe': 0.63, 'fitness': 0.16, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -735146, 'bookSize': 20000000, 'longCount': 946, 'shortCount': 988, 'turnover': 0.1081, 'returns': -0.0071, 'drawdown': 0.1526, 'margin': -0.000132, 'fitness': -0.07, 'sharpe': -0.3}, 'riskNeutralized': {'pnl': 1131025, 'bookSize': 20000000, 'longCount': 911, 'shortCount': 938, 'turnover': 0.2305, 'returns': 0.011, 'drawdown': 0.065, 'margin': 9.5e-05, 'fitness': 0.13, 'sharpe': 0.61}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.63}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.16}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2305}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2305}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.33, 'value': 0.66}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.3, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'mL2r2Zw6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_arg_max(vec_avg(rsk60_last),10),5),10)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:32:46-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:32:47-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 354468, 'bookSize': 20000000, 'longCount': 1016, 'shortCount': 786, 'turnover': 0.6825, 'returns': 0.0034, 'drawdown': 0.0463, 'margin': 1e-05, 'sharpe': 0.15, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 401498, 'bookSize': 20000000, 'longCount': 1026, 'shortCount': 891, 'turnover': 0.2031, 'returns': 0.0039, 'drawdown': 0.1046, 'margin': 3.8e-05, 'fitness': 0.02, 'sharpe': 0.15}, 'riskNeutralized': {'pnl': 198854, 'bookSize': 20000000, 'longCount': 1016, 'shortCount': 786, 'turnover': 0.6825, 'returns': 0.0019, 'drawdown': 0.0493, 'margin': 6e-06, 'fitness': 0.01, 'sharpe': 0.1}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.15}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6825}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6825}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.08, 'value': 0.05}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.42, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'j2l9l16k', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_std_dev(vec_avg(rsk60_last),10),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:32:57-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:32:58-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 168147, 'bookSize': 20000000, 'longCount': 873, 'shortCount': 1054, 'turnover': 0.3618, 'returns': 0.0016, 'drawdown': 0.0652, 'margin': 9e-06, 'sharpe': 0.08, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 379615, 'bookSize': 20000000, 'longCount': 920, 'shortCount': 1059, 'turnover': 0.1428, 'returns': 0.0037, 'drawdown': 0.0582, 'margin': 5.2e-05, 'fitness': 0.03, 'sharpe': 0.17}, 'riskNeutralized': {'pnl': -41599, 'bookSize': 20000000, 'longCount': 873, 'shortCount': 1054, 'turnover': 0.3618, 'returns': -0.0004, 'drawdown': 0.0612, 'margin': -2e-06, 'fitness': -0.0, 'sharpe': -0.02}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.08}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3618}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3618}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.04, 'value': 0.34}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.15, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:33:06,609 - ace - ERROR - Simulation failed. {'id': '2Cf5Tj8T751QauaAYKQsqgI', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 4, should be exactly 2 input(s)', 'location': {'line': 1, 'start': 22, 'end': 85, 'property': 'regular'}}

{'id': 'E50g0EqK', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(sign(ts_backfill(ts_delta(vec_avg(rsk60_crowding),3),3)),10)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-06T23:34:13-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:34:14-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -641970, 'bookSize': 20000000, 'longCount': 656, 'shortCount': 661, 'turnover': 1.3062, 'returns': -0.0077, 'drawdown': 0.1096, 'margin': -1.2e-05, 'sharpe': -0.23, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -745313, 'bookSize': 20000000, 'longCount': 732, 'shortCount': 721, 'turnover': 0.2265, 'returns': -0.009, 'drawdown': 0.1846, 'margin': -7.9e-05, 'fitness': -0.05, 'sharpe': -0.25}, 'riskNeutralized': {'pnl': -477815, 'bookSize': 20000000, 'longCount': 656, 'shortCount': 661, 'turnover': 1.3062, 'returns': -0.0057, 'drawdown': 0.106, 'margin': -9e-06, 'fitness': -0.01, 'sharpe': -0.2}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.23}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3062}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3062}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-09-09', 'limit': 0.1, 'value': 0.320568}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.12, 'value': -0.02}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.02, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'pwJVJl8X', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(days_from_last_change(ts_backfill(vec_avg(rsk60_crowding),5)),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:34:14-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:34:14-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 606806, 'bookSize': 20000000, 'longCount': 1593, 'shortCount': 1149, 'turnover': 0.3366, 'returns': 0.0073, 'drawdown': 0.0589, 'margin': 4.3e-05, 'sharpe': 0.27, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 797705, 'bookSize': 20000000, 'longCount': 1551, 'shortCount': 1216, 'turnover': 0.1133, 'returns': 0.0096, 'drawdown': 0.0512, 'margin': 0.000169, 'fitness': 0.09, 'sharpe': 0.34}, 'riskNeutralized': {'pnl': 173658, 'bookSize': 20000000, 'longCount': 1593, 'shortCount': 1149, 'turnover': 0.3366, 'returns': 0.0021, 'drawdown': 0.0351, 'margin': 1.2e-05, 'fitness': 0.01, 'sharpe': 0.13}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.27}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3366}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3366}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.14, 'value': 0.23}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.26, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'MPlKlQp9', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_ir(vec_avg(rsk60_last),20),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:34:15-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:34:15-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 99529, 'bookSize': 20000000, 'longCount': 831, 'shortCount': 1055, 'turnover': 0.3533, 'returns': 0.001, 'drawdown': 0.054, 'margin': 5e-06, 'sharpe': 0.05, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -436659, 'bookSize': 20000000, 'longCount': 887, 'shortCount': 1080, 'turnover': 0.1335, 'returns': -0.0042, 'drawdown': 0.1064, 'margin': -6.3e-05, 'fitness': -0.03, 'sharpe': -0.19}, 'riskNeutralized': {'pnl': 260479, 'bookSize': 20000000, 'longCount': 831, 'shortCount': 1055, 'turnover': 0.3533, 'returns': 0.0025, 'drawdown': 0.0397, 'margin': 1.4e-05, 'fitness': 0.01, 'sharpe': 0.15}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.05}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3533}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3533}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.03, 'value': -0.12}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.4, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'kqk1kZqL', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_offer),60),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:34:29-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:34:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2272042, 'bookSize': 20000000, 'longCount': 836, 'shortCount': 951, 'turnover': 0.4607, 'returns': 0.022, 'drawdown': 0.027, 'margin': 9.6e-05, 'sharpe': 0.94, 'fitness': 0.21, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 707157, 'bookSize': 20000000, 'longCount': 895, 'shortCount': 974, 'turnover': 0.137, 'returns': 0.0069, 'drawdown': 0.0776, 'margin': 0.0001, 'fitness': 0.06, 'sharpe': 0.27}, 'riskNeutralized': {'pnl': 1065192, 'bookSize': 20000000, 'longCount': 836, 'shortCount': 951, 'turnover': 0.4607, 'returns': 0.0103, 'drawdown': 0.0373, 'margin': 4.5e-05, 'fitness': 0.08, 'sharpe': 0.55}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.94}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.21}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4607}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4607}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.49, 'value': 0.93}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.84, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1JgJ71Q', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_kurtosis(vec_avg(rsk60_offer),20),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:34:29-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:34:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1096111, 'bookSize': 20000000, 'longCount': 460, 'shortCount': 652, 'turnover': 0.4342, 'returns': 0.0106, 'drawdown': 0.051, 'margin': 4.9e-05, 'sharpe': 0.38, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -607667, 'bookSize': 20000000, 'longCount': 542, 'shortCount': 752, 'turnover': 0.126, 'returns': -0.0059, 'drawdown': 0.1584, 'margin': -9.4e-05, 'fitness': -0.04, 'sharpe': -0.2}, 'riskNeutralized': {'pnl': 793744, 'bookSize': 20000000, 'longCount': 460, 'shortCount': 652, 'turnover': 0.4342, 'returns': 0.0077, 'drawdown': 0.0625, 'margin': 3.5e-05, 'fitness': 0.04, 'sharpe': 0.32}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.38}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4342}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4342}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.2, 'value': 0.31}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.22, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Gr0M0e1o', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_max_diff(vec_avg(rsk60_last),20),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:34:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:34:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1220200, 'bookSize': 20000000, 'longCount': 935, 'shortCount': 952, 'turnover': 0.626, 'returns': 0.0118, 'drawdown': 0.0426, 'margin': 3.8e-05, 'sharpe': 0.55, 'fitness': 0.08, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 578812, 'bookSize': 20000000, 'longCount': 943, 'shortCount': 1000, 'turnover': 0.1749, 'returns': 0.0056, 'drawdown': 0.0857, 'margin': 6.4e-05, 'fitness': 0.04, 'sharpe': 0.24}, 'riskNeutralized': {'pnl': 907429, 'bookSize': 20000000, 'longCount': 935, 'shortCount': 952, 'turnover': 0.626, 'returns': 0.0088, 'drawdown': 0.0387, 'margin': 2.8e-05, 'fitness': 0.06, 'sharpe': 0.49}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.55}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.08}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.626}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.626}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.29, 'value': 0.24}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.37, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:34:42,647 - ace - ERROR - Simulation failed. {'id': '2NCtKXawG59y8RP13O4mygdI', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}
2026-02-07 13:34:43,404 - ace - ERROR - Simulation failed. {'id': '4BEDkYawf4Glbb111Dwd7l5x', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 22, 'end': 58, 'property': 'regular'}}

{'id': '1YVaVwrJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_zscore(ts_backfill(vec_avg(rsk60_crowding),5),20))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:35:43-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:35:43-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 708949, 'bookSize': 20000000, 'longCount': 938, 'shortCount': 763, 'turnover': 1.3871, 'returns': 0.0085, 'drawdown': 0.1342, 'margin': 1.2e-05, 'sharpe': 0.23, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 214106, 'bookSize': 20000000, 'longCount': 954, 'shortCount': 829, 'turnover': 0.2352, 'returns': 0.0026, 'drawdown': 0.1876, 'margin': 2.2e-05, 'fitness': 0.01, 'sharpe': 0.06}, 'riskNeutralized': {'pnl': 285209, 'bookSize': 20000000, 'longCount': 938, 'shortCount': 763, 'turnover': 1.3871, 'returns': 0.0034, 'drawdown': 0.1054, 'margin': 5e-06, 'fitness': 0.01, 'sharpe': 0.11}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.23}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3871}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3871}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.12, 'value': 0.53}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.16, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'N1WgWQOq', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_corr(ts_backfill(vec_avg(rsk60_crowding),5),ts_backfill(vec_avg(rsk60_last),5),30),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:35:54-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:35:54-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -936574, 'bookSize': 20000000, 'longCount': 704, 'shortCount': 739, 'turnover': 0.4281, 'returns': -0.0113, 'drawdown': 0.1439, 'margin': -5.3e-05, 'sharpe': -0.41, 'fitness': -0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -182041, 'bookSize': 20000000, 'longCount': 752, 'shortCount': 794, 'turnover': 0.1248, 'returns': -0.0022, 'drawdown': 0.1716, 'margin': -3.5e-05, 'fitness': -0.01, 'sharpe': -0.08}, 'riskNeutralized': {'pnl': -884162, 'bookSize': 20000000, 'longCount': 704, 'shortCount': 739, 'turnover': 0.4281, 'returns': -0.0106, 'drawdown': 0.1271, 'margin': -5e-05, 'fitness': -0.07, 'sharpe': -0.44}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.41}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4281}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4281}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.21, 'value': -0.82}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.11, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZ2ZbPn', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5)),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:36:28-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:36:29-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2098367, 'bookSize': 20000000, 'longCount': 700, 'shortCount': 1062, 'turnover': 0.8289, 'returns': 0.0203, 'drawdown': 0.0437, 'margin': 4.9e-05, 'sharpe': 0.76, 'fitness': 0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -342929, 'bookSize': 20000000, 'longCount': 776, 'shortCount': 1077, 'turnover': 0.1882, 'returns': -0.0033, 'drawdown': 0.1699, 'margin': -3.5e-05, 'fitness': -0.01, 'sharpe': -0.11}, 'riskNeutralized': {'pnl': 1504029, 'bookSize': 20000000, 'longCount': 700, 'shortCount': 1062, 'turnover': 0.8289, 'returns': 0.0146, 'drawdown': 0.0335, 'margin': 3.5e-05, 'fitness': 0.09, 'sharpe': 0.68}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.76}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.8289}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.8289}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.39, 'value': 0.84}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.03, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'KPYXYN2k', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_corr(ts_backfill(vec_avg(rsk60_last),5),ts_backfill(vec_avg(rsk60_offer),5),15),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:36:29-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:36:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -61002, 'bookSize': 20000000, 'longCount': 544, 'shortCount': 455, 'turnover': 0.457, 'returns': -0.0006, 'drawdown': 0.0833, 'margin': -3e-06, 'sharpe': -0.02, 'fitness': -0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -450864, 'bookSize': 20000000, 'longCount': 629, 'shortCount': 563, 'turnover': 0.1204, 'returns': -0.0044, 'drawdown': 0.1369, 'margin': -7.3e-05, 'fitness': -0.02, 'sharpe': -0.13}, 'riskNeutralized': {'pnl': -561145, 'bookSize': 20000000, 'longCount': 544, 'shortCount': 455, 'turnover': 0.457, 'returns': -0.0054, 'drawdown': 0.0933, 'margin': -2.4e-05, 'fitness': -0.02, 'sharpe': -0.21}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.02}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.457}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.457}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.01, 'value': -0.25}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.48, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'wpwnwbN5', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(vec_avg(rsk60_datatime),7),20)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-06T23:36:52-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:36:52-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.5'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3537633, 'bookSize': 20000000, 'longCount': 957, 'shortCount': 1042, 'turnover': 1.0162, 'returns': 0.0454, 'drawdown': 0.2218, 'margin': 8.9e-05, 'sharpe': 0.49, 'fitness': 0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2098264, 'bookSize': 20000000, 'longCount': 1076, 'shortCount': 1102, 'turnover': 0.2169, 'returns': 0.0269, 'drawdown': 0.2301, 'margin': 0.000248, 'fitness': 0.08, 'sharpe': 0.24}, 'riskNeutralized': {'pnl': 5865349, 'bookSize': 20000000, 'longCount': 957, 'shortCount': 1042, 'turnover': 1.0162, 'returns': 0.0753, 'drawdown': 0.2087, 'margin': 0.000148, 'fitness': 0.18, 'sharpe': 0.65}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.49}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0162}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0162}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2020-01-24', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.25, 'value': 0.18}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.69, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'gJqRqZLQ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'hump(ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),20),hump=0.02)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:36:55-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:36:56-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 965700, 'bookSize': 20000000, 'longCount': 745, 'shortCount': 429, 'turnover': 0.0683, 'returns': 0.0094, 'drawdown': 0.0516, 'margin': 0.000274, 'sharpe': 0.35, 'fitness': 0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 133070, 'bookSize': 20000000, 'longCount': 872, 'shortCount': 515, 'turnover': 0.0408, 'returns': 0.0013, 'drawdown': 0.0915, 'margin': 6.3e-05, 'fitness': 0.01, 'sharpe': 0.05}, 'riskNeutralized': {'pnl': 436239, 'bookSize': 20000000, 'longCount': 745, 'shortCount': 429, 'turnover': 0.0683, 'returns': 0.0042, 'drawdown': 0.0728, 'margin': 0.000124, 'fitness': 0.04, 'sharpe': 0.2}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.35}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0683}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0683}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.18, 'value': 0.32}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.06, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[SAVED] 6 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 32 to 40 ---

2026-02-07 13:38:17,739 - ace - WARNING - Simulation PRCBtnP5hgbYavNt0vSfA failed. {'id': 'PRCBtnP5hgbYavNt0vSfA', 'type': 'REGULAR', 'status': 'FAIL'}

{'id': 'QPr2r06r', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_decay_linear(vec_avg(rsk60_last),10),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:38:11-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:38:11-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2133212, 'bookSize': 20000000, 'longCount': 791, 'shortCount': 975, 'turnover': 0.374, 'returns': 0.0207, 'drawdown': 0.0353, 'margin': 0.000111, 'sharpe': 0.88, 'fitness': 0.21, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -100618, 'bookSize': 20000000, 'longCount': 854, 'shortCount': 998, 'turnover': 0.14, 'returns': -0.001, 'drawdown': 0.1329, 'margin': -1.4e-05, 'fitness': -0.0, 'sharpe': -0.04}, 'riskNeutralized': {'pnl': 1177670, 'bookSize': 20000000, 'longCount': 791, 'shortCount': 975, 'turnover': 0.374, 'returns': 0.0114, 'drawdown': 0.0397, 'margin': 6.1e-05, 'fitness': 0.1, 'sharpe': 0.6}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.88}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.21}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.374}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.374}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.46, 'value': 0.95}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.45, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZ2Z5j0', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_crowding),5)),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:38:16-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:38:17-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.73'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -899263, 'bookSize': 20000000, 'longCount': 742, 'shortCount': 966, 'turnover': 1.3773, 'returns': -0.0108, 'drawdown': 0.1931, 'margin': -1.6e-05, 'sharpe': -0.28, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -263882, 'bookSize': 20000000, 'longCount': 810, 'shortCount': 979, 'turnover': 0.233, 'returns': -0.0032, 'drawdown': 0.2116, 'margin': -2.7e-05, 'fitness': -0.01, 'sharpe': -0.07}, 'riskNeutralized': {'pnl': -247498, 'bookSize': 20000000, 'longCount': 742, 'shortCount': 966, 'turnover': 1.3773, 'returns': -0.003, 'drawdown': 0.1095, 'margin': -4e-06, 'fitness': -0.0, 'sharpe': -0.09}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.28}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3773}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3773}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.15, 'value': -0.57}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.0, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'wpwnwod1', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_crowding),5)),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:38:14-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:38:14-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.74'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1232173, 'bookSize': 20000000, 'longCount': 839, 'shortCount': 755, 'turnover': 1.0897, 'returns': 0.0148, 'drawdown': 0.0871, 'margin': 2.7e-05, 'sharpe': 0.48, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -538279, 'bookSize': 20000000, 'longCount': 892, 'shortCount': 822, 'turnover': 0.2087, 'returns': -0.0065, 'drawdown': 0.1343, 'margin': -6.2e-05, 'fitness': -0.03, 'sharpe': -0.18}, 'riskNeutralized': {'pnl': 600745, 'bookSize': 20000000, 'longCount': 839, 'shortCount': 755, 'turnover': 1.0897, 'returns': 0.0072, 'drawdown': 0.0784, 'margin': 1.3e-05, 'fitness': 0.02, 'sharpe': 0.27}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.48}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0897}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0897}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.25, 'value': 0.78}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.31, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'gJqRqr6g', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),10),ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),60))', 'description': None, 'operatorCount': 7}, 'dateCreated': '2026-02-06T23:38:17-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:38:18-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -854011, 'bookSize': 20000000, 'longCount': 486, 'shortCount': 448, 'turnover': 0.5901, 'returns': -0.0083, 'drawdown': 0.1652, 'margin': -2.8e-05, 'sharpe': -0.25, 'fitness': -0.03, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1413242, 'bookSize': 20000000, 'longCount': 589, 'shortCount': 592, 'turnover': 0.1262, 'returns': 0.0138, 'drawdown': 0.0807, 'margin': 0.000218, 'fitness': 0.13, 'sharpe': 0.4}, 'riskNeutralized': {'pnl': -484315, 'bookSize': 20000000, 'longCount': 486, 'shortCount': 448, 'turnover': 0.5901, 'returns': -0.0047, 'drawdown': 0.137, 'margin': -1.6e-05, 'fitness': -0.02, 'sharpe': -0.17}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.25}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.03}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5901}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5901}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.13, 'value': -0.35}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.61, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '6XPaPGmJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_scale(vec_avg(rsk60_offer),30),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:38:17-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:38:17-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1672172, 'bookSize': 20000000, 'longCount': 513, 'shortCount': 666, 'turnover': 0.6257, 'returns': 0.0162, 'drawdown': 0.0714, 'margin': 5.2e-05, 'sharpe': 0.52, 'fitness': 0.08, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 335775, 'bookSize': 20000000, 'longCount': 590, 'shortCount': 739, 'turnover': 0.1386, 'returns': 0.0033, 'drawdown': 0.1021, 'margin': 4.7e-05, 'fitness': 0.02, 'sharpe': 0.1}, 'riskNeutralized': {'pnl': 857661, 'bookSize': 20000000, 'longCount': 513, 'shortCount': 666, 'turnover': 0.6257, 'returns': 0.0083, 'drawdown': 0.0974, 'margin': 2.7e-05, 'fitness': 0.04, 'sharpe': 0.31}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.52}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.08}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6257}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6257}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2014-01-06', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.27, 'value': 0.79}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.84, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[SAVED] 7 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 40 to 48 ---

2026-02-07 13:38:28,366 - ace - ERROR - Simulation failed. {'id': 'vKhWdam74FEaximWZRuJDC', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 31, 'end': 66, 'property': 'regular'}}
2026-02-07 13:38:28,914 - ace - ERROR - Simulation failed. {'id': 'nmAIh3nh5fRbPs1frXAmmJ8', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 4, should be exactly 2 input(s)', 'location': {'line': 1, 'start': 22, 'end': 83, 'property': 'regular'}}

{'id': '88kakJqo', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(vec_avg(rsk60_offer),3),15)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-06T23:39:38-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:39:39-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2605438, 'bookSize': 20000000, 'longCount': 471, 'shortCount': 607, 'turnover': 0.7017, 'returns': 0.0253, 'drawdown': 0.0471, 'margin': 7.2e-05, 'sharpe': 0.78, 'fitness': 0.15, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -731134, 'bookSize': 20000000, 'longCount': 592, 'shortCount': 681, 'turnover': 0.1456, 'returns': -0.0071, 'drawdown': 0.1594, 'margin': -9.7e-05, 'fitness': -0.04, 'sharpe': -0.2}, 'riskNeutralized': {'pnl': 1553140, 'bookSize': 20000000, 'longCount': 471, 'shortCount': 607, 'turnover': 0.7017, 'returns': 0.0151, 'drawdown': 0.042, 'margin': 4.3e-05, 'fitness': 0.08, 'sharpe': 0.55}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.78}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.15}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.7017}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.7017}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.41, 'value': 0.98}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.67, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qaqmav', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_backfill(vec_avg(rsk60_crowding),3),ts_backfill(ts_mean(vec_avg(rsk60_crowding),7),3)),15)', 'description': None, 'operatorCount': 7}, 'dateCreated': '2026-02-06T23:39:43-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:39:44-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -512235, 'bookSize': 20000000, 'longCount': 809, 'shortCount': 864, 'turnover': 1.2936, 'returns': -0.0062, 'drawdown': 0.1464, 'margin': -1e-05, 'sharpe': -0.19, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 9850, 'bookSize': 20000000, 'longCount': 857, 'shortCount': 897, 'turnover': 0.2395, 'returns': 0.0001, 'drawdown': 0.1082, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.0}, 'riskNeutralized': {'pnl': -488023, 'bookSize': 20000000, 'longCount': 809, 'shortCount': 864, 'turnover': 1.2936, 'returns': -0.0059, 'drawdown': 0.1133, 'margin': -9e-06, 'fitness': -0.01, 'sharpe': -0.21}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.19}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.2936}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.2936}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-09-07', 'limit': 0.1, 'value': 0.212713}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.1, 'value': -0.38}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.32, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'YPw2wz2A', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(reverse(ts_backfill(ts_rank(vec_avg(rsk60_offer),3),3)),10)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-06T23:39:43-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:39:44-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -667186, 'bookSize': 20000000, 'longCount': 498, 'shortCount': 508, 'turnover': 1.2385, 'returns': -0.0065, 'drawdown': 0.1617, 'margin': -1e-05, 'sharpe': -0.21, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 597687, 'bookSize': 20000000, 'longCount': 582, 'shortCount': 626, 'turnover': 0.2032, 'returns': 0.0058, 'drawdown': 0.1097, 'margin': 5.7e-05, 'fitness': 0.03, 'sharpe': 0.15}, 'riskNeutralized': {'pnl': -326167, 'bookSize': 20000000, 'longCount': 498, 'shortCount': 508, 'turnover': 1.2385, 'returns': -0.0032, 'drawdown': 0.1637, 'margin': -5e-06, 'fitness': -0.01, 'sharpe': -0.11}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.21}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.2385}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.2385}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.11, 'value': -0.28}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.05, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'gJqRqd3l', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_offer),20),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:40:09-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:40:10-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2162821, 'bookSize': 20000000, 'longCount': 801, 'shortCount': 892, 'turnover': 0.5456, 'returns': 0.021, 'drawdown': 0.0349, 'margin': 7.7e-05, 'sharpe': 0.83, 'fitness': 0.16, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 713639, 'bookSize': 20000000, 'longCount': 866, 'shortCount': 913, 'turnover': 0.1538, 'returns': 0.0069, 'drawdown': 0.0735, 'margin': 9e-05, 'fitness': 0.06, 'sharpe': 0.26}, 'riskNeutralized': {'pnl': 1169370, 'bookSize': 20000000, 'longCount': 801, 'shortCount': 892, 'turnover': 0.5456, 'returns': 0.0113, 'drawdown': 0.0579, 'margin': 4.2e-05, 'fitness': 0.08, 'sharpe': 0.55}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.83}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.16}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5456}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5456}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.43, 'value': 1.09}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.41, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVaVPPW', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_ir(vec_avg(rsk60_offer),30),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:40:18-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:40:19-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -861998, 'bookSize': 20000000, 'longCount': 669, 'shortCount': 819, 'turnover': 0.3116, 'returns': -0.0084, 'drawdown': 0.1261, 'margin': -5.4e-05, 'sharpe': -0.35, 'fitness': -0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -619205, 'bookSize': 20000000, 'longCount': 743, 'shortCount': 883, 'turnover': 0.1165, 'returns': -0.006, 'drawdown': 0.12, 'margin': -0.000103, 'fitness': -0.05, 'sharpe': -0.23}, 'riskNeutralized': {'pnl': -433018, 'bookSize': 20000000, 'longCount': 669, 'shortCount': 819, 'turnover': 0.3116, 'returns': -0.0042, 'drawdown': 0.0981, 'margin': -2.7e-05, 'fitness': -0.02, 'sharpe': -0.21}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.35}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3116}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3116}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.18, 'value': 0.01}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.02, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:40:28,519 - ace - WARNING - Simulation 4p7D174Gr4Jwbfv11aBF6r7F failed. {'id': '4p7D174Gr4Jwbfv11aBF6r7F', 'type': 'REGULAR', 'status': 'FAIL'}

[SAVED] 5 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 48 to 56 ---

2026-02-07 13:40:34,778 - ace - ERROR - Simulation failed. {'id': '5DLmD8Bu4mm8OoFqMPyaAE', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'omw3wXW2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'trade_when(ts_backfill(ts_delta(vec_avg(rsk60_last),5),5),ts_zscore(ts_backfill(ts_delta(vec_avg(rsk60_last),5),5),10),NaN)', 'description': None, 'operatorCount': 8}, 'dateCreated': '2026-02-06T23:41:33-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:41:34-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1632920, 'bookSize': 20000000, 'longCount': 999, 'shortCount': 1185, 'turnover': 0.3767, 'returns': 0.0159, 'drawdown': 0.0517, 'margin': 8.4e-05, 'sharpe': 0.68, 'fitness': 0.14, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1523814, 'bookSize': 20000000, 'longCount': 989, 'shortCount': 1200, 'turnover': 0.1246, 'returns': 0.0148, 'drawdown': 0.0653, 'margin': 0.000238, 'fitness': 0.19, 'sharpe': 0.56}, 'riskNeutralized': {'pnl': 645493, 'bookSize': 20000000, 'longCount': 999, 'shortCount': 1185, 'turnover': 0.3767, 'returns': 0.0063, 'drawdown': 0.0394, 'margin': 3.3e-05, 'fitness': 0.05, 'sharpe': 0.39}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.68}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.14}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3767}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3767}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.35, 'value': 0.34}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.62, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '6XPaPQWP', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_arg_max(vec_avg(rsk60_crowding),5),3),10)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:41:42-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:41:43-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 206079, 'bookSize': 20000000, 'longCount': 900, 'shortCount': 593, 'turnover': 1.0107, 'returns': 0.0025, 'drawdown': 0.1371, 'margin': 5e-06, 'sharpe': 0.08, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -353365, 'bookSize': 20000000, 'longCount': 963, 'shortCount': 696, 'turnover': 0.2166, 'returns': -0.0042, 'drawdown': 0.2357, 'margin': -3.9e-05, 'fitness': -0.02, 'sharpe': -0.12}, 'riskNeutralized': {'pnl': 119167, 'bookSize': 20000000, 'longCount': 900, 'shortCount': 593, 'turnover': 1.0107, 'returns': 0.0014, 'drawdown': 0.079, 'margin': 3e-06, 'fitness': 0.0, 'sharpe': 0.05}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.08}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0107}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0107}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.04, 'value': 0.36}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.8, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'ZYw2wv3Z', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(signed_power(ts_backfill(vec_avg(rsk60_offer),5),2),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:41:46-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:41:46-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2504823, 'bookSize': 20000000, 'longCount': 491, 'shortCount': 695, 'turnover': 0.6454, 'returns': 0.0243, 'drawdown': 0.0408, 'margin': 7.5e-05, 'sharpe': 0.74, 'fitness': 0.14, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1085056, 'bookSize': 20000000, 'longCount': 598, 'shortCount': 749, 'turnover': 0.14, 'returns': -0.0105, 'drawdown': 0.1833, 'margin': -0.00015, 'fitness': -0.08, 'sharpe': -0.31}, 'riskNeutralized': {'pnl': 1428918, 'bookSize': 20000000, 'longCount': 491, 'shortCount': 695, 'turnover': 0.6454, 'returns': 0.0139, 'drawdown': 0.0448, 'margin': 4.3e-05, 'fitness': 0.08, 'sharpe': 0.52}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.74}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.14}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6454}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6454}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.38, 'value': 0.94}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.84, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'npkZk5J3', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_datatime),5)),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:41:46-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:41:46-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.55'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -3954076, 'bookSize': 20000000, 'longCount': 1050, 'shortCount': 983, 'turnover': 1.0206, 'returns': -0.0508, 'drawdown': 0.5082, 'margin': -9.9e-05, 'sharpe': -0.54, 'fitness': -0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1955986, 'bookSize': 20000000, 'longCount': 1081, 'shortCount': 1061, 'turnover': 0.2128, 'returns': -0.0251, 'drawdown': 0.4508, 'margin': -0.000236, 'fitness': -0.08, 'sharpe': -0.22}, 'riskNeutralized': {'pnl': -7105233, 'bookSize': 20000000, 'longCount': 1050, 'shortCount': 983, 'turnover': 1.0206, 'returns': -0.0912, 'drawdown': 0.7759, 'margin': -0.000179, 'fitness': -0.2, 'sharpe': -0.67}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.54}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0206}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0206}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2020-01-24', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.28, 'value': -0.2}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.58, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'wpwnwkxQ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_covariance(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_last),5),20),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:41:46-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:41:47-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1491680, 'bookSize': 20000000, 'longCount': 766, 'shortCount': 883, 'turnover': 0.313, 'returns': 0.0145, 'drawdown': 0.0371, 'margin': 9.2e-05, 'sharpe': 0.59, 'fitness': 0.13, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -608722, 'bookSize': 20000000, 'longCount': 828, 'shortCount': 888, 'turnover': 0.1199, 'returns': -0.0059, 'drawdown': 0.0972, 'margin': -9.8e-05, 'fitness': -0.05, 'sharpe': -0.24}, 'riskNeutralized': {'pnl': 365394, 'bookSize': 20000000, 'longCount': 766, 'shortCount': 883, 'turnover': 0.313, 'returns': 0.0035, 'drawdown': 0.0599, 'margin': 2.3e-05, 'fitness': 0.02, 'sharpe': 0.17}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.59}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.13}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.313}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.313}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.31, 'value': 0.45}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.3, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVaV39m', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_max_diff(vec_avg(rsk60_last),10),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:42:09-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:42:10-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 789564, 'bookSize': 20000000, 'longCount': 1086, 'shortCount': 772, 'turnover': 0.6535, 'returns': 0.0077, 'drawdown': 0.0501, 'margin': 2.3e-05, 'sharpe': 0.36, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 8796, 'bookSize': 20000000, 'longCount': 1078, 'shortCount': 847, 'turnover': 0.1805, 'returns': 0.0001, 'drawdown': 0.0925, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.0}, 'riskNeutralized': {'pnl': 519372, 'bookSize': 20000000, 'longCount': 1086, 'shortCount': 772, 'turnover': 0.6535, 'returns': 0.005, 'drawdown': 0.0571, 'margin': 1.5e-05, 'fitness': 0.02, 'sharpe': 0.28}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.36}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6535}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6535}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.19, 'value': -0.03}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.34, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:42:20,915 - ace - ERROR - Simulation failed. {'id': '28kS1863b5gbaV61aFUeQBc', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 31, 'end': 67, 'property': 'regular'}}

{'id': 'vRnenWVa', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(reverse(ts_backfill(ts_rank(vec_avg(rsk60_crowding),20),5)),20)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-06T23:43:25-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:43:25-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 304315, 'bookSize': 20000000, 'longCount': 800, 'shortCount': 755, 'turnover': 1.178, 'returns': 0.0037, 'drawdown': 0.1331, 'margin': 6e-06, 'sharpe': 0.12, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -277711, 'bookSize': 20000000, 'longCount': 840, 'shortCount': 801, 'turnover': 0.2187, 'returns': -0.0033, 'drawdown': 0.1998, 'margin': -3.1e-05, 'fitness': -0.01, 'sharpe': -0.09}, 'riskNeutralized': {'pnl': 200282, 'bookSize': 20000000, 'longCount': 800, 'shortCount': 755, 'turnover': 1.178, 'returns': 0.0024, 'drawdown': 0.0895, 'margin': 4e-06, 'fitness': 0.0, 'sharpe': 0.09}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.12}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.178}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.178}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.06, 'value': 0.26}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.35, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVaVrQJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_backfill(vec_avg(rsk60_last),5),ts_backfill(vec_avg(rsk60_offer),5)),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:43:24-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:43:25-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 779634, 'bookSize': 20000000, 'longCount': 760, 'shortCount': 1024, 'turnover': 1.0611, 'returns': 0.0076, 'drawdown': 0.058, 'margin': 1.4e-05, 'sharpe': 0.28, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 151971, 'bookSize': 20000000, 'longCount': 830, 'shortCount': 1041, 'turnover': 0.2147, 'returns': 0.0015, 'drawdown': 0.1567, 'margin': 1.4e-05, 'fitness': 0.0, 'sharpe': 0.05}, 'riskNeutralized': {'pnl': 645779, 'bookSize': 20000000, 'longCount': 760, 'shortCount': 1024, 'turnover': 1.0611, 'returns': 0.0063, 'drawdown': 0.0533, 'margin': 1.2e-05, 'fitness': 0.02, 'sharpe': 0.28}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.28}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0611}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0611}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.15, 'value': 0.19}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.45, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '9qPaPNgx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(ts_backfill(vec_avg(rsk60_offer),5))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-06T23:43:26-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:43:26-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -11906636, 'bookSize': 20000000, 'longCount': 451, 'shortCount': 1680, 'turnover': 0.0952, 'returns': -0.1154, 'drawdown': 1.2435, 'margin': -0.002424, 'sharpe': -1.54, 'fitness': -1.48, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -10774281, 'bookSize': 20000000, 'longCount': 538, 'shortCount': 1624, 'turnover': 0.0404, 'returns': -0.1044, 'drawdown': 1.1146, 'margin': -0.005173, 'fitness': -1.4, 'sharpe': -1.53}, 'riskNeutralized': {'pnl': -5340218, 'bookSize': 20000000, 'longCount': 451, 'shortCount': 1680, 'turnover': 0.0952, 'returns': -0.0518, 'drawdown': 0.5592, 'margin': -0.001087, 'fitness': -0.71, 'sharpe': -1.1}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.54}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -1.48}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0952}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0952}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.8, 'value': -1.13}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -2.38, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'kqk1kzl6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(sign(ts_backfill(ts_delta(vec_avg(rsk60_crowding),3),3)),ts_backfill(ts_delta(vec_avg(rsk60_crowding),3),3)),10)', 'description': None, 'operatorCount': 9}, 'dateCreated': '2026-02-06T23:43:25-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:43:25-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.59'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -345151, 'bookSize': 20000000, 'longCount': 633, 'shortCount': 975, 'turnover': 1.174, 'returns': -0.0042, 'drawdown': 0.0787, 'margin': -7e-06, 'sharpe': -0.13, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1227779, 'bookSize': 20000000, 'longCount': 707, 'shortCount': 1019, 'turnover': 0.2171, 'returns': 0.0148, 'drawdown': 0.1016, 'margin': 0.000136, 'fitness': 0.12, 'sharpe': 0.45}, 'riskNeutralized': {'pnl': -627343, 'bookSize': 20000000, 'longCount': 633, 'shortCount': 975, 'turnover': 1.174, 'returns': -0.0075, 'drawdown': 0.0952, 'margin': -1.3e-05, 'fitness': -0.02, 'sharpe': -0.28}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.13}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.174}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.174}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-09-12', 'limit': 0.1, 'value': 0.166667}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.07, 'value': -0.32}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.69, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZ2ZGb1', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(divide(ts_backfill(vec_avg(rsk60_crowding),5),ts_backfill(vec_avg(rsk60_offer),5)),20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:43:34-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:43:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -483126, 'bookSize': 20000000, 'longCount': 786, 'shortCount': 899, 'turnover': 1.3957, 'returns': -0.0058, 'drawdown': 0.1799, 'margin': -8e-06, 'sharpe': -0.16, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -196486, 'bookSize': 20000000, 'longCount': 852, 'shortCount': 917, 'turnover': 0.2336, 'returns': -0.0024, 'drawdown': 0.1858, 'margin': -2e-05, 'fitness': -0.01, 'sharpe': -0.06}, 'riskNeutralized': {'pnl': -175345, 'bookSize': 20000000, 'longCount': 786, 'shortCount': 899, 'turnover': 1.3957, 'returns': -0.0021, 'drawdown': 0.1122, 'margin': -3e-06, 'fitness': -0.0, 'sharpe': -0.07}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.16}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3957}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3957}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.08, 'value': -0.45}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.33, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '3qYa3MQZ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_arg_min(vec_avg(rsk60_last),7),5),10)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:43:46-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:43:47-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -716037, 'bookSize': 20000000, 'longCount': 1048, 'shortCount': 709, 'turnover': 0.8681, 'returns': -0.0069, 'drawdown': 0.0767, 'margin': -1.6e-05, 'sharpe': -0.3, 'fitness': -0.03, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -4814, 'bookSize': 20000000, 'longCount': 1088, 'shortCount': 808, 'turnover': 0.2209, 'returns': -0.0, 'drawdown': 0.0703, 'margin': -0.0, 'fitness': -0.0, 'sharpe': -0.0}, 'riskNeutralized': {'pnl': 381237, 'bookSize': 20000000, 'longCount': 1048, 'shortCount': 709, 'turnover': 0.8681, 'returns': 0.0037, 'drawdown': 0.0386, 'margin': 9e-06, 'fitness': 0.01, 'sharpe': 0.18}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.3}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.03}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.8681}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.8681}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.16, 'value': 0.18}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.58, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:48:00,021 - ace - WARNING - Simulation 3JsNfn12S4RyaSj1gFUKL59Y failed. {'id': '3JsNfn12S4RyaSj1gFUKL59Y', 'type': 'REGULAR', 'status': 'FAIL'}

[SAVED] 7 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 80 to 88 ---

2026-02-07 13:48:06,459 - ace - ERROR - Simulation failed. {'id': '4CadMF3B24jo9sd99Zvj1hY', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 22, 'end': 62, 'property': 'regular'}}

{'id': 'WjwannlQ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(ts_backfill(vec_avg(rsk60_offer),5),quantile(ts_backfill(vec_avg(rsk60_crowding),5))),20)', 'description': None, 'operatorCount': 7}, 'dateCreated': '2026-02-06T23:49:10-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:11-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -748354, 'bookSize': 20000000, 'longCount': 1068, 'shortCount': 1122, 'turnover': 1.3226, 'returns': -0.009, 'drawdown': 0.1846, 'margin': -1.4e-05, 'sharpe': -0.29, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1119125, 'bookSize': 20000000, 'longCount': 1087, 'shortCount': 1139, 'turnover': 0.274, 'returns': -0.0134, 'drawdown': 0.2042, 'margin': -9.8e-05, 'fitness': -0.1, 'sharpe': -0.43}, 'riskNeutralized': {'pnl': 47267, 'bookSize': 20000000, 'longCount': 1068, 'shortCount': 1122, 'turnover': 1.3226, 'returns': 0.0006, 'drawdown': 0.0942, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.02}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.29}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3226}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3226}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.15, 'value': -0.48}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.37, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qa00v2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'scale(ts_backfill(vec_avg(rsk60_offer),5))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-06T23:49:13-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:14-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -11906635, 'bookSize': 20000000, 'longCount': 451, 'shortCount': 1680, 'turnover': 0.0952, 'returns': -0.1154, 'drawdown': 1.2435, 'margin': -0.002424, 'sharpe': -1.54, 'fitness': -1.48, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -10774283, 'bookSize': 20000000, 'longCount': 538, 'shortCount': 1624, 'turnover': 0.0404, 'returns': -0.1044, 'drawdown': 1.1146, 'margin': -0.005173, 'fitness': -1.4, 'sharpe': -1.53}, 'riskNeutralized': {'pnl': -5340219, 'bookSize': 20000000, 'longCount': 451, 'shortCount': 1680, 'turnover': 0.0952, 'returns': -0.0518, 'drawdown': 0.5592, 'margin': -0.001087, 'fitness': -0.71, 'sharpe': -1.1}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.54}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -1.48}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0952}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0952}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.8, 'value': -1.13}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -2.38, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Jj0gYYWO', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(sign(ts_backfill(days_from_last_change(vec_avg(rsk60_crowding)),3)),10)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-06T23:49:13-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:13-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1412806, 'bookSize': 20000000, 'longCount': 629, 'shortCount': 651, 'turnover': 0.9909, 'returns': -0.017, 'drawdown': 0.2124, 'margin': -3.4e-05, 'sharpe': -0.52, 'fitness': -0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -891592, 'bookSize': 20000000, 'longCount': 769, 'shortCount': 781, 'turnover': 0.197, 'returns': -0.0107, 'drawdown': 0.2108, 'margin': -0.000109, 'fitness': -0.06, 'sharpe': -0.27}, 'riskNeutralized': {'pnl': -1565190, 'bookSize': 20000000, 'longCount': 629, 'shortCount': 651, 'turnover': 0.9909, 'returns': -0.0188, 'drawdown': 0.1793, 'margin': -3.8e-05, 'fitness': -0.08, 'sharpe': -0.59}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.52}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9909}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9909}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2015-12-01', 'limit': 0.1, 'value': 0.200155}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.27, 'value': -0.12}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.7, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'e78dggvN', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_product(vec_avg(rsk60_last),3),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:49:14-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:15-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.57'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1193490, 'bookSize': 20000000, 'longCount': 734, 'shortCount': 1193, 'turnover': 0.5177, 'returns': 0.0116, 'drawdown': 0.051, 'margin': 4.5e-05, 'sharpe': 0.42, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1497314, 'bookSize': 20000000, 'longCount': 833, 'shortCount': 1183, 'turnover': 0.1648, 'returns': -0.0145, 'drawdown': 0.2211, 'margin': -0.000176, 'fitness': -0.15, 'sharpe': -0.5}, 'riskNeutralized': {'pnl': 989942, 'bookSize': 20000000, 'longCount': 734, 'shortCount': 1193, 'turnover': 0.5177, 'returns': 0.0096, 'drawdown': 0.0392, 'margin': 3.7e-05, 'fitness': 0.07, 'sharpe': 0.49}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.42}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5177}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5177}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.22, 'value': 0.66}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.16, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'QPr2qqzX', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_backfill(ts_mean(vec_avg(rsk60_last),5),3),ts_backfill(ts_mean(vec_avg(rsk60_last),30),3)),20)', 'description': None, 'operatorCount': 8}, 'dateCreated': '2026-02-06T23:49:13-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:14-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1959744, 'bookSize': 20000000, 'longCount': 915, 'shortCount': 1007, 'turnover': 0.3647, 'returns': 0.019, 'drawdown': 0.038, 'margin': 0.000104, 'sharpe': 0.87, 'fitness': 0.2, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1092910, 'bookSize': 20000000, 'longCount': 947, 'shortCount': 1024, 'turnover': 0.1469, 'returns': 0.0106, 'drawdown': 0.0515, 'margin': 0.000145, 'fitness': 0.13, 'sharpe': 0.48}, 'riskNeutralized': {'pnl': 1044028, 'bookSize': 20000000, 'longCount': 915, 'shortCount': 1007, 'turnover': 0.3647, 'returns': 0.0101, 'drawdown': 0.0339, 'margin': 5.6e-05, 'fitness': 0.1, 'sharpe': 0.58}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.87}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.2}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3647}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3647}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.45, 'value': 1.04}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.4, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '9qPabbk9', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(last_diff_value(vec_avg(rsk60_last),10),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:49:15-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:15-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 799397, 'bookSize': 20000000, 'longCount': 773, 'shortCount': 977, 'turnover': 0.804, 'returns': 0.0078, 'drawdown': 0.0618, 'margin': 1.9e-05, 'sharpe': 0.33, 'fitness': 0.03, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -437429, 'bookSize': 20000000, 'longCount': 840, 'shortCount': 1001, 'turnover': 0.1878, 'returns': -0.0042, 'drawdown': 0.1027, 'margin': -4.5e-05, 'fitness': -0.03, 'sharpe': -0.17}, 'riskNeutralized': {'pnl': 56319, 'bookSize': 20000000, 'longCount': 773, 'shortCount': 977, 'turnover': 0.804, 'returns': 0.0005, 'drawdown': 0.1118, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.03}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.33}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.03}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.804}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.804}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.17, 'value': 0.62}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.92, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:50:39,205 - ace - WARNING - Simulation 3oZ23ld0l4B8aYzBBhxYtgW failed. {'id': '3oZ23ld0l4B8aYzBBhxYtgW', 'type': 'REGULAR', 'status': 'FAIL'}

{'id': 'npkZYOGz', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(quantile(ts_backfill(vec_avg(rsk60_offer),5)),ts_zscore(ts_backfill(vec_avg(rsk60_crowding),5),10)),20)', 'description': None, 'operatorCount': 8}, 'dateCreated': '2026-02-06T23:50:38-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:50:39-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1365727, 'bookSize': 20000000, 'longCount': 681, 'shortCount': 765, 'turnover': 1.2755, 'returns': 0.0164, 'drawdown': 0.0928, 'margin': 2.6e-05, 'sharpe': 0.47, 'fitness': 0.05, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1336682, 'bookSize': 20000000, 'longCount': 743, 'shortCount': 830, 'turnover': 0.2171, 'returns': 0.0161, 'drawdown': 0.1012, 'margin': 0.000148, 'fitness': 0.11, 'sharpe': 0.4}, 'riskNeutralized': {'pnl': 681221, 'bookSize': 20000000, 'longCount': 681, 'shortCount': 765, 'turnover': 1.2755, 'returns': 0.0082, 'drawdown': 0.0941, 'margin': 1.3e-05, 'fitness': 0.02, 'sharpe': 0.26}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.47}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.05}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.2755}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.2755}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.24, 'value': 0.33}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.45, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'ZYw2qWJ3', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(quantile(ts_backfill(vec_avg(rsk60_last),5)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:50:39-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:50:40-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 4673849, 'bookSize': 20000000, 'longCount': 1079, 'shortCount': 1038, 'turnover': 0.2619, 'returns': 0.0453, 'drawdown': 0.0982, 'margin': 0.000346, 'sharpe': 0.95, 'fitness': 0.4, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4872299, 'bookSize': 20000000, 'longCount': 1086, 'shortCount': 1063, 'turnover': 0.0852, 'returns': 0.0472, 'drawdown': 0.1023, 'margin': 0.001108, 'fitness': 0.58, 'sharpe': 0.95}, 'riskNeutralized': {'pnl': 1223178, 'bookSize': 20000000, 'longCount': 1079, 'shortCount': 1038, 'turnover': 0.2619, 'returns': 0.0119, 'drawdown': 0.0553, 'margin': 9.1e-05, 'fitness': 0.15, 'sharpe': 0.69}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.95}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.4}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2619}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2619}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.49, 'value': 0.48}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.96, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'QPr2qqzX', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_backfill(ts_mean(vec_avg(rsk60_last),5),3),ts_backfill(ts_mean(vec_avg(rsk60_last),30),3)),20)', 'description': 'rsk60_last vec_avg + ts_backfill; subtract ts_mean(5) - ts_mean(30) then ts_zscore. SUGGESTION2 applied. Classic crossover adapted to borrow rates. Confidence: 0.65', 'operatorCount': 8}, 'dateCreated': '2026-02-06T23:49:13-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:49:20-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1959744, 'bookSize': 20000000, 'longCount': 915, 'shortCount': 1007, 'turnover': 0.3647, 'returns': 0.019, 'drawdown': 0.038, 'margin': 0.000104, 'sharpe': 0.87, 'fitness': 0.2, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1092910, 'bookSize': 20000000, 'longCount': 947, 'shortCount': 1024, 'turnover': 0.1469, 'returns': 0.0106, 'drawdown': 0.0515, 'margin': 0.000145, 'fitness': 0.13, 'sharpe': 0.48}, 'riskNeutralized': {'pnl': 1044028, 'bookSize': 20000000, 'longCount': 915, 'shortCount': 1007, 'turnover': 0.3647, 'returns': 0.0101, 'drawdown': 0.0339, 'margin': 5.6e-05, 'fitness': 0.1, 'sharpe': 0.58}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.87}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.2}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3647}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3647}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.45, 'value': 1.04}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.4, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'pwJVo193', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(vec_avg(rsk60_offer),3),5)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-06T23:50:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:50:41-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2434629, 'bookSize': 20000000, 'longCount': 320, 'shortCount': 355, 'turnover': 1.0595, 'returns': 0.0236, 'drawdown': 0.0558, 'margin': 4.5e-05, 'sharpe': 0.65, 'fitness': 0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -919667, 'bookSize': 20000000, 'longCount': 497, 'shortCount': 500, 'turnover': 0.1696, 'returns': -0.0089, 'drawdown': 0.1481, 'margin': -0.000105, 'fitness': -0.05, 'sharpe': -0.2}, 'riskNeutralized': {'pnl': 1914317, 'bookSize': 20000000, 'longCount': 320, 'shortCount': 355, 'turnover': 1.0595, 'returns': 0.0186, 'drawdown': 0.0699, 'margin': 3.5e-05, 'fitness': 0.07, 'sharpe': 0.56}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.65}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0595}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0595}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.34, 'value': 0.74}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.9, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Wjwanajx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(divide(ts_backfill(vec_avg(rsk60_offer),5),add(1,abs(ts_backfill(vec_avg(rsk60_crowding),5)))),20)', 'description': None, 'operatorCount': 8}, 'dateCreated': '2026-02-06T23:50:42-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:50:43-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 116062, 'bookSize': 20000000, 'longCount': 838, 'shortCount': 724, 'turnover': 0.9464, 'returns': 0.0014, 'drawdown': 0.1034, 'margin': 3e-06, 'sharpe': 0.05, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -699660, 'bookSize': 20000000, 'longCount': 892, 'shortCount': 800, 'turnover': 0.1979, 'returns': -0.0084, 'drawdown': 0.1682, 'margin': -8.5e-05, 'fitness': -0.06, 'sharpe': -0.27}, 'riskNeutralized': {'pnl': 311494, 'bookSize': 20000000, 'longCount': 838, 'shortCount': 724, 'turnover': 0.9464, 'returns': 0.0037, 'drawdown': 0.0726, 'margin': 8e-06, 'fitness': 0.01, 'sharpe': 0.16}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.05}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9464}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9464}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.03, 'value': 0.46}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.27, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'ak2AMAZ1', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_decay_linear(vec_avg(rsk60_offer),15),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:50:44-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:50:44-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2345019, 'bookSize': 20000000, 'longCount': 582, 'shortCount': 712, 'turnover': 0.2804, 'returns': 0.0227, 'drawdown': 0.0396, 'margin': 0.000162, 'sharpe': 0.84, 'fitness': 0.24, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -408300, 'bookSize': 20000000, 'longCount': 680, 'shortCount': 749, 'turnover': 0.1063, 'returns': -0.004, 'drawdown': 0.1547, 'margin': -7.5e-05, 'fitness': -0.03, 'sharpe': -0.14}, 'riskNeutralized': {'pnl': 1457478, 'bookSize': 20000000, 'longCount': 582, 'shortCount': 712, 'turnover': 0.2804, 'returns': 0.0141, 'drawdown': 0.0604, 'margin': 0.000101, 'fitness': 0.14, 'sharpe': 0.63}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.84}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.24}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2804}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2804}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.44, 'value': 1.1}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.07, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 13:50:56,798 - ace - ERROR - Simulation failed. {'id': '3Dh9gUl54Oq8XiabiVRiAx', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 29, 'end': 64, 'property': 'regular'}}
2026-02-07 13:50:57,336 - ace - ERROR - Simulation failed. {'id': '1FSKQCeqh4xWcGkcwro6xpq', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 30, 'end': 66, 'property': 'regular'}}
2026-02-07 13:50:57,412 - ace - ERROR - Simulation failed. {'id': '4gUMJUeAM4Pw8Yrrxr7ETWI', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 31, 'end': 66, 'property': 'regular'}}

{'id': 'N1WgqOoe', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_crowding),14),5),20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:52:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:52:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -185354, 'bookSize': 20000000, 'longCount': 793, 'shortCount': 924, 'turnover': 1.1831, 'returns': -0.0022, 'drawdown': 0.1277, 'margin': -4e-06, 'sharpe': -0.07, 'fitness': -0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 6946, 'bookSize': 20000000, 'longCount': 841, 'shortCount': 950, 'turnover': 0.2195, 'returns': 0.0001, 'drawdown': 0.1376, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.0}, 'riskNeutralized': {'pnl': -234996, 'bookSize': 20000000, 'longCount': 793, 'shortCount': 924, 'turnover': 1.1831, 'returns': -0.0028, 'drawdown': 0.1009, 'margin': -5e-06, 'fitness': -0.0, 'sharpe': -0.1}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.07}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.1831}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.1831}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.04, 'value': -0.26}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.41, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E50gYKA1', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(ts_backfill(ts_ir(vec_avg(rsk60_offer),10),5))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:52:02-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:52:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1144788, 'bookSize': 20000000, 'longCount': 886, 'shortCount': 941, 'turnover': 0.1155, 'returns': 0.0111, 'drawdown': 0.0739, 'margin': 0.000192, 'sharpe': 0.34, 'fitness': 0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 868739, 'bookSize': 20000000, 'longCount': 914, 'shortCount': 1074, 'turnover': 0.06, 'returns': 0.0084, 'drawdown': 0.0913, 'margin': 0.000281, 'fitness': 0.06, 'sharpe': 0.24}, 'riskNeutralized': {'pnl': 488889, 'bookSize': 20000000, 'longCount': 886, 'shortCount': 941, 'turnover': 0.1155, 'returns': 0.0047, 'drawdown': 0.0347, 'margin': 8.2e-05, 'fitness': 0.05, 'sharpe': 0.24}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.34}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1155}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1155}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2014-01-06', 'limit': 0.1, 'value': 0.499788}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.18, 'value': -0.09}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.46, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '3qYa3AW6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_arg_max(vec_avg(rsk60_offer),3),3),10)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:52:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:52:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1647992, 'bookSize': 20000000, 'longCount': 839, 'shortCount': 376, 'turnover': 1.1492, 'returns': -0.016, 'drawdown': 0.1697, 'margin': -2.8e-05, 'sharpe': -0.49, 'fitness': -0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 574496, 'bookSize': 20000000, 'longCount': 885, 'shortCount': 624, 'turnover': 0.2117, 'returns': 0.0056, 'drawdown': 0.1083, 'margin': 5.3e-05, 'fitness': 0.02, 'sharpe': 0.14}, 'riskNeutralized': {'pnl': -455718, 'bookSize': 20000000, 'longCount': 839, 'shortCount': 376, 'turnover': 1.1492, 'returns': -0.0044, 'drawdown': 0.0891, 'margin': -8e-06, 'fitness': -0.01, 'sharpe': -0.15}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.49}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.1492}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.1492}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.25, 'value': -0.5}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.59, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'ZYw2qoLx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_av_diff(vec_avg(rsk60_crowding),3),3),10)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:52:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:52:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 84122, 'bookSize': 20000000, 'longCount': 836, 'shortCount': 851, 'turnover': 1.4306, 'returns': 0.001, 'drawdown': 0.1401, 'margin': 1e-06, 'sharpe': 0.03, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -817873, 'bookSize': 20000000, 'longCount': 892, 'shortCount': 894, 'turnover': 0.2675, 'returns': -0.0098, 'drawdown': 0.1416, 'margin': -7.3e-05, 'fitness': -0.05, 'sharpe': -0.26}, 'riskNeutralized': {'pnl': -299577, 'bookSize': 20000000, 'longCount': 836, 'shortCount': 851, 'turnover': 1.4306, 'returns': -0.0036, 'drawdown': 0.1031, 'margin': -5e-06, 'fitness': -0.01, 'sharpe': -0.13}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.03}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.4306}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.4306}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-09-07', 'limit': 0.1, 'value': 0.166667}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.02, 'value': -0.3}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.72, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'wpwnOeJY', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'hump(ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),20),hump=0.01)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:52:07-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:52:08-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1589406, 'bookSize': 20000000, 'longCount': 709, 'shortCount': 472, 'turnover': 0.0896, 'returns': 0.0154, 'drawdown': 0.0603, 'margin': 0.000344, 'sharpe': 0.54, 'fitness': 0.19, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 270688, 'bookSize': 20000000, 'longCount': 838, 'shortCount': 551, 'turnover': 0.0485, 'returns': 0.0026, 'drawdown': 0.0965, 'margin': 0.000108, 'fitness': 0.01, 'sharpe': 0.09}, 'riskNeutralized': {'pnl': 842448, 'bookSize': 20000000, 'longCount': 709, 'shortCount': 472, 'turnover': 0.0896, 'returns': 0.0082, 'drawdown': 0.0589, 'margin': 0.000182, 'fitness': 0.09, 'sharpe': 0.37}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.54}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.19}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0896}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0896}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.28, 'value': 0.42}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.36, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[SAVED] 5 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 104 to 112 ---

2026-02-07 13:52:20,262 - ace - ERROR - Simulation failed. {'id': '3i2LBX7M057h9rC16GwWxQZ4', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Required attribute "k" must have a value', 'location': {'line': 1, 'start': 22, 'end': 59, 'property': 'regular'}}
2026-02-07 13:52:20,769 - ace - ERROR - Simulation failed. {'id': '2qZjgy6hd50ocMdBAiJKc85', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'RRZ2Z5j0', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(ts_backfill(vec_avg(rsk60_offer),5),ts_backfill(vec_avg(rsk60_crowding),5)),20)', 'description': 'rsk60_offer & rsk60_crowding combined. vec_avg + ts_backfill then multiply and ts_zscore. SUGGESTION1 used. Confidence: 0.73', 'operatorCount': 6}, 'dateCreated': '2026-02-06T23:38:16-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:38:19-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -899263, 'bookSize': 20000000, 'longCount': 742, 'shortCount': 966, 'turnover': 1.3773, 'returns': -0.0108, 'drawdown': 0.1931, 'margin': -1.6e-05, 'sharpe': -0.28, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -263882, 'bookSize': 20000000, 'longCount': 810, 'shortCount': 979, 'turnover': 0.233, 'returns': -0.0032, 'drawdown': 0.2116, 'margin': -2.7e-05, 'fitness': -0.01, 'sharpe': -0.07}, 'riskNeutralized': {'pnl': -247498, 'bookSize': 20000000, 'longCount': 742, 'shortCount': 966, 'turnover': 1.3773, 'returns': -0.003, 'drawdown': 0.1095, 'margin': -4e-06, 'fitness': -0.0, 'sharpe': -0.09}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.28}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3773}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3773}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.15, 'value': -0.57}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.0, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'zqwPQRjo', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(ts_mean(vec_avg(rsk60_crowding),5),3),10)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-06T23:53:27-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:53:27-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -888931, 'bookSize': 20000000, 'longCount': 801, 'shortCount': 849, 'turnover': 0.6941, 'returns': -0.0107, 'drawdown': 0.1371, 'margin': -3.1e-05, 'sharpe': -0.38, 'fitness': -0.05, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1183754, 'bookSize': 20000000, 'longCount': 861, 'shortCount': 886, 'turnover': 0.1809, 'returns': 0.0142, 'drawdown': 0.051, 'margin': 0.000157, 'fitness': 0.13, 'sharpe': 0.48}, 'riskNeutralized': {'pnl': -459008, 'bookSize': 20000000, 'longCount': 801, 'shortCount': 849, 'turnover': 0.6941, 'returns': -0.0055, 'drawdown': 0.0746, 'margin': -1.6e-05, 'fitness': -0.02, 'sharpe': -0.23}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.38}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.05}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6941}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6941}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.2, 'value': -0.45}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.54, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'gJqRwQV0', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(vec_avg(rsk60_last),3),3)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-06T23:55:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:55:01-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1046036, 'bookSize': 20000000, 'longCount': 583, 'shortCount': 648, 'turnover': 1.3465, 'returns': 0.0101, 'drawdown': 0.0815, 'margin': 1.5e-05, 'sharpe': 0.41, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 597616, 'bookSize': 20000000, 'longCount': 766, 'shortCount': 762, 'turnover': 0.2645, 'returns': 0.0058, 'drawdown': 0.131, 'margin': 4.4e-05, 'fitness': 0.03, 'sharpe': 0.19}, 'riskNeutralized': {'pnl': 911341, 'bookSize': 20000000, 'longCount': 583, 'shortCount': 648, 'turnover': 1.3465, 'returns': 0.0088, 'drawdown': 0.0969, 'margin': 1.3e-05, 'fitness': 0.03, 'sharpe': 0.38}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.41}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3465}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3465}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.21, 'value': 0.22}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.26, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'omw3A602', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),10),sign(ts_backfill(ts_delta(vec_avg(rsk60_crowding),3),3))),20)', 'description': None, 'operatorCount': 9}, 'dateCreated': '2026-02-06T23:55:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:55:00-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -528634, 'bookSize': 20000000, 'longCount': 365, 'shortCount': 450, 'turnover': 1.3362, 'returns': -0.0064, 'drawdown': 0.1451, 'margin': -1e-05, 'sharpe': -0.16, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 271551, 'bookSize': 20000000, 'longCount': 498, 'shortCount': 534, 'turnover': 0.1727, 'returns': 0.0033, 'drawdown': 0.1386, 'margin': 3.8e-05, 'fitness': 0.01, 'sharpe': 0.08}, 'riskNeutralized': {'pnl': -486668, 'bookSize': 20000000, 'longCount': 365, 'shortCount': 450, 'turnover': 1.3362, 'returns': -0.0059, 'drawdown': 0.1531, 'margin': -9e-06, 'fitness': -0.01, 'sharpe': -0.17}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.16}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3362}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3362}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-09-12', 'limit': 0.1, 'value': 0.166667}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.08, 'value': -0.36}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.33, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'O0wbqNYR', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(multiply(ts_backfill(ts_rank(vec_avg(rsk60_last),10),3),ts_zscore(ts_backfill(vec_avg(rsk60_offer),5),10)),20)', 'description': None, 'operatorCount': 8}, 'dateCreated': '2026-02-06T23:55:05-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-06T23:55:06-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 674694, 'bookSize': 20000000, 'longCount': 369, 'shortCount': 545, 'turnover': 0.934, 'returns': 0.0065, 'drawdown': 0.1248, 'margin': 1.4e-05, 'sharpe': 0.18, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1738562, 'bookSize': 20000000, 'longCount': 487, 'shortCount': 665, 'turnover': 0.1562, 'returns': -0.0169, 'drawdown': 0.2641, 'margin': -0.000216, 'fitness': -0.14, 'sharpe': -0.43}, 'riskNeutralized': {'pnl': 413003, 'bookSize': 20000000, 'longCount': 369, 'shortCount': 545, 'turnover': 0.934, 'returns': 0.004, 'drawdown': 0.1012, 'margin': 9e-06, 'fitness': 0.01, 'sharpe': 0.13}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.18}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.934}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.934}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.09, 'value': 0.09}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.27, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 14:00:42,662 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429
2026-02-07 14:00:42,671 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429
2026-02-07 14:00:46,166 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': 'vRnexQ0A', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_av_diff(vec_avg(rsk60_offer), 20), 20)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:01:51-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:01:52-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2336740, 'bookSize': 20000000, 'longCount': 773, 'shortCount': 860, 'turnover': 0.5859, 'returns': 0.0227, 'drawdown': 0.0329, 'margin': 7.7e-05, 'sharpe': 0.9, 'fitness': 0.18, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 653551, 'bookSize': 20000000, 'longCount': 861, 'shortCount': 905, 'turnover': 0.1649, 'returns': 0.0063, 'drawdown': 0.0721, 'margin': 7.7e-05, 'fitness': 0.04, 'sharpe': 0.23}, 'riskNeutralized': {'pnl': 1215146, 'bookSize': 20000000, 'longCount': 773, 'shortCount': 860, 'turnover': 0.5859, 'returns': 0.0118, 'drawdown': 0.0598, 'margin': 4e-05, 'fitness': 0.08, 'sharpe': 0.58}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.9}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.18}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5859}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5859}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.47, 'value': 1.12}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.58, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'LLbgqQl6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_range(rsk60_crowding), 15)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:01:55-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:01:55-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6402347, 'bookSize': 20000000, 'longCount': 73, 'shortCount': 98, 'turnover': 1.189, 'returns': 0.077, 'drawdown': 0.5396, 'margin': 0.00013, 'sharpe': 0.41, 'fitness': 0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 10864157, 'bookSize': 20000000, 'longCount': 111, 'shortCount': 131, 'turnover': 0.1602, 'returns': 0.1306, 'drawdown': 0.3913, 'margin': 0.001631, 'fitness': 0.4, 'sharpe': 0.44}, 'riskNeutralized': {'pnl': 2583693, 'bookSize': 20000000, 'longCount': 73, 'shortCount': 98, 'turnover': 1.189, 'returns': 0.0311, 'drawdown': 0.5422, 'margin': 5.2e-05, 'fitness': 0.03, 'sharpe': 0.2}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.41}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.189}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.189}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-07-11', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.21, 'value': 0.29}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.83, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'O0wbq3ld', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_avg(rsk60_last), 10)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:02:12-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:02:12-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1770112, 'bookSize': 20000000, 'longCount': 663, 'shortCount': 891, 'turnover': 1.0357, 'returns': 0.0172, 'drawdown': 0.0441, 'margin': 3.3e-05, 'sharpe': 0.7, 'fitness': 0.09, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 71874, 'bookSize': 20000000, 'longCount': 780, 'shortCount': 960, 'turnover': 0.2252, 'returns': 0.0007, 'drawdown': 0.1446, 'margin': 6e-06, 'fitness': 0.0, 'sharpe': 0.02}, 'riskNeutralized': {'pnl': 1403664, 'bookSize': 20000000, 'longCount': 663, 'shortCount': 891, 'turnover': 1.0357, 'returns': 0.0136, 'drawdown': 0.0366, 'margin': 2.6e-05, 'fitness': 0.08, 'sharpe': 0.67}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.7}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.09}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0357}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0357}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.36, 'value': 0.72}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.17, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Gr0MYRZ0', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_corr(vec_avg(rsk60_offer), vec_avg(rsk60_crowding), 30), 30)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-07T00:02:11-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:02:12-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -376724, 'bookSize': 20000000, 'longCount': 565, 'shortCount': 594, 'turnover': 0.4053, 'returns': -0.0045, 'drawdown': 0.0873, 'margin': -2.2e-05, 'sharpe': -0.15, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1581056, 'bookSize': 20000000, 'longCount': 632, 'shortCount': 666, 'turnover': 0.1099, 'returns': -0.019, 'drawdown': 0.1968, 'margin': -0.000346, 'fitness': -0.24, 'sharpe': -0.62}, 'riskNeutralized': {'pnl': -739095, 'bookSize': 20000000, 'longCount': 565, 'shortCount': 594, 'turnover': 0.4053, 'returns': -0.0089, 'drawdown': 0.1086, 'margin': -4.4e-05, 'fitness': -0.05, 'sharpe': -0.33}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.15}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4053}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4053}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.08, 'value': -0.61}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.22, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qa0ee2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_stddev(rsk60_last), 20)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:02:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:02:41-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5723465, 'bookSize': 20000000, 'longCount': 107, 'shortCount': 151, 'turnover': 1.0169, 'returns': 0.0555, 'drawdown': 0.3726, 'margin': 0.000109, 'sharpe': 0.32, 'fitness': 0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -3886508, 'bookSize': 20000000, 'longCount': 158, 'shortCount': 204, 'turnover': 0.1556, 'returns': -0.0377, 'drawdown': 1.076, 'margin': -0.000485, 'fitness': -0.08, 'sharpe': -0.17}, 'riskNeutralized': {'pnl': 4758925, 'bookSize': 20000000, 'longCount': 107, 'shortCount': 151, 'turnover': 1.0169, 'returns': 0.0461, 'drawdown': 0.3016, 'margin': 9.1e-05, 'fitness': 0.07, 'sharpe': 0.31}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.32}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0169}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0169}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2015-09-28', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.17, 'value': 0.16}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.4, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[SAVED] 5 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 16 to 24 ---

2026-02-07 14:02:42,846 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429
2026-02-07 14:02:42,866 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429
2026-02-07 14:02:42,876 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': 'Xgw2Lmd1', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_sum(rsk60_last), 20)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:03:54-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:03:55-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2238070, 'bookSize': 20000000, 'longCount': 717, 'shortCount': 1076, 'turnover': 0.9754, 'returns': 0.0217, 'drawdown': 0.0363, 'margin': 4.5e-05, 'sharpe': 0.8, 'fitness': 0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 153691, 'bookSize': 20000000, 'longCount': 819, 'shortCount': 1102, 'turnover': 0.2123, 'returns': 0.0015, 'drawdown': 0.155, 'margin': 1.4e-05, 'fitness': 0.0, 'sharpe': 0.04}, 'riskNeutralized': {'pnl': 1176434, 'bookSize': 20000000, 'longCount': 717, 'shortCount': 1076, 'turnover': 0.9754, 'returns': 0.0114, 'drawdown': 0.0412, 'margin': 2.3e-05, 'fitness': 0.06, 'sharpe': 0.56}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.8}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9754}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9754}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.42, 'value': 0.6}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.16, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZ2YMjn', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_returns(vec_avg(rsk60_last), 5), 20)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:03:56-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:03:56-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 797548, 'bookSize': 20000000, 'longCount': 763, 'shortCount': 1012, 'turnover': 1.0698, 'returns': 0.0077, 'drawdown': 0.0494, 'margin': 1.4e-05, 'sharpe': 0.31, 'fitness': 0.03, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -173075, 'bookSize': 20000000, 'longCount': 846, 'shortCount': 1068, 'turnover': 0.2582, 'returns': -0.0017, 'drawdown': 0.1678, 'margin': -1.3e-05, 'fitness': -0.0, 'sharpe': -0.05}, 'riskNeutralized': {'pnl': 447222, 'bookSize': 20000000, 'longCount': 763, 'shortCount': 1012, 'turnover': 1.0698, 'returns': 0.0043, 'drawdown': 0.0585, 'margin': 8e-06, 'fitness': 0.01, 'sharpe': 0.21}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.31}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.03}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0698}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0698}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.16, 'value': 0.42}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.11, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'npkZo918', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_rank(vec_avg(rsk60_crowding), 20)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:03:55-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:03:55-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.55'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -886977, 'bookSize': 20000000, 'longCount': 1034, 'shortCount': 1063, 'turnover': 1.3652, 'returns': -0.0107, 'drawdown': 0.1764, 'margin': -1.6e-05, 'sharpe': -0.31, 'fitness': -0.03, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -526010, 'bookSize': 20000000, 'longCount': 1078, 'shortCount': 1114, 'turnover': 0.2655, 'returns': -0.0063, 'drawdown': 0.2079, 'margin': -4.8e-05, 'fitness': -0.03, 'sharpe': -0.18}, 'riskNeutralized': {'pnl': -877813, 'bookSize': 20000000, 'longCount': 1034, 'shortCount': 1063, 'turnover': 1.3652, 'returns': -0.0105, 'drawdown': 0.1344, 'margin': -1.5e-05, 'fitness': -0.03, 'sharpe': -0.37}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.31}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.03}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3652}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3652}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.16, 'value': -0.29}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.12, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'qMkPd892', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(divide(vec_avg(rsk60_offer), vec_avg(rsk60_last)), 20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-07T00:03:56-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:03:57-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -448154, 'bookSize': 20000000, 'longCount': 889, 'shortCount': 766, 'turnover': 1.0953, 'returns': -0.0043, 'drawdown': 0.1128, 'margin': -8e-06, 'sharpe': -0.16, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -151024, 'bookSize': 20000000, 'longCount': 946, 'shortCount': 849, 'turnover': 0.2268, 'returns': -0.0015, 'drawdown': 0.1217, 'margin': -1.3e-05, 'fitness': -0.0, 'sharpe': -0.05}, 'riskNeutralized': {'pnl': -203308, 'bookSize': 20000000, 'longCount': 889, 'shortCount': 766, 'turnover': 1.0953, 'returns': -0.002, 'drawdown': 0.078, 'margin': -4e-06, 'fitness': -0.0, 'sharpe': -0.09}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.16}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0953}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0953}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.08, 'value': -0.09}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.61, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Vkw2EVqM', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_delta(vec_sum(rsk60_offer), 3), 20)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:04:02-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:04:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1476057, 'bookSize': 20000000, 'longCount': 734, 'shortCount': 783, 'turnover': 1.1088, 'returns': 0.0143, 'drawdown': 0.1362, 'margin': 2.6e-05, 'sharpe': 0.42, 'fitness': 0.05, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -603692, 'bookSize': 20000000, 'longCount': 857, 'shortCount': 830, 'turnover': 0.2274, 'returns': -0.0059, 'drawdown': 0.1709, 'margin': -5.2e-05, 'fitness': -0.02, 'sharpe': -0.15}, 'riskNeutralized': {'pnl': 449856, 'bookSize': 20000000, 'longCount': 734, 'shortCount': 783, 'turnover': 1.1088, 'returns': 0.0044, 'drawdown': 0.1273, 'margin': 8e-06, 'fitness': 0.01, 'sharpe': 0.17}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.42}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.05}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.1088}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.1088}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.22, 'value': 0.37}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.3, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[SAVED] 5 results to ./results/EUR_TOP2500_risk.csv
--- Simulating alpha batch 24 to 32 ---

2026-02-07 14:04:08,121 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': '587a9o9J', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_delta(ts_mean(vec_avg(rsk60_offer),7), 3), 20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-07T00:05:15-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:05:16-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2727889, 'bookSize': 20000000, 'longCount': 703, 'shortCount': 712, 'turnover': 0.4839, 'returns': 0.0265, 'drawdown': 0.0439, 'margin': 0.000109, 'sharpe': 0.91, 'fitness': 0.21, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 582923, 'bookSize': 20000000, 'longCount': 771, 'shortCount': 749, 'turnover': 0.1535, 'returns': 0.0057, 'drawdown': 0.0523, 'margin': 7.4e-05, 'fitness': 0.03, 'sharpe': 0.18}, 'riskNeutralized': {'pnl': 1110763, 'bookSize': 20000000, 'longCount': 703, 'shortCount': 712, 'turnover': 0.4839, 'returns': 0.0108, 'drawdown': 0.0399, 'margin': 4.5e-05, 'fitness': 0.07, 'sharpe': 0.44}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.91}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.21}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4839}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4839}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.47, 'value': 1.04}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.34, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1JgbMbd', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_rank(vec_avg(rsk60_offer),20), ts_rank(vec_avg(rsk60_crowding),20)), 20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:05:15-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:05:16-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.54'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3086014, 'bookSize': 20000000, 'longCount': 840, 'shortCount': 876, 'turnover': 0.9184, 'returns': 0.0371, 'drawdown': 0.0273, 'margin': 8.1e-05, 'sharpe': 1.33, 'fitness': 0.27, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 911735, 'bookSize': 20000000, 'longCount': 914, 'shortCount': 938, 'turnover': 0.2176, 'returns': 0.011, 'drawdown': 0.0665, 'margin': 0.000101, 'fitness': 0.09, 'sharpe': 0.41}, 'riskNeutralized': {'pnl': 2048837, 'bookSize': 20000000, 'longCount': 840, 'shortCount': 876, 'turnover': 0.9184, 'returns': 0.0246, 'drawdown': 0.0248, 'margin': 5.4e-05, 'fitness': 0.17, 'sharpe': 1.06}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 1.33}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.27}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9184}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9184}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.69, 'value': 1.39}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.58, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'LLbg6AEm', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_avg(rsk60_crowding), 20)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:05:26-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:05:27-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.53'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -684599, 'bookSize': 20000000, 'longCount': 732, 'shortCount': 905, 'turnover': 1.422, 'returns': -0.0082, 'drawdown': 0.1857, 'margin': -1.2e-05, 'sharpe': -0.22, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -523189, 'bookSize': 20000000, 'longCount': 819, 'shortCount': 948, 'turnover': 0.2469, 'returns': -0.0063, 'drawdown': 0.2242, 'margin': -5.1e-05, 'fitness': -0.02, 'sharpe': -0.14}, 'riskNeutralized': {'pnl': -414395, 'bookSize': 20000000, 'longCount': 732, 'shortCount': 905, 'turnover': 1.422, 'returns': -0.005, 'drawdown': 0.1246, 'margin': -7e-06, 'fitness': -0.01, 'sharpe': -0.15}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.22}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.422}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.422}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.11, 'value': -0.53}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.25, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVaLEwM', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'days_from_last_change(vec_avg(rsk60_crowding))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:05:44-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:05:45-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.52'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -865276, 'bookSize': 20000000, 'longCount': 657, 'shortCount': 2194, 'turnover': 0.0219, 'returns': -0.0104, 'drawdown': 0.232, 'margin': -0.000948, 'sharpe': -0.24, 'fitness': -0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -843740, 'bookSize': 20000000, 'longCount': 724, 'shortCount': 2132, 'turnover': 0.0211, 'returns': -0.0101, 'drawdown': 0.251, 'margin': -0.00096, 'fitness': -0.07, 'sharpe': -0.23}, 'riskNeutralized': {'pnl': 139621, 'bookSize': 20000000, 'longCount': 657, 'shortCount': 2194, 'turnover': 0.0219, 'returns': 0.0017, 'drawdown': 0.1053, 'margin': 0.000153, 'fitness': 0.01, 'sharpe': 0.07}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.24}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0219}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0219}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.12, 'value': 0.48}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.83, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1JgbKle', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_min(rsk60_last), 15)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:05:44-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:05:45-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.57'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1438011, 'bookSize': 20000000, 'longCount': 649, 'shortCount': 916, 'turnover': 0.9565, 'returns': 0.0139, 'drawdown': 0.0683, 'margin': 2.9e-05, 'sharpe': 0.53, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -615313, 'bookSize': 20000000, 'longCount': 750, 'shortCount': 976, 'turnover': 0.2031, 'returns': -0.006, 'drawdown': 0.1844, 'margin': -5.9e-05, 'fitness': -0.03, 'sharpe': -0.2}, 'riskNeutralized': {'pnl': 969542, 'bookSize': 20000000, 'longCount': 649, 'shortCount': 916, 'turnover': 0.9565, 'returns': 0.0094, 'drawdown': 0.0483, 'margin': 2e-05, 'fitness': 0.04, 'sharpe': 0.44}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.53}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9565}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9565}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.28, 'value': 0.58}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.36, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'N1Wg69rw', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'sign(subtract(vec_avg(rsk60_offer), vec_avg(rsk60_last)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-07T00:05:43-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:05:43-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -537282, 'bookSize': 20000000, 'longCount': 1047, 'shortCount': 909, 'turnover': 0.7779, 'returns': -0.0052, 'drawdown': 0.1298, 'margin': -1.3e-05, 'sharpe': -0.15, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 94333, 'bookSize': 20000000, 'longCount': 1164, 'shortCount': 960, 'turnover': 0.1623, 'returns': 0.0009, 'drawdown': 0.1528, 'margin': 1.1e-05, 'fitness': 0.0, 'sharpe': 0.02}, 'riskNeutralized': {'pnl': 199873, 'bookSize': 20000000, 'longCount': 1047, 'shortCount': 909, 'turnover': 0.7779, 'returns': 0.0019, 'drawdown': 0.0852, 'margin': 5e-06, 'fitness': 0.0, 'sharpe': 0.08}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.15}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.7779}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.7779}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.08, 'value': -0.11}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.49, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 14:08:16,862 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': 'bl2oMNpR', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_backfill(vec_avg(rsk60_crowding), 5), 20)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:09:27-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:09:27-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.57'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -708949, 'bookSize': 20000000, 'longCount': 763, 'shortCount': 938, 'turnover': 1.3871, 'returns': -0.0085, 'drawdown': 0.186, 'margin': -1.2e-05, 'sharpe': -0.23, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -214106, 'bookSize': 20000000, 'longCount': 829, 'shortCount': 954, 'turnover': 0.2352, 'returns': -0.0026, 'drawdown': 0.1968, 'margin': -2.2e-05, 'fitness': -0.01, 'sharpe': -0.06}, 'riskNeutralized': {'pnl': -285209, 'bookSize': 20000000, 'longCount': 763, 'shortCount': 938, 'turnover': 1.3871, 'returns': -0.0034, 'drawdown': 0.1116, 'margin': -5e-06, 'fitness': -0.01, 'sharpe': -0.11}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.23}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.3871}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.3871}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.12, 'value': -0.53}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.16, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'omw3vnQm', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(vec_avg(rsk60_last), ts_mean(vec_avg(rsk60_last), 5)), 20)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-07T00:09:27-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:09:28-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1187408, 'bookSize': 20000000, 'longCount': 850, 'shortCount': 941, 'turnover': 1.15, 'returns': 0.0115, 'drawdown': 0.0587, 'margin': 2e-05, 'sharpe': 0.45, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 553765, 'bookSize': 20000000, 'longCount': 914, 'shortCount': 984, 'turnover': 0.2547, 'returns': 0.0054, 'drawdown': 0.1117, 'margin': 4.2e-05, 'fitness': 0.03, 'sharpe': 0.18}, 'riskNeutralized': {'pnl': 913656, 'bookSize': 20000000, 'longCount': 850, 'shortCount': 941, 'turnover': 1.15, 'returns': 0.0089, 'drawdown': 0.0521, 'margin': 1.5e-05, 'fitness': 0.04, 'sharpe': 0.42}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.45}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.15}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.15}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.23, 'value': 0.15}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.07, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'omw3vn5l', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(vec_avg(rsk60_offer),20), ts_zscore(vec_avg(rsk60_crowding),20))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-07T00:09:25-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:09:25-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2132253, 'bookSize': 20000000, 'longCount': 490, 'shortCount': 561, 'turnover': 0.8035, 'returns': 0.0256, 'drawdown': 0.0573, 'margin': 6.4e-05, 'sharpe': 0.77, 'fitness': 0.14, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1482427, 'bookSize': 20000000, 'longCount': 595, 'shortCount': 652, 'turnover': 0.1498, 'returns': -0.0178, 'drawdown': 0.1957, 'margin': -0.000238, 'fitness': -0.17, 'sharpe': -0.48}, 'riskNeutralized': {'pnl': 1501469, 'bookSize': 20000000, 'longCount': 490, 'shortCount': 561, 'turnover': 0.8035, 'returns': 0.018, 'drawdown': 0.0537, 'margin': 4.5e-05, 'fitness': 0.09, 'sharpe': 0.63}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.77}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.14}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.8035}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.8035}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.4, 'value': 1.02}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.6, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Jj0gmn0x', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_av_diff(vec_avg(rsk60_offer), 30), 30)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:09:28-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:09:28-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2254083, 'bookSize': 20000000, 'longCount': 781, 'shortCount': 913, 'turnover': 0.5222, 'returns': 0.0219, 'drawdown': 0.038, 'margin': 8.4e-05, 'sharpe': 0.86, 'fitness': 0.18, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 993521, 'bookSize': 20000000, 'longCount': 865, 'shortCount': 945, 'turnover': 0.1497, 'returns': 0.0096, 'drawdown': 0.0613, 'margin': 0.000129, 'fitness': 0.09, 'sharpe': 0.35}, 'riskNeutralized': {'pnl': 885022, 'bookSize': 20000000, 'longCount': 781, 'shortCount': 913, 'turnover': 0.5222, 'returns': 0.0086, 'drawdown': 0.0333, 'margin': 3.3e-05, 'fitness': 0.05, 'sharpe': 0.42}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.86}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.18}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5222}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5222}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.45, 'value': 0.85}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.98, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'omw3vnZm', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(add(ts_zscore(vec_avg(rsk60_offer),20), ts_zscore(vec_avg(rsk60_last),20)), 20)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:09:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:09:40-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1322393, 'bookSize': 20000000, 'longCount': 504, 'shortCount': 605, 'turnover': 0.7987, 'returns': 0.0128, 'drawdown': 0.0757, 'margin': 3.2e-05, 'sharpe': 0.43, 'fitness': 0.05, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 97771, 'bookSize': 20000000, 'longCount': 595, 'shortCount': 704, 'turnover': 0.1555, 'returns': 0.0009, 'drawdown': 0.1082, 'margin': 1.2e-05, 'fitness': 0.0, 'sharpe': 0.03}, 'riskNeutralized': {'pnl': 880734, 'bookSize': 20000000, 'longCount': 504, 'shortCount': 605, 'turnover': 0.7987, 'returns': 0.0085, 'drawdown': 0.0952, 'margin': 2.1e-05, 'fitness': 0.03, 'sharpe': 0.33}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.43}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.05}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.7987}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.7987}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.22, 'value': 0.33}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.26, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Wjwad9EP', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_av_diff(vec_avg(rsk60_last), 30), 30)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:09:44-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:09:44-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2063183, 'bookSize': 20000000, 'longCount': 844, 'shortCount': 1073, 'turnover': 0.746, 'returns': 0.02, 'drawdown': 0.0521, 'margin': 5.4e-05, 'sharpe': 0.85, 'fitness': 0.14, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1091789, 'bookSize': 20000000, 'longCount': 908, 'shortCount': 1105, 'turnover': 0.1865, 'returns': 0.0106, 'drawdown': 0.0733, 'margin': 0.000114, 'fitness': 0.1, 'sharpe': 0.42}, 'riskNeutralized': {'pnl': 1236818, 'bookSize': 20000000, 'longCount': 844, 'shortCount': 1073, 'turnover': 0.746, 'returns': 0.012, 'drawdown': 0.0308, 'margin': 3.2e-05, 'fitness': 0.08, 'sharpe': 0.66}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.85}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.14}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.746}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.746}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.44, 'value': 0.78}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.22, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 14:09:50,866 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': '2rqaRNMP', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_arg_min(vec_avg(rsk60_last), 5), 10)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:11:07-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:11:08-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.51'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 359271, 'bookSize': 20000000, 'longCount': 1054, 'shortCount': 690, 'turnover': 1.0054, 'returns': 0.0035, 'drawdown': 0.0621, 'margin': 7e-06, 'sharpe': 0.15, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 734099, 'bookSize': 20000000, 'longCount': 1105, 'shortCount': 788, 'turnover': 0.2383, 'returns': 0.0071, 'drawdown': 0.0744, 'margin': 6e-05, 'fitness': 0.04, 'sharpe': 0.25}, 'riskNeutralized': {'pnl': 669330, 'bookSize': 20000000, 'longCount': 1054, 'shortCount': 690, 'turnover': 1.0054, 'returns': 0.0065, 'drawdown': 0.0599, 'margin': 1.3e-05, 'fitness': 0.03, 'sharpe': 0.32}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.15}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0054}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0054}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.08, 'value': -0.11}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.47, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '9qPaK7rd', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_delta(ts_mean(vec_avg(rsk60_crowding), 3), 1), 20)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-07T00:11:16-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:11:16-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.54'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 196124, 'bookSize': 20000000, 'longCount': 840, 'shortCount': 868, 'turnover': 1.5419, 'returns': 0.0024, 'drawdown': 0.0948, 'margin': 3e-06, 'sharpe': 0.07, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -783972, 'bookSize': 20000000, 'longCount': 893, 'shortCount': 890, 'turnover': 0.2632, 'returns': -0.0094, 'drawdown': 0.2031, 'margin': -7.2e-05, 'fitness': -0.04, 'sharpe': -0.23}, 'riskNeutralized': {'pnl': 121842, 'bookSize': 20000000, 'longCount': 840, 'shortCount': 868, 'turnover': 1.5419, 'returns': 0.0015, 'drawdown': 0.0704, 'margin': 2e-06, 'fitness': 0.0, 'sharpe': 0.05}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.07}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.5419}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.5419}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-09-08', 'limit': 0.1, 'value': 0.227814}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.04, 'value': 0.01}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.01, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qaQnJO', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_sum(vec_avg(rsk60_crowding), 14), 20)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:11:14-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:11:15-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.56'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -646048, 'bookSize': 20000000, 'longCount': 864, 'shortCount': 922, 'turnover': 0.4428, 'returns': -0.0078, 'drawdown': 0.0887, 'margin': -3.5e-05, 'sharpe': -0.3, 'fitness': -0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -115316, 'bookSize': 20000000, 'longCount': 906, 'shortCount': 946, 'turnover': 0.1416, 'returns': -0.0014, 'drawdown': 0.1081, 'margin': -2e-05, 'fitness': -0.0, 'sharpe': -0.05}, 'riskNeutralized': {'pnl': 116664, 'bookSize': 20000000, 'longCount': 864, 'shortCount': 922, 'turnover': 0.4428, 'returns': 0.0014, 'drawdown': 0.0512, 'margin': 6e-06, 'fitness': 0.0, 'sharpe': 0.06}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.3}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4428}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4428}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.16, 'value': -0.63}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.56, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '3qYaxe5P', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(last_diff_value(vec_avg(rsk60_crowding), 5), 10)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:11:22-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:11:23-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.53'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1804334, 'bookSize': 20000000, 'longCount': 618, 'shortCount': 682, 'turnover': 1.0408, 'returns': -0.0217, 'drawdown': 0.1938, 'margin': -4.2e-05, 'sharpe': -0.67, 'fitness': -0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1830277, 'bookSize': 20000000, 'longCount': 710, 'shortCount': 755, 'turnover': 0.1948, 'returns': -0.022, 'drawdown': 0.2262, 'margin': -0.000226, 'fitness': -0.19, 'sharpe': -0.58}, 'riskNeutralized': {'pnl': -963331, 'bookSize': 20000000, 'longCount': 618, 'shortCount': 682, 'turnover': 1.0408, 'returns': -0.0116, 'drawdown': 0.133, 'margin': -2.2e-05, 'fitness': -0.04, 'sharpe': -0.42}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.67}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0408}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0408}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.35, 'value': -0.51}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.5, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '2rqaRp1b', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_range(rsk60_offer), 15)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:11:27-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:11:28-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1773209, 'bookSize': 20000000, 'longCount': 108, 'shortCount': 135, 'turnover': 0.8684, 'returns': -0.0172, 'drawdown': 0.7008, 'margin': -4e-05, 'sharpe': -0.1, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1467334, 'bookSize': 20000000, 'longCount': 169, 'shortCount': 175, 'turnover': 0.1341, 'returns': -0.0142, 'drawdown': 0.7653, 'margin': -0.000212, 'fitness': -0.02, 'sharpe': -0.07}, 'riskNeutralized': {'pnl': -1182441, 'bookSize': 20000000, 'longCount': 108, 'shortCount': 135, 'turnover': 0.8684, 'returns': -0.0115, 'drawdown': 0.6594, 'margin': -2.6e-05, 'fitness': -0.01, 'sharpe': -0.07}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.1}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.8684}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.8684}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2015-10-19', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.05, 'value': -0.17}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.37, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '587a9kdN', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(vec_range(rsk60_last), 15)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:11:24-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:11:25-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.59'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7193328, 'bookSize': 20000000, 'longCount': 127, 'shortCount': 177, 'turnover': 0.9883, 'returns': 0.0698, 'drawdown': 0.2901, 'margin': 0.000141, 'sharpe': 0.43, 'fitness': 0.11, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 385867, 'bookSize': 20000000, 'longCount': 202, 'shortCount': 217, 'turnover': 0.158, 'returns': 0.0037, 'drawdown': 0.5865, 'margin': 4.7e-05, 'fitness': 0.0, 'sharpe': 0.02}, 'riskNeutralized': {'pnl': 7184978, 'bookSize': 20000000, 'longCount': 127, 'shortCount': 177, 'turnover': 0.9883, 'returns': 0.0697, 'drawdown': 0.2363, 'margin': 0.000141, 'fitness': 0.13, 'sharpe': 0.49}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.43}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.11}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9883}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9883}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2015-02-03', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.22, 'value': 0.37}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.95, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 14:20:54,008 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': 'LLbgX6wm', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(divide(ts_std_dev(vec_avg(rsk60_offer), 5), ts_std_dev(vec_avg(rsk60_offer), 20)), 30)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:21:59-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:21:59-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 91257, 'bookSize': 20000000, 'longCount': 466, 'shortCount': 716, 'turnover': 0.5062, 'returns': 0.0009, 'drawdown': 0.0622, 'margin': 4e-06, 'sharpe': 0.03, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 810755, 'bookSize': 20000000, 'longCount': 547, 'shortCount': 808, 'turnover': 0.1416, 'returns': 0.0079, 'drawdown': 0.0886, 'margin': 0.000111, 'fitness': 0.06, 'sharpe': 0.26}, 'riskNeutralized': {'pnl': -114505, 'bookSize': 20000000, 'longCount': 466, 'shortCount': 716, 'turnover': 0.5062, 'returns': -0.0011, 'drawdown': 0.0885, 'margin': -4e-06, 'fitness': -0.0, 'sharpe': -0.05}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.03}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5062}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5062}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.02, 'value': -0.4}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.48, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'bl2oPMzm', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(divide(ts_std_dev(vec_avg(rsk60_last), 5), ts_std_dev(vec_avg(rsk60_last), 20)), 30)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:21:57-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:21:58-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 152673, 'bookSize': 20000000, 'longCount': 756, 'shortCount': 984, 'turnover': 0.4869, 'returns': 0.0015, 'drawdown': 0.074, 'margin': 6e-06, 'sharpe': 0.06, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 106430, 'bookSize': 20000000, 'longCount': 810, 'shortCount': 1027, 'turnover': 0.1669, 'returns': 0.001, 'drawdown': 0.084, 'margin': 1.2e-05, 'fitness': 0.0, 'sharpe': 0.04}, 'riskNeutralized': {'pnl': -507991, 'bookSize': 20000000, 'longCount': 756, 'shortCount': 984, 'turnover': 0.4869, 'returns': -0.0049, 'drawdown': 0.1202, 'margin': -2e-05, 'fitness': -0.02, 'sharpe': -0.23}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.06}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4869}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4869}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.03, 'value': 0.27}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.22, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'mL2rzANx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_zscore(vec_stddev(rsk60_crowding), 15))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:21:59-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:21:59-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.45'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -7408434, 'bookSize': 20000000, 'longCount': 81, 'shortCount': 55, 'turnover': 1.2475, 'returns': -0.0891, 'drawdown': 1.2003, 'margin': -0.000143, 'sharpe': -0.44, 'fitness': -0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -12721070, 'bookSize': 20000000, 'longCount': 111, 'shortCount': 100, 'turnover': 0.1842, 'returns': -0.153, 'drawdown': 1.4682, 'margin': -0.001661, 'fitness': -0.48, 'sharpe': -0.53}, 'riskNeutralized': {'pnl': -5445969, 'bookSize': 20000000, 'longCount': 81, 'shortCount': 55, 'turnover': 1.2475, 'returns': -0.0655, 'drawdown': 1.0022, 'margin': -0.000105, 'fitness': -0.09, 'sharpe': -0.38}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.44}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.2475}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.2475}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2016-05-02', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.23, 'value': -0.22}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.1, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'vRnezz3w', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_zscore(subtract(vec_avg(rsk60_offer), ts_mean(vec_avg(rsk60_offer), 5)), 20))', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:22:02-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:22:02-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1600702, 'bookSize': 20000000, 'longCount': 677, 'shortCount': 654, 'turnover': 0.9945, 'returns': -0.0155, 'drawdown': 0.224, 'margin': -3.1e-05, 'sharpe': -0.47, 'fitness': -0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 457313, 'bookSize': 20000000, 'longCount': 738, 'shortCount': 742, 'turnover': 0.2008, 'returns': 0.0044, 'drawdown': 0.0983, 'margin': 4.4e-05, 'fitness': 0.02, 'sharpe': 0.12}, 'riskNeutralized': {'pnl': -764058, 'bookSize': 20000000, 'longCount': 677, 'shortCount': 654, 'turnover': 0.9945, 'returns': -0.0074, 'drawdown': 0.1625, 'margin': -1.5e-05, 'fitness': -0.02, 'sharpe': -0.28}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.47}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.9945}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.9945}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.24, 'value': -0.43}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.85, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '0mkeQerr', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(subtract(ts_mean(vec_avg(rsk60_last), 10), ts_mean(vec_avg(rsk60_last), 30)), 30)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:22:43-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:22:44-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1811130, 'bookSize': 20000000, 'longCount': 969, 'shortCount': 979, 'turnover': 0.262, 'returns': 0.0176, 'drawdown': 0.0389, 'margin': 0.000135, 'sharpe': 0.79, 'fitness': 0.2, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 979101, 'bookSize': 20000000, 'longCount': 989, 'shortCount': 999, 'turnover': 0.1236, 'returns': 0.0095, 'drawdown': 0.091, 'margin': 0.000154, 'fitness': 0.11, 'sharpe': 0.41}, 'riskNeutralized': {'pnl': 401790, 'bookSize': 20000000, 'longCount': 969, 'shortCount': 979, 'turnover': 0.262, 'returns': 0.0039, 'drawdown': 0.053, 'margin': 3e-05, 'fitness': 0.03, 'sharpe': 0.21}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.79}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.2}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.262}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.262}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.41, 'value': 0.79}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.47, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'MPlK8bVr', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_zscore(subtract(vec_avg(rsk60_last), ts_mean(vec_avg(rsk60_last), 5)), 20))', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-07T00:23:04-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:23:04-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1187408, 'bookSize': 20000000, 'longCount': 941, 'shortCount': 850, 'turnover': 1.15, 'returns': -0.0115, 'drawdown': 0.1713, 'margin': -2e-05, 'sharpe': -0.45, 'fitness': -0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -553765, 'bookSize': 20000000, 'longCount': 984, 'shortCount': 914, 'turnover': 0.2547, 'returns': -0.0054, 'drawdown': 0.157, 'margin': -4.2e-05, 'fitness': -0.03, 'sharpe': -0.18}, 'riskNeutralized': {'pnl': -913656, 'bookSize': 20000000, 'longCount': 941, 'shortCount': 850, 'turnover': 1.15, 'returns': -0.0089, 'drawdown': 0.1382, 'margin': -1.5e-05, 'fitness': -0.04, 'sharpe': -0.42}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.45}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.15}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.15}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.23, 'value': -0.15}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.07, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-07 14:23:36,017 - ace - ERROR - Simulation failed. {'id': '3DbFsm3La4PJ8Cn1dgYLZWE6', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'ZYw2lEXd', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_quantile(vec_avg(rsk60_crowding), 10))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:24:38-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:24:39-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.54'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 725678, 'bookSize': 20000000, 'longCount': 1050, 'shortCount': 1036, 'turnover': 1.4055, 'returns': 0.0087, 'drawdown': 0.1095, 'margin': 1.2e-05, 'sharpe': 0.25, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 158393, 'bookSize': 20000000, 'longCount': 1096, 'shortCount': 1087, 'turnover': 0.2766, 'returns': 0.0019, 'drawdown': 0.1612, 'margin': 1.4e-05, 'fitness': 0.0, 'sharpe': 0.05}, 'riskNeutralized': {'pnl': 848316, 'bookSize': 20000000, 'longCount': 1050, 'shortCount': 1036, 'turnover': 1.4055, 'returns': 0.0102, 'drawdown': 0.0852, 'margin': 1.5e-05, 'fitness': 0.03, 'sharpe': 0.35}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.25}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.4055}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.4055}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.13, 'value': 0.2}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.37, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'LLbgXGz2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'hump(ts_zscore(vec_avg(rsk60_last), 10), hump=0.01)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:24:39-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:24:40-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 554737, 'bookSize': 20000000, 'longCount': 736, 'shortCount': 818, 'turnover': 0.1457, 'returns': 0.0054, 'drawdown': 0.0418, 'margin': 7.4e-05, 'sharpe': 0.23, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 119639, 'bookSize': 20000000, 'longCount': 856, 'shortCount': 904, 'turnover': 0.0748, 'returns': 0.0012, 'drawdown': 0.0981, 'margin': 3.1e-05, 'fitness': 0.0, 'sharpe': 0.05}, 'riskNeutralized': {'pnl': 703256, 'bookSize': 20000000, 'longCount': 736, 'shortCount': 818, 'turnover': 0.1457, 'returns': 0.0068, 'drawdown': 0.0298, 'margin': 9.4e-05, 'fitness': 0.08, 'sharpe': 0.36}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.23}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1457}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1457}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.12, 'value': 0.08}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.17, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Xgw2lJgb', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'trade_when(ts_zscore(vec_avg(rsk60_crowding), 10), ts_zscore(vec_avg(rsk60_crowding), 10), NaN)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-07T00:25:34-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:25:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.5'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 286024, 'bookSize': 20000000, 'longCount': 973, 'shortCount': 1305, 'turnover': 0.2378, 'returns': 0.0034, 'drawdown': 0.0742, 'margin': 2.9e-05, 'sharpe': 0.16, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 94499, 'bookSize': 20000000, 'longCount': 962, 'shortCount': 1321, 'turnover': 0.0894, 'returns': 0.0011, 'drawdown': 0.1181, 'margin': 2.5e-05, 'fitness': 0.0, 'sharpe': 0.05}, 'riskNeutralized': {'pnl': -100807, 'bookSize': 20000000, 'longCount': 973, 'shortCount': 1305, 'turnover': 0.2378, 'returns': -0.0012, 'drawdown': 0.0421, 'margin': -1e-05, 'fitness': -0.01, 'sharpe': -0.08}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.16}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2378}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2378}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.08, 'value': -0.14}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.94, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'O0wbm8YJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_zscore(vec_avg(rsk60_crowding),10), 1), greater(ts_zscore(vec_avg(rsk60_offer),10), 1))', 'description': None, 'operatorCount': 7}, 'dateCreated': '2026-02-07T00:25:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:25:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.55'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2612953, 'bookSize': 20000000, 'longCount': 49, 'shortCount': 474, 'turnover': 1.4954, 'returns': 0.0314, 'drawdown': 0.1129, 'margin': 4.2e-05, 'sharpe': 0.39, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1577327, 'bookSize': 20000000, 'longCount': 316, 'shortCount': 741, 'turnover': 0.1918, 'returns': -0.019, 'drawdown': 0.4551, 'margin': -0.000198, 'fitness': -0.08, 'sharpe': -0.24}, 'riskNeutralized': {'pnl': 552317, 'bookSize': 20000000, 'longCount': 49, 'shortCount': 474, 'turnover': 1.4954, 'returns': 0.0066, 'drawdown': 0.1397, 'margin': 9e-06, 'fitness': 0.01, 'sharpe': 0.1}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.39}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.4954}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.4954}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.2, 'value': 0.16}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.06, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'WjwaXeMO', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'hump(ts_zscore(vec_avg(rsk60_offer), 10), hump=0.01)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-07T00:25:34-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:25:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.59'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2263689, 'bookSize': 20000000, 'longCount': 477, 'shortCount': 427, 'turnover': 0.2402, 'returns': 0.022, 'drawdown': 0.0511, 'margin': 0.000183, 'sharpe': 0.75, 'fitness': 0.23, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2176208, 'bookSize': 20000000, 'longCount': 647, 'shortCount': 559, 'turnover': 0.0903, 'returns': 0.0211, 'drawdown': 0.0491, 'margin': 0.000468, 'fitness': 0.28, 'sharpe': 0.68}, 'riskNeutralized': {'pnl': 1419143, 'bookSize': 20000000, 'longCount': 477, 'shortCount': 427, 'turnover': 0.2402, 'returns': 0.0138, 'drawdown': 0.0528, 'margin': 0.000115, 'fitness': 0.13, 'sharpe': 0.55}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.75}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.23}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2402}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2402}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.39, 'value': 1.03}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.55, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'LLbgXZRe', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_quantile(vec_avg(rsk60_last), 10)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-07T00:25:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-07T00:25:40-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1681803, 'bookSize': 20000000, 'longCount': 979, 'shortCount': 1060, 'turnover': 1.0277, 'returns': 0.0163, 'drawdown': 0.0421, 'margin': 3.2e-05, 'sharpe': 0.72, 'fitness': 0.09, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -106105, 'bookSize': 20000000, 'longCount': 1038, 'shortCount': 1077, 'turnover': 0.2476, 'returns': -0.001, 'drawdown': 0.1341, 'margin': -8e-06, 'fitness': -0.0, 'sharpe': -0.04}, 'riskNeutralized': {'pnl': 1202017, 'bookSize': 20000000, 'longCount': 979, 'shortCount': 1060, 'turnover': 1.0277, 'returns': 0.0117, 'drawdown': 0.05, 'margin': 2.3e-05, 'fitness': 0.07, 'sharpe': 0.62}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.72}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.09}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0277}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0277}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.37, 'value': 0.68}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.33, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.1, 'pyramids': [{'name': 'EUR/D1/RISK', 'multiplier': 1.1}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

# LLM 함수 해설

In [ ]:
import random
# def generate_expressions_from_dataset(s, alpha_region, alpha_universe, dataset_id, model = 'gpt-5-mini-2025-08-07', datafields_num_cap = 500, alpha_num = 100, top_n_datafields = 3):

# 함수 인풋들
# 🔧 REGION / UNIVERSE GLOBALIZED
alpha_region = REGION
alpha_universe = UNIVERSE
dataset_id = "other455"
datafields_num_cap = 500
alpha_num = 100

# 🔧 NEW: 상위 N개 datafield만 사용하는 설정
top_n_datafields = 3

# 데이터셋에서 데이터필드 불러오기
data_fields = ace.get_datafields(s, region=alpha_region, universe=alpha_universe, dataset_id=dataset_id, data_type='ALL')
data_fields = data_fields[data_fields['type'] != "GROUP"]

# 🔧 NEW: alphaCount 기준 상위 N개 datafield만 선택
top_fields_df = data_fields.nlargest(top_n_datafields, "alphaCount")

# 🔧 NEW: LLM 입력용 compact datafield spec 생성 (토큰 절약)
# 필요한 키만 포함: id, description, subcategory, coverage, userCount, alphaCount, type
selected_datafields_spec = top_fields_df[[
    "id",
    "description", 
    "subcategory",
    "coverage",
    "userCount",
    "alphaCount",
    "type"  # VECTOR / MATRIX 구분용
]].to_dict("records")

print(f"[INFO] Selected top {len(selected_datafields_spec)} datafields for dataset '{dataset_id}':")
for df_spec in selected_datafields_spec:
    print(f"  - {df_spec.get('id', 'N/A')} (alphaCount: {df_spec.get('alphaCount', 'N/A')}, type: {df_spec.get('type', 'N/A')})")

# 오퍼레이터도 같은 방식으로 만들어 줌
operators = ace.get_operators(s)
operators_list = [row.to_dict() for row in operators[operators['scope']=='REGULAR'].iloc]

# rank는 LLM이 너무 많이 씀 - 빼줌
operator_exclude = []
operators_list = [x for x in operators_list if x['name'] not in operator_exclude]


answer_form = '''{
    "results":[
        {
            "idea":...,
            "description":...,
            "implementation":...,
            "confidence_level":...
        }
    ]
}'''

# 🔧 MODIFIED: 프롬프트에 ALLOWED_DATAFIELDS 섹션 추가 및 KEEP_IN_MIND 업데이트
prompt = f"""
<MISSION>
Based on the OPERATORS and ALLOWED_DATAFIELDS below,
1. SUGGEST {alpha_num} SEPARATED and DIVERSIFIED Alpha ideas which can create excess return in the market
2. Divide your idea into 4 parts, "idea", "description", "implementation", and "target".
3. "idea" must contain the core idea of the alpha.
4. "description" must include how you considered SUGGESTIONS and KEEP_IN_MINDs, and how much you set the confidence of this alpha. Consider SUGGESTIONS and write the reason you applied or didn't apply each of the SUGGESTIONS.
5. "implementation" must contain implementation of the variation, including specific template (in OPERATOR(MATRIX) form) or exact name of datafield.
6. "confidence_level" should be numerical value set in description, in 0-1 scale. Bigger value means higher confidence of this alpha idea.
Very new user can understand the idea and how to implement this idea.
</MISSION>

<SUGGESTIONS>
SUGGESTION1: Actively use MULTIPLE datafields from ALLOWED_DATAFIELDS. Your main mission is finding great combinations of the allowed datafields.
SUGGESTION2: If a datafield has type=VECTOR, wrap it with vec_avg() or vec_sum() operator.
SUGGESTION3: If the datafield's coverage is lower than 0.6, try using ts_backfill() to preprocess the data.
SUGGESTION4: datafields' userCount and alphaCount are the count of users and alphas submitted. Try to use high user and alphaCount so that you can catch the signal easily.
</SUGGESTIONS>

<KEEP_IN_MIND>
KEEP_IN_MIND1: Final implementation MUST be simple. recommend to use operator "ts_backfill" , "ts_zscore" more often
KEEP_IN_MIND2: Final implementation MUST NOT contain over 4 operators and over 2 datafields.
KEEP_IN_MIND3: You MUST ONLY use datafield IDs from ALLOWED_DATAFIELDS. Using any datafield outside this list is INVALID.
KEEP_IN_MIND4: You CANNOT use type=GROUP field by itself. You need to use it as "group" parameter in Group operator.
KEEP_IN_MIND5: If a datafield has type=VECTOR, it MUST be wrapped with vec_avg() or vec_sum() operator.
</KEEP_IN_MIND>

<OPERATORS>
You can use those operators: {operators_list}
</OPERATORS>

<ALLOWED_DATAFIELDS>
Available datafields = {selected_datafields_spec}
</ALLOWED_DATAFIELDS>

<ANSWER_FORMAT>
You must answer in this form 
{answer_form}
</ANSWER_FORMAT>
""".strip()


print(prompt)

NameError: name 'REGION' is not defined