In [1]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install networkx
!pip install requests
!pip install openai
!pip install nest_asyncio
!pip install tqdm
!pip install Jinja2
# USA = [TOP3000, TOP1000, TOP500, TOP200, ILLIQUID_M2INVOL1M, TOPSP500]

# GLB = [TOP3000, MINVOL1M, TOPDIV3000]

# EUR = [TOP2500, TOP1200, TOP800, TOP400, ILLIQUID_MINVOL1M]

# ASI = [MINVOL1M, ILLIQUID_MINVOL1M]

Requirement already satisfied: pandas in c:\python314\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\python314\lib\site-packages (2.4.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\python314\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\python314\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\python314\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\python314\lib\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in c:\python314\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\python314\lib\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\python314\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\python314\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: networkx in c:\python314\lib\site-packages (3.6.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: requests in c:\python314\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python314\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\python314\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python314\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\python314\lib\site-packages (from requests) (2026.1.4)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: openai in c:\python314\lib\site-packages (2.16.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\python314\lib\site-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in c:\python314\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\python314\lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\python314\lib\site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\python314\lib\site-packages (from openai) (2.12.5)
Requirement already satisfied: sniffio in c:\python314\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\python314\lib\site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\python314\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\python314\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\python314\lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\python314\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\python314\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\python314\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\python314\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\python314\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in c:\python314\lib\site-packages (from tqdm>4->openai) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: nest_asyncio in c:\python314\lib\site-packages (1.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: tqdm in c:\python314\lib\site-packages (4.67.3)
Requirement already satisfied: colorama in c:\python314\lib\site-packages (from tqdm) (0.4.6)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: Jinja2 in c:\python314\lib\site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python314\lib\site-packages (from Jinja2) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Python314\python.exe -m pip install --upgrade pip

# LLM으로 알파 생성하기
* LLM이 발달하면서 이제 mini 등 가벼운 모델로도 알파를 꽤나 쉽게 만들 수 있는 환경이 되었습니다. 
* 오늘 돌리면서 한 쿼리를 6번 정도 날렸는데 $0.4 정도가 나왔습니다. 
* 한 번 알파 100개 만드는 시도를 할 때 약 100원 정도 들어간다고 생각하시면 될 것 같습니다.
* 사양이 괜찮으신 분들은 (또는 최신 맥북을 쓰신다면) ollama로 로컬 LLM도 한번 써보세요! 생각보다 괜찮습니다 성능이

# 데이터필드 정보 저장하기
현재 설정: **REGION / UNIVERSE** (글로벌 변수 참조)
처음 실행 시 30분-1시간 정도 걸리는 작업입니다.

In [2]:
# 처음에만 진행하시면 됩니다.
# 🔧 REGION / UNIVERSE GLOBALIZED - 글로벌 설정
REGION = "EUR"
UNIVERSE = "TOP2500"
DELAY = "1"

import AAF as aaf
import ace_lib as ace
import requests
# 세팅 
settings = {

    "nan_handling" : "OFF",
    "instrumentType": "EQUITY",      # FIXED
    "delay"          : 1,
    "universe"       : UNIVERSE,     # 🔧 REGION / UNIVERSE GLOBALIZED
    "truncation"     : 0.01,
    "unitHandling"   : "VERIFY",     # FIXED
    "pasteurization" : "ON",
    "region"         : REGION,       # 🔧 REGION / UNIVERSE GLOBALIZED
    "language"       : "FASTEXPR",   # FIXED

    "decay"          : 0,
    "neutralization" : "INDUSTRY",     # Can be varied
    "visualization"  : False
    
}

s = requests.Session()
s.auth = (input("Email: "), input("Password: "))
r = s.post("https://api.worldquantbrain.com/authentication")

print("Status:", r.status_code)
print("Headers:", dict(r.headers))
print("Response:", r.json())

s = ace.start_session()
operators = ace.get_operators(s)


# aaf.initiate_datafield(s,settings)

ModuleNotFoundError: No module named 'pandas'

In [ ]:
# 🔧 REGION / UNIVERSE GLOBALIZED
datasets_df = ace.get_datasets(
    s, 
    instrument_type='EQUITY', 
    region=REGION, 
    universe=UNIVERSE,
    delay=1, 
)
selected_datasets_df = datasets_df[
    (datasets_df["alphaCount"] >-1)]
selected_datasets_df

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
0,analyst10,Performance-Weighted Analyst Estimates,"This dataset provides ""smart estimates,"" which...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.7760,...,926,3515,916,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,analyst11,ESG scores,This dataset provides a comprehensive mapping ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8489,...,179,426,445,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
2,analyst14,Estimations of Key Fundamentals,This dataset reports many items from financial...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.5000,...,819,2859,121,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,analyst15,Earnings forecasts,This dataset provides bottom-up forecast data ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.9102,...,1448,10756,1701,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,analyst39,Analyst estimates & financial ratios,This dataset contains detailed point-in-time c...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8755,...,597,3148,24,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,shortinterest6,SmartHoldings Model,This dataset is a global stock selection model...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-estimates-models', 'name': 'Esti...",EUR,1,TOP2500,1.0,1.0000,...,50,130,11,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-estimates-models,Estimates Models
126,socialmedia12,Sentiment Data for Equity,This dataset aggregates and analyzes social me...,"{'id': 'socialmedia', 'name': 'Social Media'}","{'id': 'socialmedia-social-media', 'name': 'So...",EUR,1,TOP2500,1.0,0.7836,...,474,1367,6,1.1,[],"[{'type': 'research', 'title': 'Creating D0 Al...",socialmedia,Social Media,socialmedia-social-media,Social Media
127,socialmedia15,Sentiment Indicators,A dataset model providing normalized sentiment...,"{'id': 'socialmedia', 'name': 'Social Media'}","{'id': 'socialmedia-social-media', 'name': 'So...",EUR,1,TOP2500,1.0,0.2726,...,290,740,13,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",socialmedia,Social Media,socialmedia-social-media,Social Media
128,univ1,Universe Dataset,No dataset description,"{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",EUR,1,TOP2500,1.0,0.7500,...,0,0,4,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",pv,Price Volume,pv-price-volume,Price Volume
129,univ2,Universe Dataset,No dataset description,"{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",EUR,1,TOP2500,NaN,0.6700,...,0,0,1,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",pv,Price Volume,pv-price-volume,Price Volume

In [ ]:
#     "USA": ['analyst12', 'analyst2', 'analyst48', 'analyst9', 'fundamental21', 'fundamental85',
#  'fundamental91', 'macro10', 'macro52', 'model239', 'model240', 'model46', 'model54',
#  'model57', 'news31', 'news5', 'news50', 'news54', 'news79', 'option10', 'option13',
#  'option22', 'other323', 'other492', 'other696', 'sentiment18', 'shortinterest3',
#  'shortinterest36', 'socialmedia3', 'socialmedia8']
# ,
#     "EUR": ['analyst39', 'earnings3', 'model109', 'model138', 'model139', 'model176', 'model25',
#  'model28', 'model30', 'model39', 'news104', 'news17', 'news23', 'news46', 'news79',
#  'other197', 'other455', 'other696', 'risk59', 'risk60', 'risk88',
#  'shortinterest3', 'shortinterest37', 'socialmedia39']
# ,
#     "ASI": ['analyst44', 'analyst48', 'analyst69', 'analyst9', 'fundamental17', 'fundamental21',
#  'fundamental23', 'fundamental28', 'fundamental44', 'fundamental6', 'fundamental72',
#  'model106', 'model109', 'model138', 'model16', 'model262', 'model53', 'model77',
#  'other128', 'other455', 'other463', 'other675', 'pv13', 'risk74', 'risk88',
#  'shortinterest37']
# ,
#     "GLB": ['analyst11', 'analyst35', 'analyst44', 'analyst48', 'analyst82', 'analyst9',
#  'fundamental45', 'fundamental46', 'fundamental6', 'fundamental7', 'fundamental72',
#  'model106', 'model16', 'model162', 'model262', 'news52', 'news76', 'other128',
#  'other169', 'other463', 'other675', 'pv13', 'pv30', 'pv53', 'risk74', 'risk88',
#  'shortinterest37']

In [ ]:
selected_df = datasets_df[datasets_df['alphaCount']>100]
dataset_ids =  ['analyst39', 'earnings3', 'model109', 'model138', 'model139', 'model176', 'model25',
  'model28', 'model30', 'model39', 'news104', 'news17', 'news23', 'news46', 'news79',
  'other197', 'other455', 'other696', 'risk59', 'risk60', 'risk88',
  'shortinterest3', 'shortinterest37', 'socialmedia39']
saved_fields =[]

In [ ]:
filtered_df = selected_df[
    selected_df['id'].str.split('_').str[0].isin(dataset_ids)
]
filtered_df = filtered_df.sort_values(
    by='alphaCount',
    ascending=False
)

filtered_df

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
41,model25,Earnings Quality,This model dataset provides with financial sta...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-revisions-models', 'name': 'Revi...",EUR,1,TOP2500,1.0,0.6591,...,1156,7036,199,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-revisions-models,Revisions Models
4,analyst39,Analyst estimates & financial ratios,This dataset contains detailed point-in-time c...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8755,...,597,3148,24,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
32,model138,Stock Selection from Accounting-based Factors,This dataset contains a comprehensive suite of...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-mlai-models', 'name': 'ML/AI Mod...",EUR,1,TOP2500,1.0,0.5537,...,651,2723,120,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-mlai-models,ML/AI Models
92,other455,Relationship enhanced with AI/ML,Grouping data. Generated using deep learning m...,"{'id': 'other', 'name': 'Other'}","{'id': 'other-aiml-data', 'name': 'AI/ML Data'}",EUR,1,TOP2500,1.0,0.6380,...,495,2596,1200,1.6,[],"[{'type': 'discussion', 'title': 'Getting star...",other,Other,other-aiml-data,AI/ML Data
47,model30,EPS Estimate Model,This dataset provides detailed metrics on anal...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-estimates-models', 'name': 'Esti...",EUR,1,TOP2500,1.0,0.7130,...,448,1358,77,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-estimates-models,Estimates Models
115,risk60,Securities Lending Insight Data,"The dataset provides list of metrics, covering...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,1.0,0.9372,...,484,978,4,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",risk,Risk,risk-risk-models,Risk Models
55,model39,Valuation Momentum Data,This dataset integrates two advanced quantitat...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-valuation-models', 'name': 'Valu...",EUR,1,TOP2500,1.0,0.8044,...,285,954,24,1.4,[],"[{'type': 'research', 'title': 'Research Paper...",model,Model,model-valuation-models,Valuation Models
60,news17,PR Edition Data,"This dataset analyzes and structures news, pre...","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",EUR,1,TOP2500,1.0,0.8014,...,214,516,75,1.5,[],"[{'type': 'discussion', 'title': 'Getting star...",news,News,news-news,News
69,news46,Relevant News Analytics Data,This dataset provides a comprehensive mapping ...,"{'id': 'news', 'name': 'News'}","{'id': 'news-news-sentiment', 'name': 'News Se...",EUR,1,TOP2500,1.0,0.9382,...,125,263,30,1.5,[],"[{'type': 'research', 'title': 'Creating D0 Al...",news,News,news-news-sentiment,News Sentiment
46,model28,Structural Credit Risk Model,This dataset provides a comprehensive mapping ...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-risk-based-models', 'name': 'Ris...",EUR,1,TOP2500,1.0,0.8281,...,103,247,43,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-risk-based-models,Risk Based Models
64,news23,MnA Deals Data,This dataset offers detailed information on me...,"{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",EUR,1,TOP2500,1.0,0.4462,...,88,145,136,1.5,[],"[{'type': 'discussion', 'title': 'Getting star...",news,News,news-news,News

In [ ]:
# 특정 dataset_id에 속하는 datafield 스펙 보기
TARGET_DATASET_ID = "analyst39"  # 원하는 dataset id로 변경

# 🔧 REGION / UNIVERSE GLOBALIZED
# Brain API에서 해당 dataset의 datafield 목록 가져오기
datafields_spec = ace.get_datafields(
    s, 
    region=REGION,
    universe=UNIVERSE,
    dataset_id=TARGET_DATASET_ID,
    data_type='ALL'
)

# 표시할 컬럼 선택 (존재하는 컬럼만)
display_cols = ['id', 'description', 'type', 'alphaCount', 'userCount', 'coverage']
display_cols = [col for col in display_cols if col in datafields_spec.columns]

# alphaCount 기준 내림차순 정렬 후 표시
datafields_spec = datafields_spec[display_cols].sort_values(by='alphaCount', ascending=False)
print(f"Dataset: {TARGET_DATASET_ID} | Total datafields: {len(datafields_spec)}")
display(datafields_spec)

Dataset: model25 | Total datafields: 199

,id,description,type,alphaCount,userCount,coverage
193,mdl25_vrv421_71v,FCF Yield (%),MATRIX,1255,330,0.9607
3,mdl25_21v,Earnings Quality by Cash Flow,MATRIX,720,269,0.9339
195,mdl25_vrv421_81v,FCF/EV (%),MATRIX,628,241,0.9386
0,mdl25_01v,Earnings Quality by Accruals - Period End Date,MATRIX,499,141,0.9813
197,mdl25_vrv421_91v,CFO/EV (%),MATRIX,426,172,0.9425
...,...,...,...,...,...,...
141,mdl25_rlevv421_8v,Debt to Equity - 1 Qtr Difference,MATRIX,2,2,0.4622
152,mdl25_rov421_11v,Inv Turnover - 1 Qtr Difference,MATRIX,2,2,0.2799
163,mdl25_rov421_7v,A/R Turnover - 1 Qtr Difference,MATRIX,2,2,0.3473
136,mdl25_rlevv421_11v,(Total Debt - Cash) / EBITDA - Last Qtr,MATRIX,2,2,0.4709
156,mdl25_rov421_31v,Avg Inventory Days - 1 Qtr Difference,MATRIX,1,1,0.2799

# operators_list.json 업데이트
Brain API에서 최신 operator 목록을 가져와서 로컬 파일을 갱신합니다.
Sanity Check에서 사용하는 operators_list.json과 LLM에 전달되는 operator 목록이 일치해야 합니다.

In [ ]:
# ============================================================
# operators_list.json 업데이트 (Brain API → 로컬 파일)
# ============================================================
import json
import ace_lib as ace

# Brain API에서 최신 operator 목록 가져오기
operators_df = ace.get_operators(s)

# REGULAR scope만 필터링 (LLM 프롬프트와 동일하게)
regular_ops = operators_df[operators_df['scope'] == 'REGULAR']

# DataFrame → dict 변환 (name을 key로)
operators_dict = {}
for _, row in regular_ops.iterrows():
    name = row['name']
    
    # input 타입 처리: 리스트나 문자열 모두 문자열로 저장
    input_val = row.get('input', '[]')
    if isinstance(input_val, list):
        input_str = str(input_val)
    else:
        input_str = str(input_val) if input_val else "['MATRIX']"
    
    operators_dict[name] = {
        'name': name,
        'category': row.get('category', ''),
        'scope': 'REGULAR',
        'definition': row.get('definition', ''),
        'description': row.get('description', ''),
        'documentation': row.get('documentation', None),
        'level': row.get('level', 'ALL'),
        'input': input_str,
        'output': row.get('output', 'MATRIX')
    }

# JSON 파일로 저장
output_path = 'operators_list.json'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(operators_dict, f, ensure_ascii=False, indent=4)

print(f"[DONE] operators_list.json 업데이트 완료!")
print(f"  - 총 {len(operators_dict)}개 operator 저장")
print(f"  - 저장 경로: {output_path}")

# 기존에 없던 operator 확인 (디버깅용)
missing_ops = ['zscore', 'reverse', 'quantile', 'ts_quantile', 'ts_ir', 'normalize', 'hump', 'ts_arg_max', 'ts_scale', 'ts_zscore']
print(f"\n[CHECK] 이전에 누락되었던 operator 존재 여부:")
for op in missing_ops:
    status = "✅ 있음" if op in operators_dict else "❌ 없음"
    print(f"  - {op}: {status}")

[DONE] operators_list.json 업데이트 완료!
  - 총 83개 operator 저장
  - 저장 경로: operators_list.json

[CHECK] 이전에 누락되었던 operator 존재 여부:
  - zscore: ✅ 있음
  - reverse: ✅ 있음
  - quantile: ✅ 있음
  - ts_quantile: ✅ 있음
  - ts_ir: ✅ 있음
  - normalize: ✅ 있음
  - hump: ✅ 있음
  - ts_arg_max: ✅ 있음
  - ts_scale: ✅ 있음
  - ts_zscore: ✅ 있음

# Expression Sanity checker
데이터필드 정보를 이용해서, LLM이 만든 expression이 실제 브레인에서 돌아갈 수 있는지를 체크합니다.

In [ ]:
import llm_functions as llm
from parser import *
import ace_lib as ace
import numpy as np
import pandas as pd
import os 
import json
import asyncio



# 🔧 REGION / UNIVERSE GLOBALIZED
datafields = llm.import_json(f'datafield/1/{REGION}/{UNIVERSE}/1_{REGION}_{UNIVERSE}_total.json')
operators = llm.import_json('operators_list.json')

def return_type(node, operators, datafields):
    if node.node_type == 'operator':
        return operators[node.value]['output']

    elif node.node_type == 'number':
        return "NUMBER"

    elif node.node_type == 'datafield':
        if node.value.lower() == 'nan':
            return "MATRIX"
        return datafields[node.value]['type']

    else:
        return "SPECIAL_ARGUMENT"


def check_input(operator_inputs, children_types, _debug = False):
    if _debug: print(operator_inputs)
    while len(operator_inputs) != 0:

        operator_input = operator_inputs.pop(0)
        if _debug: print(f"operator input: {operator_input}, remain inputs: {len(operator_inputs)}" )

        if operator_input == '_SPECIAL_ARGUMENT':
            if len(children_types) == 0:
                pass
            elif children_types[0] == '_SPECIAL_ARGUMENT':
                if _debug: print(operator_input)
                if _debug: print(children_types.pop(0))
            else:
                pass

        else:
            if len(children_types) == 0:
                return False

            children_type = children_types.pop(0)
            if operator_input == "MATRIX" and children_type == "NUMBER":
                pass
            elif operator_input != children_type:
                if _debug: print(operator_input ,children_type, operator_input == children_type)
                return False

    return True


def sanity_checker(exp, _debug=False):

    try:
        exp_tree = tree_node(exp)

        for node in [node for node in exp_tree.collect_all_nodes() if node.node_type == "operator"]:

            if check_input(eval(operators[node.value]['input']), [return_type(x,operators, datafields) for x in node.children]):
                if _debug: print(check_input(eval(operators[node.value]['input']), [return_type(x) for x in node.children]))
            else:
                return False
        if return_type(exp_tree,operators, datafields)=="MATRIX":
            return True

        else:
            return False
    except Exception as e:
        print(f"err: {e}")
        return False

## Sanity check 예시

In [ ]:
sanity_checker('bucket(rank(star_si_country_rank), range="0,100,10")') # 이상한 수식, False

err: 'star_si_country_rank'

c:\Users\user\OneDrive\바탕 화면\WQ-2026-AI-HACKATON\llm_alpha_gen\parser.py:117: FutureWarning: Possible nested set at position 22
  tokens = re.findall(r'\?|\:|[a-zA-Z_]\w*\(|[[a-zA-Z_]\w*|==|&&|\|\||[-+*/()<>=,]|"(?:\\.[^"\\]*)*"|\'(?:\\.[^\'\\]*)*\'|[0-9]*\.?[0-9]+', expression)

False

In [ ]:
sanity_checker('ts_backfill(mdl25_vrv421_71v,60)') # 정상적인 expression, True

err: 'sales'

False

# 탐색 데이터셋 설정
여기서는 데이터셋 카테고리별로 User Count가 가장 높은 순으로 정렬해서 탐색

In [ ]:
#s = ace.start_session()

# 🔧 REGION / UNIVERSE GLOBALIZED - 글로벌 변수 사용
region = REGION
universe = UNIVERSE

datafields = llm.import_json(f'datafield/1/{region}/{universe}/1_{region}_{universe}_total.json')
operators = llm.import_json('operators_list.json')

# ============================================================
# 탐색할 dataset 직접 지정 (하드코딩)
# ============================================================
ALLOWED_DATASETS = [TARGET_DATASET_ID]  # 원하는 dataset id 추가

# Brain API에서 전체 datasets 정보 가져오기 (datasets_dict 구성용)
datasets = ace.get_datasets(s, region=region, universe=universe)
datasets = datasets.drop_duplicates(['id'])

# ALLOWED_DATASETS에 있는 것만 datasets_dict에 포함
datasets_filtered = datasets[datasets['id'].isin(ALLOWED_DATASETS)]
datasets_dict = {row['id']: row.to_dict() for _, row in datasets_filtered.iterrows()}

# datasets_list는 ALLOWED_DATASETS 그대로 사용
datasets_list = ALLOWED_DATASETS

print(f"Exploring datasets: {datasets_list}")

Exploring datasets: ['model25']

## 시뮬레이션 하기에 앞서...
* 저카운트와 필드카운트에 따라 몇번 expression을 생성하고 돌릴지 결정 
* llm으로 만드는 알파들을 따로 json으로 저장
* csv 로드하고 저장하는 함수

In [ ]:
# 유저카운트와 필드카운트로 몇번 expression을 생성하고 돌릴지 결정 
# 한번에 100개씩 generate하니까 10은 알파를 1000개 만들어서 돌리겠다는 뜻
def datset_to_simnum(dataset):
    score = int(np.log10(datasets_dict[dataset]['userCount']+1) + datasets_dict[dataset]['fieldCount'])

    if score <= 3:
        return 1
    elif score <= 10:
        return 2
    elif score <= 50:
        return 3
    elif score <= 100:
        return 10
    else:
        return 20


# llm으로 알파 리스트를 만들면 json도 저장해주기
def get_json_num(dataset):

    json_list = [x for x in os.listdir('./gen_json/') if dataset in x]
    if len(json_list) == 0:
        return 0
    nums = [int(x.split('_')[-1].split('.')[0]) for x in json_list]

    return max(nums)+1

# csv 로드하고 저장하는 함수
def load_csv(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        return pd.DataFrame()
    df = pd.read_csv(path) # index_col=None(기본값): 인덱스 컬럼으로 읽지 않음
    # 과거에 인덱스가 저장되어 있으면 'Unnamed: 0' 같은 컬럼 제거
    df = df.loc[:, ~df.columns.str.match(r'^Unnamed: \d+$')]
    return df

def save_csv(df: pd.DataFrame, path: str) -> None:
    df.to_csv(path, index=False)

def append_and_save_csv(path: str, new_rows: pd.DataFrame) -> pd.DataFrame:
    base = load_csv(path)
    out = pd.concat([base, new_rows], ignore_index=True) # 인덱스 재부여
    save_csv(out, path) # index=False
    return out

In [ ]:
# ============================================================
# Best Alpha 저장 함수
# - 시뮬레이션 결과에서 IS Sharpe가 가장 높은 알파를 good_alpha_list.json에 저장
# ============================================================
from datetime import datetime

def save_best_alpha(sim_results, alpha_expressions, alpha_list, filepath="good_alpha_list.json"):
    """
    시뮬레이션 결과에서 최고 IS Sharpe 알파를 찾아 JSON 파일에 저장
    
    Parameters:
    - sim_results: list of simulation result dicts from ace.multi_simulate_alphas_map
    - alpha_expressions: list of dicts with 'implementation' key (원본 expression)
    - alpha_list: list of alpha payloads with settings
    - filepath: 저장할 JSON 파일 경로
    """
    
    # 유효한 결과만 필터링 (alpha_id와 is_stats 존재 확인)
    valid_results = []
    for i, result in enumerate(sim_results):
        if result is None:
            continue
        if 'id' not in result or not result['id']:
            continue
        
        # is_stats 또는 is 필드에서 sharpe 추출
        is_data = result.get('is', {})
        if not is_data:
            is_data = result.get('is_stats', {})
        
        sharpe = is_data.get('sharpe')
        if sharpe is None:
            continue
        
        valid_results.append({
            'index': i,
            'result': result,
            'sharpe': sharpe
        })
    
    # 유효한 결과가 없으면 경고 출력 후 종료
    if not valid_results:
        print("[WARN] save_best_alpha: No valid results with sharpe found, skipping save")
        return None
    
    # 최고 Sharpe 찾기
    best = max(valid_results, key=lambda x: x['sharpe'])
    best_idx = best['index']
    best_result = best['result']
    
    # Expression 추출 (인덱스 범위 체크)
    if best_idx < len(alpha_expressions):
        expression = alpha_expressions[best_idx].get('implementation', '')
    else:
        expression = best_result.get('regular', {}).get('code', '')
    
    # Settings 추출
    if best_idx < len(alpha_list):
        settings = alpha_list[best_idx].get('settings', {})
    else:
        settings = best_result.get('settings', {})
    
    # is_stats에서 메트릭 추출
    is_data = best_result.get('is', {})
    if not is_data:
        is_data = best_result.get('is_stats', {})
    
    # checks 정보 추출 (PASS/FAIL 리스트)
    checks_raw = is_data.get('checks', [])
    checks_summary = []
    for check in checks_raw:
        if isinstance(check, dict):
            checks_summary.append({
                'name': check.get('name', ''),
                'result': check.get('result', '')
            })
    
    # 저장할 엔트리 구성
    entry = {
        'timestamp': datetime.now().isoformat(),
        'alpha_id': best_result.get('id', ''),
        'expression': expression,
        'is_sharpe': is_data.get('sharpe'),
        'is_fitness': is_data.get('fitness'),
        'is_turnover': is_data.get('turnover'),
        'settings': {
            'region': settings.get('region', ''),
            'universe': settings.get('universe', ''),
            'delay': settings.get('delay'),
            'decay': settings.get('decay'),
            'truncation': settings.get('truncation'),
            'neutralization': settings.get('neutralization', ''),
            'pasteurization': settings.get('pasteurization', ''),
            'nanHandling': settings.get('nanHandling', ''),
            'unitHandling': settings.get('unitHandling', ''),
            'language': settings.get('language', ''),
            'testPeriod': settings.get('testPeriod', ''),
            'visualization': settings.get('visualization', False)
        },
        'checks': checks_summary if checks_summary else None
    }
    
    # 기존 파일 로드 또는 새 리스트 생성
    if os.path.exists(filepath):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
            if not isinstance(data, list):
                data = [data]  # 기존 데이터가 리스트가 아니면 리스트로 변환
        except (json.JSONDecodeError, Exception) as e:
            print(f"[WARN] Could not read existing {filepath}: {e}, creating new list")
            data = []
    else:
        data = []
    
    # 새 엔트리 추가
    data.append(entry)
    
    # 파일 저장 (UTF-8, pretty indent)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"[BEST ALPHA SAVED] Sharpe={entry['is_sharpe']:.4f}, ID={entry['alpha_id']}, File={filepath}")
    
    return entry

# 시뮬레이션 돌리기
* 데이터셋에 따라 정해진 횟수에 맞추어 시뮬레이션 돌리기
* 원한다면 datasets_list를 조작하여 원하는 데이터셋에 맞추어 돌릴 수 있음

In [ ]:
# ============================================================
# 시뮬레이션 돌리기 (Resume 지원 버전)
# - 이미 생성된 gen_json은 스킵하고 부족한 배치만 생성
# - 중간에 끊겨도 다시 실행하면 이어서 진행
# ============================================================
# 🔧 NEW: Top N datafields 설정 - 각 dataset에서 alphaCount 상위 N개만 LLM에 전달
# This restricts the LLM to use only the top N datafields (by alphaCount) within each dataset
TOP_N_DATAFIELDS = 5
# ============================================================

import os
import json
import re

# ------------------------------------------------------------
# Resume 지원 함수들
# ------------------------------------------------------------

def get_existing_json_count(dataset, gen_dir="./gen_json"):
    """
    gen_dir에서 {dataset}_*.json 패턴 파일 개수를 반환
    """
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir, exist_ok=True)
        return 0
    
    pattern = re.compile(rf"^{re.escape(dataset)}_(\d+)\.json$")
    count = 0
    for filename in os.listdir(gen_dir):
        if pattern.match(filename):
            count += 1
    return count


def get_next_json_index(dataset, gen_dir="./gen_json"):
    """
    gen_dir에서 {dataset}_*.json 패턴 파일을 찾고
    가장 큰 k를 계산한 다음 max_k + 1 반환
    파일이 없으면 0 반환
    """
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir, exist_ok=True)
        return 0
    
    pattern = re.compile(rf"^{re.escape(dataset)}_(\d+)\.json$")
    max_k = -1
    
    for filename in os.listdir(gen_dir):
        match = pattern.match(filename)
        if match:
            k = int(match.group(1))
            if k > max_k:
                max_k = k
    
    return max_k + 1


def save_json_safe(data, filepath):
    """
    저장 직전에 파일 존재 여부 체크 (레이스 방지)
    이미 존재하면 저장하지 않고 False 반환
    """
    if os.path.exists(filepath):
        print(f"[WARN] File already exists, skipping: {filepath}")
        return False
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return True


# ------------------------------------------------------------
# 메인 루프 (Resume 지원)
# ------------------------------------------------------------

GEN_DIR = "./gen_json"
os.makedirs(GEN_DIR, exist_ok=True)
print(datasets_list)
print(f"[CONFIG] Using top {TOP_N_DATAFIELDS} datafields per dataset (by alphaCount)")

for dataset in datasets_list:
    
    # 목표 생성 횟수
    target_simnum = datset_to_simnum(dataset)
    
    # 현재 존재하는 파일 개수
    existing_count = get_existing_json_count(dataset, GEN_DIR)
    
    # 남은 생성 횟수
    remaining = target_simnum - existing_count
    
    # 다음 저장할 인덱스
    start_index = get_next_json_index(dataset, GEN_DIR)
    
    # 로그 출력
    print(f"\n{'='*60}")
    print(f"[DATASET] {dataset}")
    print(f"  existing={existing_count}  target={target_simnum}  remaining={remaining}  start_index={start_index}")
    print(f"{'='*60}")
    
    # 이미 완료된 경우 스킵
    if remaining <= 0:
        print(f"[SKIP] dataset={dataset} already complete ({existing_count}/{target_simnum})")
        continue
    
    dataset_category = datasets_dict[dataset]['category_id']
    batch_name = f"{region}_{universe}_{dataset_category}"
    
    # remaining 만큼만 생성
    for i in range(remaining):
        
        current_index = start_index + i
        save_path = f"{GEN_DIR}/{dataset}_{current_index}.json"
        
        # 저장 전 파일 존재 여부 재확인 (레이스 방지)
        if os.path.exists(save_path):
            print(f"[SKIP] {save_path} already exists, skipping this batch")
            continue
        
        print(f"\n--- [{dataset}] Batch {i+1}/{remaining} (index={current_index}) ---")
        print("--- Generating alphas with LLM ---")
        
        try:
            # 🔧 MODIFIED: top_n_datafields 파라미터 추가
            # LLM은 각 dataset에서 alphaCount 상위 N개 datafield만 사용
            response = llm.generate_expressions_from_dataset(
                s, region, universe, dataset, 
                model='gpt-5-mini-2025-08-07', 
                datafields_num_cap=500,
                top_n_datafields=TOP_N_DATAFIELDS  # 🔧 NEW: 상위 N개 datafield만 전달
            )
        except Exception as e:
            print(f"[ERROR] LLM generation failed: {e}")
            continue
        
        print("--- Received response ---")
        
        try:
            json_response = llm.cut_first_to_last_brace(response)
            alphas = json.loads(json_response)
            print(f"--- Alpha generated successfully ---")
        except Exception as e:
            print(f"[ERROR] JSON parsing failed: {e}")
            continue
        
        # JSON 저장 (안전하게)
        if not save_json_safe(alphas, save_path):
            print(f"[WARN] Could not save {save_path}, skipping simulation")
            continue
        
        print(f"[SAVED] {save_path}")
        
        # ------------------------------------------------------------
        # 시뮬레이션 실행
        # ------------------------------------------------------------
        
        # Sanity check로 유효한 알파만 필터링
        alpha_expressions = [
            x for x in alphas.get("results", []) 
            if sanity_checker(x.get('implementation', ''), _debug=False)
        ]
        
        if len(alpha_expressions) == 0:
            print(f"[WARN] No valid alphas after sanity check")
            continue
        
        alpha_list = [
            ace.generate_alpha(
                regular=x['implementation'], 
                region=region, 
                universe=universe, 
                neutralization="INDUSTRY"
            ) 
            for x in alpha_expressions
        ]
        
        len_alpha_list = len(alpha_list)
        print(f"[INFO] eligible_alpha_count: {len_alpha_list}")
        
        tags_list = [
            ['llm_test', f"confidence_{x.get('confidence_level', 0)}"] 
            for x in alpha_expressions
        ]
        descs_list = [x.get('description', '') for x in alpha_expressions]
        
        # 8개씩 배치로 시뮬레이션
        for rep in range(0, len_alpha_list, 8):
            
            # 세션 타임아웃 체크
            if ace.check_session_timeout(s) < 500:
                print("[INFO] Session timeout approaching, refreshing...")
                s = ace.start_session()
            
            batch_end = min(rep + 8, len_alpha_list)
            
            try:
                print(f"--- Simulating alpha batch {rep} to {batch_end} ---")
                
                sim_results = list(
                    ace.multi_simulate_alphas_map(
                        s,
                        alpha_list[rep:batch_end],
                        tags_list[rep:batch_end],
                        descs_list[rep:batch_end],
                        batch_end - rep
                    )
                )
                
                # 🔧 NEW: Best alpha 저장 (배치별 최고 Sharpe 알파)
                save_best_alpha(
                    sim_results,
                    alpha_expressions[rep:batch_end],
                    alpha_list[rep:batch_end],
                    filepath="good_alpha_list.json"
                )
                
                df = pd.DataFrame([
                    ace.flatten_dict(x) 
                    for x in sim_results 
                    if 'id' in x.keys()
                ])
                
                if len(df) > 0:
                    append_and_save_csv(f"./results/{batch_name}.csv", df)
                    print(f"[SAVED] {len(df)} results to ./results/{batch_name}.csv")
                    
            except Exception as e:
                print(f"[ERROR] Simulation failed: {e}")
                continue

print("\n" + "="*60)
print("[DONE] All datasets processed")
print("="*60)

['model25']
[CONFIG] Using top 5 datafields per dataset (by alphaCount)

============================================================
[DATASET] model25
  existing=0  target=20  remaining=20  start_index=0
============================================================

--- [model25] Batch 1/20 (index=0) ---
--- Generating alphas with LLM ---
[INFO] Selected top 5 datafields for dataset 'model25':
  - mdl25_vrv421_71v (alphaCount: 1255, type: MATRIX)
  - mdl25_21v (alphaCount: 720, type: MATRIX)
  - mdl25_vrv421_81v (alphaCount: 628, type: MATRIX)
  - mdl25_01v (alphaCount: 499, type: MATRIX)
  - mdl25_vrv421_91v (alphaCount: 426, type: MATRIX)
{
  "results": [
    {
      "idea": "Cross-sectional quality spread: Earnings Quality (Cash Flow) minus Earnings Quality (Accruals)",
      "description": "I use multiple allowed datafields per SUGGESTION1: mdl25_21v and mdl25_01v. SUGGESTION2 not applicable (no VECTOR fields). SUGGESTION3 not applied because both fields have coverage >0.9. SUGGESTION4 applied: both fields have high userCount/alphaCount so signal likely robust. Kept implementation short per KEEP_IN_MIND1/2 (1 operator, 2 fields). Confidence: 0.72",
      "implementation": "subtract(mdl25_21v, mdl25_01v)",
      "confidence_level": 0.72
    },
    {
      "idea": "FCF yield relative to FCF/EV momentum (z-scored returns)",
      "description": "SUGGESTION1: combine mdl25_vrv421_71v and mdl25_vrv421_81v. SUGGESTION2 not relevant. SUGGESTION3 skipped (coverage high). SUGGESTION4: both fields have high user/alpha counts. KEEP_IN_MIND respected: 2 fields, 3 operators. Confidence: 0.75",
      "implementation": "divide(ts_zscore(mdl25_vrv421_71v, 63), ts_zscore(mdl25_vrv421_81v, 63))",
      "confidence_level": 0.75
    },
    {
      "idea": "CFO/EV momentum minus FCF/EV momentum (time-series z-score spread)",
      "description": "S1: use mdl25_vrv421_91v and mdl25_vrv421_81v. S2 not applicable. S3 not used; coverage >0.9. S4 used higher user/alpha counts where available. KEEP_IN_MIND: simple ops, <=2 fields. Confidence: 0.70",
      "implementation": "subtract(ts_zscore(mdl25_vrv421_91v, 126), ts_zscore(mdl25_vrv421_81v, 126))",
      "confidence_level": 0.7
    },
    {
      "idea": "FCF Yield acceleration: recent returns of FCF Yield",
      "description": "S1: single-field momentum using mdl25_vrv421_71v (still multiple-field suggestion intentionally relaxed because this isolates a clean signal). S2 not applicable. S3 not needed (coverage high). S4 applied by choosing a widely used field. KEEP_IN_MIND: uses 1 field, simple operator. Confidence: 0.65",
      "implementation": "ts_returns(mdl25_vrv421_71v, 20)",
      "confidence_level": 0.65
    },
    {
      "idea": "Earnings Quality (Cash Flow) scaled by FCF/EV to favor profitable free-cash-flow firms",
      "description": "S1: combined mdl25_21v and mdl25_vrv421_81v. S2 not applicable. S3 skipped (coverage high). S4 applied. KEEP_IN_MIND: 2 fields and 2 operators. Confidence: 0.73",
      "implementation": "divide(mdl25_21v, mdl25_vrv421_81v)",
      "confidence_level": 0.73
    },
    {
      "idea": "Accrual-based quality mean-reversion: zscore of Earnings Quality by Accruals",
      "description": "S1 uses mdl25_01v alone to capture accrual distortions. S2 not relevant. S3 not required. S4 field has high coverage but fewer users; still acceptable. KEEP_IN_MIND: 1 field, 1 operator. Confidence: 0.62",
      "implementation": "zscore(mdl25_01v)",
      "confidence_level": 0.62
    },
    {
      "idea": "Information ratio of FCF/EV (time-series IR to find stable cash-generators)",
      "description": "S1: single-field mdl25_vrv421_81v to compute ts_ir. S2 N/A. S3 not used (coverage 0.9386). S4 moderate user/alpha counts considered. KEEP_IN_MIND: short implementation. Confidence: 0.68",
      "implementation": "ts_ir(mdl25_vrv421_81v, 126)",
      "confidence_level": 0.68
    },
    {
      "idea": "FCF Yield minus CFO/EV to detect firms with FCF strength vs CFO",
      "description": "S1: combine mdl25_vrv421_71v and mdl25_vrv421_91v. S2 N/A. S3 skipped (coverage high). S4 applied using popular fields. KEEP_IN_MIND: 2 fields, single subtract. Confidence: 0.71",
      "implementation": "subtract(mdl25_vrv421_71v, mdl25_vrv421_91v)",
      "confidence_level": 0.71
    },
    {
      "idea": "Normalized cross-sectional rank of FCF/EV (favor top quintile)",
      "description": "S1: single-field mdl25_vrv421_81v but using cross-sectional quantile to create buckets. S2 N/A. S3 not needed. S4 applied. KEEP_IN_MIND: 1 field, 1 operator. Confidence: 0.66",
      "implementation": "quantile(mdl25_vrv421_81v)",
      "confidence_level": 0.66
    },
    {
      "idea": "Combine earnings quality (cash flow) z-score with FCF Yield z-score (additive signal)",
      "description": "S1: uses mdl25_21v and mdl25_vrv421_71v to enhance signal. S2 not applicable. S3 not required. S4: chosen fields have good user/alpha counts. KEEP_IN_MIND: 2 fields, 3 operators. Confidence: 0.76",
      "implementation": "add(zscore(mdl25_21v), zscore(mdl25_vrv421_71v))",
      "confidence_level": 0.76
    },
    {
      "idea": "Short-term reversal in CFO/EV (negative recent returns)",
      "description": "S1: single-field mdl25_vrv421_91v to capture short-term mean reversion. S2 not applicable. S3 skipped. S4 used a field with reasonable usage. KEEP_IN_MIND: 1 field, 1 operator. Confidence: 0.60",
      "implementation": "reverse(ts_returns(mdl25_vrv421_91v, 5))",
      "confidence_level": 0.6
    },
    {
      "idea": "Relative quality: Earnings Quality (Cash Flow) / Earnings Quality (Accruals) ratio",
      "description": "S1: uses mdl25_21v and mdl25_01v to compare cash vs accrual quality. S2 N/A. S3 not applied. S4: both fields have high user/alpha counts. KEEP_IN_MIND respected. Confidence: 0.74",
      "implementation": "divide(mdl25_21v, mdl25_01v)",
      "confidence_level": 0.74
    },
    {
      "idea": "Momentum of FCF/EV zscore over medium horizon",
      "description": "S1: single-field mdl25_vrv421_81v preferred for payout-focused firms. S2 N/A. S3 not needed. S4 applied. KEEP_IN_MIND short op. Confidence: 0.67",
      "implementation": "ts_zscore(mdl25_vrv421_81v, 63)",
      "confidence_level": 0.67
    },
    {
      "idea": "FCF Yield scaled by earnings quality to favor high FCF and high quality",
      "description": "S1: combine mdl25_vrv421_71v and mdl25_21v. S2 not applicable. S3 skipped. S4 used high-use fields. KEEP_IN_MIND: 2 fields and 2 ops. Confidence: 0.78",
      "implementation": "multiply(mdl25_vrv421_71v, mdl25_21v)",
      "confidence_level": 0.78
    },
    {
      "idea": "Cross-sectional zscore of (FCF/EV - CFO/EV) to detect firms with free cashflow edge",
      "description": "S1: uses mdl25_vrv421_81v and mdl25_vrv421_91v. S2 N/A. S3 not used. S4 applied. KEEP_IN_MIND: 2 fields, 2 operators. Confidence: 0.73",
      "implementation": "zscore(subtract(mdl25_vrv421_81v, mdl25_vrv421_91v))",
      "confidence_level": 0.73
    },
    {
      "idea": "Time-series mean reversion of earnings accruals (difference from 1-year mean)",
      "description": "S1: single-field mdl25_01v. S2 N/A. S3 not needed (coverage high). S4 considered lower userCount but robust coverage. KEEP_IN_MIND: 1 field, 1 op. Confidence: 0.61",
      "implementation": "ts_av_diff(mdl25_01v, 252)",
      "confidence_level": 0.61
    },
    {
      "idea": "Stable cash flow generators: low ts_std_dev of CFO/EV",
      "description": "S1: use mdl25_vrv421_91v to find firms with stable CFO/EV (low volatility). S2 N/A. S3 not applied. S4 applied. KEEP_IN_MIND: 1 field, 1 operator. Confidence: 0.64",
      "implementation": "ts_std_dev(mdl25_vrv421_91v, 126)",
      "confidence_level": 0.64
    },
    {
      "idea": "FCF Yield growth (delta over 1 year)",
      "description": "S1: single-field mdl25_vrv421_71v to capture improvement in FCF yield. S2 N/A. S3 not needed. S4 used popular FCF Yield field. KEEP_IN_MIND: concise implementation. Confidence: 0.69",
      "implementation": "ts_delta(mdl25_vrv421_71v, 252)",
      "confidence_level": 0.69
    },
    {
      "idea": "Combine CFO/EV IR with Earnings Quality (Cash Flow) z-score",
      "description": "S1: uses mdl25_vrv421_91v and mdl25_21v for complementary signals. S2 N/A. S3 skipped. S4 used fields with decent usage. KEEP_IN_MIND: 2 fields, 2 ops. Confidence: 0.72",
      "implementation": "add(ts_ir(mdl25_vrv421_91v, 126), zscore(mdl25_21v))",
      "confidence_level": 0.72
    },
    {
      "idea": "FCF/EV minus FCF Yield to capture valuation inconsistencies",
      "description": "S1: compare mdl25_vrv421_81v and mdl25_vrv421_71v. S2 N/A. S3 skipped. S4 fields chosen for coverage and relevance. KEEP_IN_MIND: simple subtract. Confidence: 0.68",
      "implementation": "subtract(mdl25_vrv421_81v, mdl25_vrv421_71v)",
      "confidence_level": 0.68
    },
    {
      "idea": "Earnings quality momentum (ts_returns of mdl25_21v)",
      "description": "S1: single-field mdl25_21v to capture changes in cash-flow quality. S2 N/A. S3 not needed. S4 used field with strong alphaCount. KEEP_IN_MIND: short op. Confidence: 0.66",
      "implementation": "ts_returns(mdl25_21v, 63)",
      "confidence_level": 0.66
    },
    {
      "idea": "Cross-sectional normalized sum: zscore(FCF Yield) + zscore(CFO/EV)",
      "description": "S1: combines mdl25_vrv421_71v and mdl25_vrv421_91v. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.74",
      "implementation": "add(zscore(mdl25_vrv421_71v), zscore(mdl25_vrv421_91v))",
      "confidence_level": 0.74
    },
    {
      "idea": "Low volatility FCF/EV and improving earnings quality (multiply stability and quality)",
      "description": "S1: mdl25_vrv421_81v for stability (low ts_std_dev) and mdl25_21v for quality. S2 N/A. S3 skipped. S4 used widely used fields. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.70",
      "implementation": "multiply(inverse(ts_std_dev(mdl25_vrv421_81v, 126)), zscore(mdl25_21v))",
      "confidence_level": 0.7
    },
    {
      "idea": "FCF Yield vs historical median (ts_max_diff variant)",
      "description": "S1: single-field mdl25_vrv421_71v to detect unusually high current FCF yield. S2 N/A. S3 not necessary. S4 chosen for strong alpha history. KEEP_IN_MIND: single field, single op. Confidence: 0.68",
      "implementation": "ts_max_diff(mdl25_vrv421_71v, 252)",
      "confidence_level": 0.68
    },
    {
      "idea": "CF quality divergence: Earnings Quality (Cash Flow) minus FCF Yield (z-scored)",
      "description": "S1: combine mdl25_21v and mdl25_vrv421_71v. S2 N/A. S3 not used. S4 applied. KEEP_IN_MIND: 2 fields, 2 ops. Confidence: 0.73",
      "implementation": "zscore(subtract(mdl25_21v, mdl25_vrv421_71v))",
      "confidence_level": 0.73
    },
    {
      "idea": "Short-term momentum of FCF/EV relative to its 3-month mean",
      "description": "S1: single-field mdl25_vrv421_81v. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: concise op. Confidence: 0.65",
      "implementation": "ts_av_diff(mdl25_vrv421_81v, 63)",
      "confidence_level": 0.65
    },
    {
      "idea": "Earnings accrual shock: recent delta of accruals quality",
      "description": "S1: single-field mdl25_01v to capture sudden accrual changes. S2 N/A. S3 not needed. S4 lower userCount but high coverage. KEEP_IN_MIND: simple. Confidence: 0.59",
      "implementation": "ts_delta(mdl25_01v, 63)",
      "confidence_level": 0.59
    },
    {
      "idea": "Composite safety: average of zscores of FCF Yield, FCF/EV, CFO/EV",
      "description": "S1: combines mdl25_vrv421_71v, mdl25_vrv421_81v, mdl25_vrv421_91v (note KEEP_IN_MIND2 limits to 2 datafields; to comply, I use pairwise average layering: first average 71v & 81v then combine with 91v using add() but still only two original fields in each operator — to strictly keep <=2 datafields per operator we construct as add(zscore(71v), zscore(81v)) then add result with zscore(91v) is 3 fields overall; however KEEP_IN_MIND2 forbids over 2 datafields. Therefore I implement pairwise and choose top two most informative fields to adhere to rules). I applied S1 by selecting the two most used fields (71v and 81v). S2 N/A. S3 skipped. S4 used highest user/alpha counts. Confidence: 0.77",
      "implementation": "add(zscore(mdl25_vrv421_71v), zscore(mdl25_vrv421_81v))",
      "confidence_level": 0.77
    },
    {
      "idea": "FCF Yield relative momentum vs 6-month mean (ts_returns scaled)",
      "description": "S1: mdl25_vrv421_71v used to capture momentum. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: short op. Confidence: 0.66",
      "implementation": "ts_returns(mdl25_vrv421_71v, 126)",
      "confidence_level": 0.66
    },
    {
      "idea": "Quality-adjusted FCF/EV: FCF/EV * Earnings Quality (Cash Flow)",
      "description": "S1: uses mdl25_vrv421_81v and mdl25_21v. S2 N/A. S3 not needed. S4 applied. KEEP_IN_MIND: 2 fields, 1 operator. Confidence: 0.76",
      "implementation": "multiply(mdl25_vrv421_81v, mdl25_21v)",
      "confidence_level": 0.76
    },
    {
      "idea": "Cross-sectional zscore of CFO/EV growth vs FCF/EV growth",
      "description": "S1: compare ts_returns of mdl25_vrv421_91v and mdl25_vrv421_81v. S2 N/A. S3 not needed. S4 used fields with adequate counts. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.69",
      "implementation": "zscore(subtract(ts_returns(mdl25_vrv421_91v, 63), ts_returns(mdl25_vrv421_81v, 63)))",
      "confidence_level": 0.69
    },
    {
      "idea": "Earnings Quality momentum adjusted by accrual volatility",
      "description": "S1: mdl25_21v for quality, mdl25_01v for accrual volatility. S2 N/A. S3 not used. S4 applied. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.71",
      "implementation": "divide(zscore(mdl25_21v), ts_std_dev(mdl25_01v, 126))",
      "confidence_level": 0.71
    },
    {
      "idea": "FCF Yield extremeness: winsorized zscore",
      "description": "S1: single-field mdl25_vrv421_71v. S2 N/A. S3 skip. S4 applied. KEEP_IN_MIND: 1 field and 2 ops. Confidence: 0.67",
      "implementation": "zscore(winsorize(mdl25_vrv421_71v, std=4))",
      "confidence_level": 0.67
    },
    {
      "idea": "FCF/EV information ratio adjusted by recent trend",
      "description": "S1: mdl25_vrv421_81v only (ts_ir and ts_returns combined). S2 N/A. S3 not required. S4 used. KEEP_IN_MIND: 1 field, 2 ops. Confidence: 0.7",
      "implementation": "add(ts_ir(mdl25_vrv421_81v, 126), ts_returns(mdl25_vrv421_81v, 20))",
      "confidence_level": 0.7
    },
    {
      "idea": "CFO/EV cross-sectional rank (group-neutral replacement by zscore)",
      "description": "S1: mdl25_vrv421_91v as a standalone cross-sectional signal. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 1 field, 1 op to keep short. Confidence: 0.65",
      "implementation": "zscore(mdl25_vrv421_91v)",
      "confidence_level": 0.65
    },
    {
      "idea": "Earnings Quality divergence: ts_zscore(cash-flow) minus cross-sectional zscore(accruals)",
      "description": "S1: mdl25_21v and mdl25_01v used. S2 N/A. S3 not used. S4 applied. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.72",
      "implementation": "subtract(ts_zscore(mdl25_21v, 63), zscore(mdl25_01v))",
      "confidence_level": 0.72
    },
    {
      "idea": "Momentum-adjusted FCF Yield: ts_zscore * recent return",
      "description": "S1: mdl25_vrv421_71v only. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 1 field, 2 ops. Confidence: 0.68",
      "implementation": "multiply(ts_zscore(mdl25_vrv421_71v, 63), ts_returns(mdl25_vrv421_71v, 20))",
      "confidence_level": 0.68
    },
    {
      "idea": "FCF/EV stability minus accrual volatility",
      "description": "S1: mdl25_vrv421_81v and mdl25_01v used to penalize high accrual volatility. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.71",
      "implementation": "subtract(inverse(ts_std_dev(mdl25_vrv421_81v, 126)), ts_std_dev(mdl25_01v, 126))",
      "confidence_level": 0.71
    },
    {
      "idea": "Cross-sectional quantile of combined FCF Yield and CFO/EV (sum then quantile)",
      "description": "S1: mdl25_vrv421_71v and mdl25_vrv421_91v. S2 N/A. S3 not needed. S4 used popular fields. KEEP_IN_MIND: 2 fields and 2 ops. Confidence: 0.75",
      "implementation": "quantile(add(mdl25_vrv421_71v, mdl25_vrv421_91v))",
      "confidence_level": 0.75
    },
    {
      "idea": "Earnings Quality stabilization: low ts_count_nans (data reliability) for mdl25_21v",
      "description": "S1: single-field mdl25_21v; ts_count_nans helps measure data robustness (operator available). S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: minimal operators. Confidence: 0.6",
      "implementation": "ts_count_nans(mdl25_21v, 252)",
      "confidence_level": 0.6
    },
    {
      "idea": "FCF Yield relative to its 1-year mean (zscored deviation)",
      "description": "S1: mdl25_vrv421_71v. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: short op. Confidence: 0.69",
      "implementation": "ts_zscore(mdl25_vrv421_71v, 252)",
      "confidence_level": 0.69
    },
    {
      "idea": "Earnings Quality cross-sectional bucketed (top decile) using quantile",
      "description": "S1: mdl25_21v used with quantile to bucket. S2 N/A. S3 not needed. S4 applied. KEEP_IN_MIND: 1 field, 1 op. Confidence: 0.67",
      "implementation": "quantile(mdl25_21v)",
      "confidence_level": 0.67
    },
    {
      "idea": "FCF/EV minus historical median (ts_av_diff with 2-year lookback)",
      "description": "S1: mdl25_vrv421_81v. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 1 field, 1 op. Confidence: 0.68",
      "implementation": "ts_av_diff(mdl25_vrv421_81v, 504)",
      "confidence_level": 0.68
    },
    {
      "idea": "Cross-sectional zscore of (FCF Yield * Earnings Quality) to find high-quality cash generators",
      "description": "S1: combines mdl25_vrv421_71v and mdl25_21v. S2 N/A. S3 not used. S4 applied. KEEP_IN_MIND: 2 fields, 2 ops. Confidence: 0.79",
      "implementation": "zscore(multiply(mdl25_vrv421_71v, mdl25_21v))",
      "confidence_level": 0.79
    },
    {
      "idea": "CFO/EV mean-reversion vs its 3-month peak (ts_arg_max based insight approximated with ts_max_diff)",
      "description": "S1: mdl25_vrv421_91v single-field. S2 N/A. S3 skipped. S4 used field with moderate alphaCount. KEEP_IN_MIND: 1 field, 1 op. Confidence: 0.63",
      "implementation": "ts_max_diff(mdl25_vrv421_91v, 63)",
      "confidence_level": 0.63
    },
    {
      "idea": "Earnings accruals scaled by FCF Yield to punish accrual-driven firms",
      "description": "S1: mdl25_01v and mdl25_vrv421_71v. S2 N/A. S3 not needed. S4 considered both fields. KEEP_IN_MIND: 2 fields, 2 ops. Confidence: 0.7",
      "implementation": "divide(mdl25_01v, mdl25_vrv421_71v)",
      "confidence_level": 0.7
    },
    {
      "idea": "FCF Yield upside capture: ts_arg_max proxy via ts_returns rank (short lookback)",
      "description": "S1: mdl25_vrv421_71v used with ts_returns to identify leaders. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 1 field, 1 op. Confidence: 0.66",
      "implementation": "ts_returns(mdl25_vrv421_71v, 20)",
      "confidence_level": 0.66
    },
    {
      "idea": "Combine FCF/EV IR and FCF Yield zscore (additive composite)",
      "description": "S1: mdl25_vrv421_81v and mdl25_vrv421_71v combined. S2 N/A. S3 not needed. S4 applied. KEEP_IN_MIND: 2 fields, 2 ops. Confidence: 0.74",
      "implementation": "add(ts_ir(mdl25_vrv421_81v, 126), zscore(mdl25_vrv421_71v))",
      "confidence_level": 0.74
    },
    {
      "idea": "Earnings Quality improvement signal: ts_delta of mdl25_21v over 6 months",
      "description": "S1: mdl25_21v single-field momentum in quality. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: short op. Confidence: 0.65",
      "implementation": "ts_delta(mdl25_21v, 126)",
      "confidence_level": 0.65
    },
    {

2026-02-04 15:33:53,709 - ace - ERROR - Simulation failed. {'id': '1rKLd211m4Ai9JRDJEcHYym', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Required attribute "lookback" must have a value', 'location': {'line': 1, 'start': 70, 'end': 97, 'property': 'regular'}}

{'id': 'e78Jj6K6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(divide(mdl25_vrv421_71v, ts_std_dev(mdl25_01v, 63)))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T01:35:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:35:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 8265857, 'bookSize': 20000000, 'longCount': 490, 'shortCount': 740, 'turnover': 0.2136, 'returns': 0.0801, 'drawdown': 0.2043, 'margin': 0.00075, 'sharpe': 0.99, 'fitness': 0.61, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4358114, 'bookSize': 20000000, 'longCount': 605, 'shortCount': 849, 'turnover': 0.0682, 'returns': 0.0422, 'drawdown': 0.3285, 'margin': 0.001239, 'fitness': 0.33, 'sharpe': 0.56}, 'riskNeutralized': {'pnl': 5916207, 'bookSize': 20000000, 'longCount': 490, 'shortCount': 740, 'turnover': 0.2136, 'returns': 0.0573, 'drawdown': 0.1071, 'margin': 0.000537, 'fitness': 0.47, 'sharpe': 0.9}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.99}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.61}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2136}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2136}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499833}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.51, 'value': 0.43}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.86, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'YPwdexml', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_decay_linear(mdl25_vrv421_71v, 63)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T01:35:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:35:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6470391, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 1055, 'turnover': 0.0236, 'returns': 0.0627, 'drawdown': 0.1043, 'margin': 0.00532, 'sharpe': 0.95, 'fitness': 0.67, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4260840, 'bookSize': 20000000, 'longCount': 1024, 'shortCount': 1043, 'turnover': 0.022, 'returns': 0.0413, 'drawdown': 0.1152, 'margin': 0.003747, 'fitness': 0.44, 'sharpe': 0.76}, 'riskNeutralized': {'pnl': 1848645, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 1055, 'turnover': 0.0236, 'returns': 0.0179, 'drawdown': 0.1586, 'margin': 0.00152, 'fitness': 0.13, 'sharpe': 0.34}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.95}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.67}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0236}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0236}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.49, 'value': 0.4}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.65, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'qMkZREzK', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(multiply(reverse(mdl25_01v), ts_zscore(ts_returns(mdl25_vrv421_91v, 63), 63)))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T01:35:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:35:04-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -5773453, 'bookSize': 20000000, 'longCount': 1016, 'shortCount': 950, 'turnover': 0.237, 'returns': -0.0559, 'drawdown': 0.6198, 'margin': -0.000472, 'sharpe': -2.0, 'fitness': -0.97, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2806686, 'bookSize': 20000000, 'longCount': 1022, 'shortCount': 954, 'turnover': 0.0914, 'returns': -0.0272, 'drawdown': 0.2989, 'margin': -0.000595, 'fitness': -0.51, 'sharpe': -1.1}, 'riskNeutralized': {'pnl': -2287436, 'bookSize': 20000000, 'longCount': 1016, 'shortCount': 950, 'turnover': 0.237, 'returns': -0.0222, 'drawdown': 0.2568, 'margin': -0.000187, 'fitness': -0.39, 'sharpe': -1.29}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -2.0}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.97}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.237}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.237}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -1.04, 'value': -1.22}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.09, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'ak23padv', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(divide(mdl25_vrv421_71v, mdl25_vrv421_91v))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T01:35:32-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:35:32-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.57'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1216623, 'bookSize': 20000000, 'longCount': 991, 'shortCount': 1018, 'turnover': 0.0483, 'returns': 0.0118, 'drawdown': 0.3896, 'margin': 0.000488, 'sharpe': 0.11, 'fitness': 0.03, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1246369, 'bookSize': 20000000, 'longCount': 997, 'shortCount': 1020, 'turnover': 0.0354, 'returns': 0.0121, 'drawdown': 0.3829, 'margin': 0.000683, 'fitness': 0.04, 'sharpe': 0.12}, 'riskNeutralized': {'pnl': 470839, 'bookSize': 20000000, 'longCount': 991, 'shortCount': 1018, 'turnover': 0.0483, 'returns': 0.0046, 'drawdown': 0.3795, 'margin': 0.000189, 'fitness': 0.01, 'sharpe': 0.05}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.11}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.03}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0483}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0483}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2022-11-18', 'limit': 0.1, 'value': 0.320999}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.06, 'value': 0.48}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.39, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'j2lQ7a3k', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(subtract(mdl25_vrv421_91v, mdl25_vrv421_71v))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T01:35:34-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:35:34-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -6111253, 'bookSize': 20000000, 'longCount': 855, 'shortCount': 1154, 'turnover': 0.1908, 'returns': -0.0592, 'drawdown': 0.6371, 'margin': -0.000621, 'sharpe': -0.64, 'fitness': -0.36, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -4430445, 'bookSize': 20000000, 'longCount': 873, 'shortCount': 1145, 'turnover': 0.0528, 'returns': -0.0429, 'drawdown': 0.4787, 'margin': -0.001626, 'fitness': -0.31, 'sharpe': -0.53}, 'riskNeutralized': {'pnl': -4273823, 'bookSize': 20000000, 'longCount': 855, 'shortCount': 1154, 'turnover': 0.1908, 'returns': -0.0414, 'drawdown': 0.4364, 'margin': -0.000434, 'fitness': -0.27, 'sharpe': -0.57}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.64}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.36}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1908}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1908}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499949}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.33, 'value': -0.48}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.13, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '3qYWNGp6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(mdl25_21v)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T01:35:47-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:35:47-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7770304, 'bookSize': 20000000, 'longCount': 1079, 'shortCount': 910, 'turnover': 0.0208, 'returns': 0.0753, 'drawdown': 0.1047, 'margin': 0.007249, 'sharpe': 2.02, 'fitness': 1.57, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 7042850, 'bookSize': 20000000, 'longCount': 1059, 'shortCount': 936, 'turnover': 0.0169, 'returns': 0.0682, 'drawdown': 0.103, 'margin': 0.008076, 'fitness': 1.37, 'sharpe': 1.85}, 'riskNeutralized': {'pnl': 2701785, 'bookSize': 20000000, 'longCount': 1079, 'shortCount': 910, 'turnover': 0.0208, 'returns': 0.0262, 'drawdown': 0.0432, 'margin': 0.002521, 'fitness': 0.66, 'sharpe': 1.45}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.02}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.57}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0208}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0208}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.05, 'value': 0.91}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.65, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 15:44:12,803 - ace - ERROR - Simulation failed. {'id': '3yPdhL4f05gRaKvfEPJkyoA', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'N1WoYLYe', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_delta(mdl25_vrv421_71v, 21), 21)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T01:45:22-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:45:23-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2710618, 'bookSize': 20000000, 'longCount': 1029, 'shortCount': 1023, 'turnover': 0.4311, 'returns': 0.0263, 'drawdown': 0.0625, 'margin': 0.000122, 'sharpe': 1.05, 'fitness': 0.26, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1189350, 'bookSize': 20000000, 'longCount': 1023, 'shortCount': 1035, 'turnover': 0.1416, 'returns': 0.0115, 'drawdown': 0.0586, 'margin': 0.000163, 'fitness': 0.14, 'sharpe': 0.49}, 'riskNeutralized': {'pnl': 329956, 'bookSize': 20000000, 'longCount': 1029, 'shortCount': 1023, 'turnover': 0.4311, 'returns': 0.0032, 'drawdown': 0.0895, 'margin': 1.5e-05, 'fitness': 0.02, 'sharpe': 0.19}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'WARNING', 'limit': 1.58, 'value': 1.05}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.26}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4311}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4311}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.55, 'value': 0.73}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': -0.07, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'bl23erAp', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(multiply(mdl25_vrv421_71v, ts_zscore(ts_returns(mdl25_01v, 63), 63)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T01:45:31-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:45:31-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.74'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1381518, 'bookSize': 20000000, 'longCount': 960, 'shortCount': 886, 'turnover': 0.2344, 'returns': 0.0134, 'drawdown': 0.1685, 'margin': 0.000114, 'sharpe': 0.17, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3442479, 'bookSize': 20000000, 'longCount': 942, 'shortCount': 953, 'turnover': 0.0876, 'returns': 0.0334, 'drawdown': 0.1283, 'margin': 0.000762, 'fitness': 0.24, 'sharpe': 0.47}, 'riskNeutralized': {'pnl': 883778, 'bookSize': 20000000, 'longCount': 960, 'shortCount': 886, 'turnover': 0.2344, 'returns': 0.0086, 'drawdown': 0.1472, 'margin': 7.3e-05, 'fitness': 0.03, 'sharpe': 0.14}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.17}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2344}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2344}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499999}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.09, 'value': -0.06}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.55, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qVemb5', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'divide(ts_zscore(ts_returns(mdl25_vrv421_81v, 63), 63), ts_std_dev(ts_returns(mdl25_vrv421_81v, 63), 63))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T01:45:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:45:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 4273110, 'bookSize': 20000000, 'longCount': 940, 'shortCount': 1035, 'turnover': 0.3759, 'returns': 0.0414, 'drawdown': 0.0469, 'margin': 0.00022, 'sharpe': 1.29, 'fitness': 0.43, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 521224, 'bookSize': 20000000, 'longCount': 940, 'shortCount': 1042, 'turnover': 0.1117, 'returns': 0.0051, 'drawdown': 0.0816, 'margin': 9e-05, 'fitness': 0.03, 'sharpe': 0.17}, 'riskNeutralized': {'pnl': 1904784, 'bookSize': 20000000, 'longCount': 940, 'shortCount': 1035, 'turnover': 0.3759, 'returns': 0.0185, 'drawdown': 0.0418, 'margin': 9.8e-05, 'fitness': 0.17, 'sharpe': 0.77}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'WARNING', 'limit': 1.58, 'value': 1.29}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.43}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3759}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3759}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING', 'date': '2014-12-15', 'limit': 0.1, 'value': 0.145875}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.67, 'value': 1.03}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': -0.03, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'LLbx0zxM', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(sqrt(multiply(mdl25_vrv421_71v, mdl25_vrv421_91v)))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T01:45:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:45:36-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3257540, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 1153, 'turnover': 0.0824, 'returns': 0.0316, 'drawdown': 0.1504, 'margin': 0.000767, 'sharpe': 0.47, 'fitness': 0.24, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -970706, 'bookSize': 20000000, 'longCount': 692, 'shortCount': 1136, 'turnover': 0.0338, 'returns': -0.0094, 'drawdown': 0.2817, 'margin': -0.000557, 'fitness': -0.04, 'sharpe': -0.15}, 'riskNeutralized': {'pnl': 1498802, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 1153, 'turnover': 0.0824, 'returns': 0.0145, 'drawdown': 0.0709, 'margin': 0.000353, 'fitness': 0.12, 'sharpe': 0.34}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.47}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.24}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0824}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0824}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499989}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.24, 'value': 0.38}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.61, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YV5r3VW', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'if_else(greater(ts_zscore(ts_returns(mdl25_01v, 63), 63), 0), ts_zscore(ts_returns(mdl25_vrv421_91v, 63), 63), 0)', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-04T01:46:49-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:46:50-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5890930, 'bookSize': 20000000, 'longCount': 890, 'shortCount': 925, 'turnover': 0.2599, 'returns': 0.0571, 'drawdown': 0.0463, 'margin': 0.000439, 'sharpe': 1.84, 'fitness': 0.86, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1479930, 'bookSize': 20000000, 'longCount': 926, 'shortCount': 949, 'turnover': 0.0931, 'returns': 0.0143, 'drawdown': 0.0872, 'margin': 0.000308, 'fitness': 0.17, 'sharpe': 0.51}, 'riskNeutralized': {'pnl': 2995728, 'bookSize': 20000000, 'longCount': 890, 'shortCount': 925, 'turnover': 0.2599, 'returns': 0.029, 'drawdown': 0.036, 'margin': 0.000223, 'fitness': 0.44, 'sharpe': 1.32}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.84}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.86}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2599}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2599}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.96, 'value': 0.95}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.18, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 15:49:57,482 - ace - ERROR - Simulation failed. {'id': '4kHdO84pL4ON8YO5Iq880It', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Incompatible unit for input of "multiply" at index 0, expected "Unit[]", found "Unit[Group:1]"', 'location': {'property': 'regular'}}

{'id': 'xAwMKelW', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_quantile(mdl25_21v, 252)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T01:51:10-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:51:11-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3425131, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 983, 'turnover': 0.0852, 'returns': 0.0332, 'drawdown': 0.0366, 'margin': 0.00078, 'sharpe': 1.42, 'fitness': 0.73, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2614051, 'bookSize': 20000000, 'longCount': 1009, 'shortCount': 985, 'turnover': 0.044, 'returns': 0.0253, 'drawdown': 0.0551, 'margin': 0.001152, 'fitness': 0.49, 'sharpe': 1.08}, 'riskNeutralized': {'pnl': 1605132, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 983, 'turnover': 0.0852, 'returns': 0.0156, 'drawdown': 0.0529, 'margin': 0.000365, 'fitness': 0.34, 'sharpe': 0.96}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'WARNING', 'limit': 1.58, 'value': 1.42}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.73}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0852}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0852}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.74, 'value': 0.87}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 0.78, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZLg2Ze', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(subtract(mdl25_vrv421_81v, mdl25_01v))', 'description': 'Core: prefer high FCF/EV and low accruals risk; subtract accruals quality from FCF/EV. Two fields used. SUGGESTION1 applied. Confidence: 0.70', 'operatorCount': 2}, 'dateCreated': '2026-02-04T01:32:16-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:32:26-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 936720, 'bookSize': 20000000, 'longCount': 636, 'shortCount': 1355, 'turnover': 0.0601, 'returns': 0.0091, 'drawdown': 0.1506, 'margin': 0.000302, 'sharpe': 0.21, 'fitness': 0.06, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -851886, 'bookSize': 20000000, 'longCount': 714, 'shortCount': 1291, 'turnover': 0.0416, 'returns': -0.0083, 'drawdown': 0.2482, 'margin': -0.000397, 'fitness': -0.05, 'sharpe': -0.19}, 'riskNeutralized': {'pnl': 1682037, 'bookSize': 20000000, 'longCount': 636, 'shortCount': 1355, 'turnover': 0.0601, 'returns': 0.0163, 'drawdown': 0.0801, 'margin': 0.000542, 'fitness': 0.21, 'sharpe': 0.57}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.21}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.06}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0601}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0601}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.11, 'value': 0.21}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.41, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qOkdgv', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(subtract(mdl25_vrv421_71v, mdl25_vrv421_91v))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T01:51:32-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:51:33-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6111253, 'bookSize': 20000000, 'longCount': 1154, 'shortCount': 855, 'turnover': 0.1908, 'returns': 0.0592, 'drawdown': 0.1519, 'margin': 0.000621, 'sharpe': 0.64, 'fitness': 0.36, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4430445, 'bookSize': 20000000, 'longCount': 1145, 'shortCount': 873, 'turnover': 0.0528, 'returns': 0.0429, 'drawdown': 0.1717, 'margin': 0.001626, 'fitness': 0.31, 'sharpe': 0.53}, 'riskNeutralized': {'pnl': 4273823, 'bookSize': 20000000, 'longCount': 1154, 'shortCount': 855, 'turnover': 0.1908, 'returns': 0.0414, 'drawdown': 0.2034, 'margin': 0.000434, 'fitness': 0.27, 'sharpe': 0.57}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.64}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.36}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1908}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1908}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499949}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.33, 'value': 0.48}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.13, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Xgwqj8R8', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(ts_returns(mdl25_vrv421_91v, 63), 63), ts_zscore(ts_returns(mdl25_vrv421_81v, 63), 63))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T01:52:13-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:52:14-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.74'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1083550, 'bookSize': 20000000, 'longCount': 689, 'shortCount': 1285, 'turnover': 0.4772, 'returns': 0.0105, 'drawdown': 0.1117, 'margin': 4.4e-05, 'sharpe': 0.31, 'fitness': 0.05, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -681978, 'bookSize': 20000000, 'longCount': 768, 'shortCount': 1215, 'turnover': 0.1279, 'returns': -0.0066, 'drawdown': 0.1382, 'margin': -0.000103, 'fitness': -0.04, 'sharpe': -0.18}, 'riskNeutralized': {'pnl': 248596, 'bookSize': 20000000, 'longCount': 689, 'shortCount': 1285, 'turnover': 0.4772, 'returns': 0.0024, 'drawdown': 0.0963, 'margin': 1e-05, 'fitness': 0.01, 'sharpe': 0.09}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.31}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.05}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4772}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4772}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.16, 'value': 0.03}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.57, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'e78AlxvJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(winsorize(mdl25_vrv421_91v, std=4))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T01:52:15-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:52:16-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5861596, 'bookSize': 20000000, 'longCount': 897, 'shortCount': 1113, 'turnover': 0.1443, 'returns': 0.0568, 'drawdown': 0.0694, 'margin': 0.000787, 'sharpe': 1.09, 'fitness': 0.68, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4594113, 'bookSize': 20000000, 'longCount': 902, 'shortCount': 1116, 'turnover': 0.0451, 'returns': 0.0445, 'drawdown': 0.1235, 'margin': 0.001976, 'fitness': 0.55, 'sharpe': 0.92}, 'riskNeutralized': {'pnl': 3003487, 'bookSize': 20000000, 'longCount': 897, 'shortCount': 1113, 'turnover': 0.1443, 'returns': 0.0291, 'drawdown': 0.0536, 'margin': 0.000403, 'fitness': 0.34, 'sharpe': 0.75}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 1.09}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.68}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1443}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1443}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499644}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.57, 'value': 0.46}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.2, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 16:09:34,929 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': 'wpwVkg51', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'add(zscore(mdl25_vrv421_71v), zscore(mdl25_vrv421_91v))', 'description': 'S1: combines mdl25_vrv421_71v and mdl25_vrv421_91v. S2 N/A. S3 skipped. S4 applied. KEEP_IN_MIND: 2 fields, 3 ops. Confidence: 0.74', 'operatorCount': 3}, 'dateCreated': '2026-02-04T01:02:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:02:43-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.76'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6698760, 'bookSize': 20000000, 'longCount': 956, 'shortCount': 1054, 'turnover': 0.1396, 'returns': 0.0649, 'drawdown': 0.1121, 'margin': 0.00093, 'sharpe': 0.93, 'fitness': 0.63, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3932619, 'bookSize': 20000000, 'longCount': 961, 'shortCount': 1057, 'turnover': 0.0448, 'returns': 0.0381, 'drawdown': 0.1355, 'margin': 0.0017, 'fitness': 0.33, 'sharpe': 0.59}, 'riskNeutralized': {'pnl': 2963055, 'bookSize': 20000000, 'longCount': 956, 'shortCount': 1054, 'turnover': 0.1396, 'returns': 0.0287, 'drawdown': 0.109, 'margin': 0.000411, 'fitness': 0.26, 'sharpe': 0.58}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.93}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.63}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1396}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1396}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499978}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.48, 'value': 0.64}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.81, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E503OEmK', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(divide(ts_returns(mdl25_vrv421_71v,10), ts_returns(mdl25_vrv421_81v,10)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T02:10:52-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:10:53-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -2538025, 'bookSize': 20000000, 'longCount': 729, 'shortCount': 1241, 'turnover': 0.3759, 'returns': -0.0246, 'drawdown': 0.407, 'margin': -0.000131, 'sharpe': -0.27, 'fitness': -0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1444601, 'bookSize': 20000000, 'longCount': 774, 'shortCount': 1229, 'turnover': 0.0796, 'returns': -0.014, 'drawdown': 0.2714, 'margin': -0.000352, 'fitness': -0.05, 'sharpe': -0.15}, 'riskNeutralized': {'pnl': -3791670, 'bookSize': 20000000, 'longCount': 729, 'shortCount': 1241, 'turnover': 0.3759, 'returns': -0.0367, 'drawdown': 0.4489, 'margin': -0.000195, 'fitness': -0.18, 'sharpe': -0.59}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.27}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3759}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3759}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2020-03-31', 'limit': 0.1, 'value': 0.461067}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.14, 'value': -0.2}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.74, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'xAwMOk3J', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'divide(add(zscore(mdl25_vrv421_71v), zscore(mdl25_21v)), 2)', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T02:10:51-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:10:52-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.77'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7870253, 'bookSize': 20000000, 'longCount': 1106, 'shortCount': 875, 'turnover': 0.029, 'returns': 0.0763, 'drawdown': 0.0753, 'margin': 0.005256, 'sharpe': 1.8, 'fitness': 1.41, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 6743413, 'bookSize': 20000000, 'longCount': 1093, 'shortCount': 896, 'turnover': 0.0211, 'returns': 0.0653, 'drawdown': 0.0996, 'margin': 0.006197, 'fitness': 1.19, 'sharpe': 1.65}, 'riskNeutralized': {'pnl': 3060584, 'bookSize': 20000000, 'longCount': 1106, 'shortCount': 875, 'turnover': 0.029, 'returns': 0.0297, 'drawdown': 0.0439, 'margin': 0.002044, 'fitness': 0.58, 'sharpe': 1.18}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.8}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.41}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.029}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.029}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.94, 'value': 0.88}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.99, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Vkwn132w', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_delta(mdl25_21v,10),20)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T02:11:01-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:11:01-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1371262, 'bookSize': 20000000, 'longCount': 564, 'shortCount': 578, 'turnover': 0.5298, 'returns': 0.0133, 'drawdown': 0.1045, 'margin': 5e-05, 'sharpe': 0.51, 'fitness': 0.08, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1527291, 'bookSize': 20000000, 'longCount': 664, 'shortCount': 716, 'turnover': 0.1384, 'returns': -0.0148, 'drawdown': 0.1863, 'margin': -0.000214, 'fitness': -0.17, 'sharpe': -0.52}, 'riskNeutralized': {'pnl': 1853700, 'bookSize': 20000000, 'longCount': 564, 'shortCount': 578, 'turnover': 0.5298, 'returns': 0.018, 'drawdown': 0.0662, 'margin': 6.8e-05, 'fitness': 0.14, 'sharpe': 0.78}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.51}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.08}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5298}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5298}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.27, 'value': 0.29}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.66, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '78qO7zY5', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'quantile(mdl25_vrv421_71v)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:11:19-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:11:19-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7499117, 'bookSize': 20000000, 'longCount': 1050, 'shortCount': 1012, 'turnover': 0.0289, 'returns': 0.0727, 'drawdown': 0.0554, 'margin': 0.005027, 'sharpe': 2.34, 'fitness': 1.78, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 6481293, 'bookSize': 20000000, 'longCount': 1046, 'shortCount': 1022, 'turnover': 0.0212, 'returns': 0.0628, 'drawdown': 0.0612, 'margin': 0.005923, 'fitness': 1.4, 'sharpe': 1.97}, 'riskNeutralized': {'pnl': 3221837, 'bookSize': 20000000, 'longCount': 1050, 'shortCount': 1012, 'turnover': 0.0289, 'returns': 0.0312, 'drawdown': 0.0145, 'margin': 0.00216, 'fitness': 0.88, 'sharpe': 1.77}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.34}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.78}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0289}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0289}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.22, 'value': 1.12}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 2.67, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'vRn0wjQb', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_kurtosis(mdl25_21v,60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:11:36-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:11:37-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.55'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -2498891, 'bookSize': 20000000, 'longCount': 271, 'shortCount': 1215, 'turnover': 0.4713, 'returns': -0.0242, 'drawdown': 0.3244, 'margin': -0.000103, 'sharpe': -0.49, 'fitness': -0.11, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -3929065, 'bookSize': 20000000, 'longCount': 393, 'shortCount': 1284, 'turnover': 0.1038, 'returns': -0.0381, 'drawdown': 0.405, 'margin': -0.000734, 'fitness': -0.38, 'sharpe': -0.69}, 'riskNeutralized': {'pnl': -823887, 'bookSize': 20000000, 'longCount': 271, 'shortCount': 1215, 'turnover': 0.4713, 'returns': -0.008, 'drawdown': 0.205, 'margin': -3.4e-05, 'fitness': -0.02, 'sharpe': -0.19}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.49}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.11}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4713}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4713}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.25, 'value': 0.01}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.0, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 16:12:17,056 - ace - WARNING - Simulation failed. {"detail":"CONCURRENT_SIMULATION_LIMIT_EXCEEDED"}, Status code: 429

{'id': 'bl2pGr9Z', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_count_nans(mdl25_vrv421_81v,60))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T02:13:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:13:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.52'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1134651, 'bookSize': 20000000, 'longCount': 1973, 'shortCount': 824, 'turnover': 0.0122, 'returns': -0.011, 'drawdown': 0.1616, 'margin': -0.0018, 'sharpe': -0.32, 'fitness': -0.09, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1202407, 'bookSize': 20000000, 'longCount': 1967, 'shortCount': 853, 'turnover': 0.0121, 'returns': -0.0117, 'drawdown': 0.1633, 'margin': -0.001924, 'fitness': -0.1, 'sharpe': -0.34}, 'riskNeutralized': {'pnl': -423070, 'bookSize': 20000000, 'longCount': 1973, 'shortCount': 824, 'turnover': 0.0122, 'returns': -0.0041, 'drawdown': 0.0523, 'margin': -0.000671, 'fitness': -0.05, 'sharpe': -0.28}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.32}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.09}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0122}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0122}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.17, 'value': -0.54}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.27, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'omw28Jl6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_covariance(mdl25_vrv421_71v, mdl25_vrv421_91v,60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:13:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:13:31-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.59'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 12153849, 'bookSize': 20000000, 'longCount': 359, 'shortCount': 1663, 'turnover': 0.0762, 'returns': 0.1178, 'drawdown': 0.4096, 'margin': 0.00309, 'sharpe': 0.59, 'fitness': 0.57, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1455596, 'bookSize': 20000000, 'longCount': 618, 'shortCount': 1410, 'turnover': 0.0478, 'returns': 0.0141, 'drawdown': 0.3919, 'margin': 0.000591, 'fitness': 0.03, 'sharpe': 0.09}, 'riskNeutralized': {'pnl': 3297782, 'bookSize': 20000000, 'longCount': 359, 'shortCount': 1663, 'turnover': 0.0762, 'returns': 0.032, 'drawdown': 0.4589, 'margin': 0.000838, 'fitness': 0.1, 'sharpe': 0.19}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.59}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.57}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0762}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0762}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-12-29', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.31, 'value': 0.31}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.45, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZXjlwo', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_rank(mdl25_vrv421_81v,20)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:13:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:13:36-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5862230, 'bookSize': 20000000, 'longCount': 992, 'shortCount': 1011, 'turnover': 0.4402, 'returns': 0.0568, 'drawdown': 0.0329, 'margin': 0.000258, 'sharpe': 2.12, 'fitness': 0.76, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3643453, 'bookSize': 20000000, 'longCount': 987, 'shortCount': 1029, 'turnover': 0.1322, 'returns': 0.0353, 'drawdown': 0.0732, 'margin': 0.000534, 'fitness': 0.74, 'sharpe': 1.44}, 'riskNeutralized': {'pnl': 2008604, 'bookSize': 20000000, 'longCount': 992, 'shortCount': 1011, 'turnover': 0.4402, 'returns': 0.0195, 'drawdown': 0.0334, 'margin': 8.8e-05, 'fitness': 0.25, 'sharpe': 1.18}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.12}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.76}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4402}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4402}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 1.1, 'value': 1.1}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 2.21, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'O0weQM2J', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(divide(mdl25_21v, mdl25_vrv421_71v))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T02:13:34-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:13:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -161487, 'bookSize': 20000000, 'longCount': 918, 'shortCount': 1064, 'turnover': 0.0524, 'returns': -0.0016, 'drawdown': 0.2751, 'margin': -6e-05, 'sharpe': -0.02, 'fitness': -0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2999207, 'bookSize': 20000000, 'longCount': 903, 'shortCount': 1085, 'turnover': 0.0353, 'returns': -0.0291, 'drawdown': 0.4565, 'margin': -0.001647, 'fitness': -0.18, 'sharpe': -0.37}, 'riskNeutralized': {'pnl': 20846, 'bookSize': 20000000, 'longCount': 918, 'shortCount': 1064, 'turnover': 0.0524, 'returns': 0.0002, 'drawdown': 0.2802, 'margin': 8e-06, 'fitness': 0.0, 'sharpe': 0.0}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.02}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0524}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0524}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2015-04-08', 'limit': 0.1, 'value': 0.160802}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.01, 'value': -0.17}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.06, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Gr0V1xgx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(subtract(ts_delta(mdl25_21v,10), ts_delta(mdl25_01v,10)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T02:14:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:14:01-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2778583, 'bookSize': 20000000, 'longCount': 1611, 'shortCount': 321, 'turnover': 0.2924, 'returns': 0.0269, 'drawdown': 0.1203, 'margin': 0.000184, 'sharpe': 0.47, 'fitness': 0.14, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 997598, 'bookSize': 20000000, 'longCount': 1542, 'shortCount': 446, 'turnover': 0.1169, 'returns': 0.0097, 'drawdown': 0.2646, 'margin': 0.000165, 'fitness': 0.04, 'sharpe': 0.14}, 'riskNeutralized': {'pnl': 2310649, 'bookSize': 20000000, 'longCount': 1611, 'shortCount': 321, 'turnover': 0.2924, 'returns': 0.0224, 'drawdown': 0.1139, 'margin': 0.000153, 'fitness': 0.12, 'sharpe': 0.45}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.47}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.14}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2924}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2924}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.24, 'value': -0.04}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.15, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'pwJ0YZvx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_regression(mdl25_21v, mdl25_vrv421_71v,60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:14:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:14:01-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1237496, 'bookSize': 20000000, 'longCount': 1122, 'shortCount': 869, 'turnover': 0.2976, 'returns': 0.012, 'drawdown': 0.1692, 'margin': 8.1e-05, 'sharpe': 0.2, 'fitness': 0.04, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1757952, 'bookSize': 20000000, 'longCount': 1149, 'shortCount': 850, 'turnover': 0.0967, 'returns': -0.017, 'drawdown': 0.2412, 'margin': -0.000352, 'fitness': -0.1, 'sharpe': -0.26}, 'riskNeutralized': {'pnl': 3171318, 'bookSize': 20000000, 'longCount': 1122, 'shortCount': 869, 'turnover': 0.2976, 'returns': 0.0307, 'drawdown': 0.1328, 'margin': 0.000207, 'fitness': 0.19, 'sharpe': 0.59}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.2}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.04}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2976}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2976}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2021-12-23', 'limit': 0.1, 'value': 0.169582}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.1, 'value': 0.2}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.36, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 16:14:13,645 - ace - ERROR - Simulation failed. {'id': '3teICyh0t4NCb60w7VukJGR', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Got invalid value for attribute "lookback", must be constant or string', 'location': {'line': 1, 'start': 0, 'end': 74, 'property': 'regular'}}

{'id': 'd58qkMPv', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_ir(mdl25_21v,30)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:15:24-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:15:24-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5450851, 'bookSize': 20000000, 'longCount': 504, 'shortCount': 642, 'turnover': 0.271, 'returns': 0.0528, 'drawdown': 0.0346, 'margin': 0.00039, 'sharpe': 1.64, 'fitness': 0.72, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4165499, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 777, 'turnover': 0.0888, 'returns': 0.0404, 'drawdown': 0.0882, 'margin': 0.000909, 'fitness': 0.71, 'sharpe': 1.25}, 'riskNeutralized': {'pnl': 2534997, 'bookSize': 20000000, 'longCount': 504, 'shortCount': 642, 'turnover': 0.271, 'returns': 0.0246, 'drawdown': 0.0325, 'margin': 0.000181, 'fitness': 0.3, 'sharpe': 1.01}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.64}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.72}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.271}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.271}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.85, 'value': 0.78}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 2.06, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'kqkREw9K', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'normalize(divide(add(mdl25_vrv421_91v, mdl25_vrv421_81v),2))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T02:15:24-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:15:24-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.74'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3780182, 'bookSize': 20000000, 'longCount': 947, 'shortCount': 1063, 'turnover': 0.1847, 'returns': 0.0366, 'drawdown': 0.1267, 'margin': 0.000397, 'sharpe': 0.48, 'fitness': 0.21, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2452334, 'bookSize': 20000000, 'longCount': 951, 'shortCount': 1067, 'turnover': 0.0508, 'returns': 0.0238, 'drawdown': 0.1707, 'margin': 0.000936, 'fitness': 0.16, 'sharpe': 0.36}, 'riskNeutralized': {'pnl': 1297066, 'bookSize': 20000000, 'longCount': 947, 'shortCount': 1063, 'turnover': 0.1847, 'returns': 0.0126, 'drawdown': 0.1313, 'margin': 0.000136, 'fitness': 0.05, 'sharpe': 0.2}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.48}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.21}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1847}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1847}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499973}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.25, 'value': 0.23}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.25, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'LLbeVQg2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(divide(mdl25_vrv421_81v, ts_std_dev(mdl25_vrv421_81v,20)))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T02:15:31-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:15:32-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3107392, 'bookSize': 20000000, 'longCount': 951, 'shortCount': 1052, 'turnover': 0.1355, 'returns': 0.0301, 'drawdown': 0.1098, 'margin': 0.000444, 'sharpe': 0.7, 'fitness': 0.33, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3038801, 'bookSize': 20000000, 'longCount': 998, 'shortCount': 1015, 'turnover': 0.0691, 'returns': 0.0294, 'drawdown': 0.1002, 'margin': 0.000853, 'fitness': 0.34, 'sharpe': 0.71}, 'riskNeutralized': {'pnl': 827525, 'bookSize': 20000000, 'longCount': 951, 'shortCount': 1052, 'turnover': 0.1355, 'returns': 0.008, 'drawdown': 0.0599, 'margin': 0.000118, 'fitness': 0.07, 'sharpe': 0.3}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.7}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.33}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1355}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1355}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.36, 'value': 0.26}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.96, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'npk0xEq3', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(subtract(ts_mean(mdl25_vrv421_71v,60), ts_mean(mdl25_vrv421_81v,60)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T02:15:36-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:15:37-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7082696, 'bookSize': 20000000, 'longCount': 936, 'shortCount': 1087, 'turnover': 0.0532, 'returns': 0.0686, 'drawdown': 0.2999, 'margin': 0.002581, 'sharpe': 0.54, 'fitness': 0.4, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3852906, 'bookSize': 20000000, 'longCount': 994, 'shortCount': 1036, 'turnover': 0.0376, 'returns': 0.0373, 'drawdown': 0.3005, 'margin': 0.001985, 'fitness': 0.2, 'sharpe': 0.36}, 'riskNeutralized': {'pnl': 4936699, 'bookSize': 20000000, 'longCount': 936, 'shortCount': 1087, 'turnover': 0.0532, 'returns': 0.0478, 'drawdown': 0.2039, 'margin': 0.001799, 'fitness': 0.28, 'sharpe': 0.46}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.54}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.4}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0532}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0532}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.497588}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.28, 'value': 0.38}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.79, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVvkMPQ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(zscore(mdl25_21v), zscore(mdl25_01v))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T02:15:36-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:15:37-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6040264, 'bookSize': 20000000, 'longCount': 966, 'shortCount': 1020, 'turnover': 0.0401, 'returns': 0.0585, 'drawdown': 0.0824, 'margin': 0.002916, 'sharpe': 1.47, 'fitness': 1.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4839705, 'bookSize': 20000000, 'longCount': 957, 'shortCount': 1035, 'turnover': 0.0297, 'returns': 0.0469, 'drawdown': 0.1109, 'margin': 0.003161, 'fitness': 0.72, 'sharpe': 1.18}, 'riskNeutralized': {'pnl': 3014621, 'bookSize': 20000000, 'longCount': 966, 'shortCount': 1020, 'turnover': 0.0401, 'returns': 0.0292, 'drawdown': 0.0473, 'margin': 0.001456, 'fitness': 0.73, 'sharpe': 1.51}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'WARNING', 'limit': 1.58, 'value': 1.47}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0401}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0401}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.76, 'value': 0.77}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 1.18, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1J6jA8d', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_arg_min(mdl25_01v,10)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:15:38-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:15:38-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 428978, 'bookSize': 20000000, 'longCount': 403, 'shortCount': 10, 'turnover': 0.3951, 'returns': 0.0042, 'drawdown': 0.4266, 'margin': 2.1e-05, 'sharpe': 0.03, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2465995, 'bookSize': 20000000, 'longCount': 1352, 'shortCount': 718, 'turnover': 0.1095, 'returns': 0.0239, 'drawdown': 0.7211, 'margin': 0.000436, 'fitness': 0.06, 'sharpe': 0.14}, 'riskNeutralized': {'pnl': -432035, 'bookSize': 20000000, 'longCount': 403, 'shortCount': 10, 'turnover': 0.3951, 'returns': -0.0042, 'drawdown': 0.4153, 'margin': -2.1e-05, 'fitness': -0.0, 'sharpe': -0.03}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.03}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3951}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3951}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-01-13', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.02, 'value': 0.4}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.55, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:14:16,388 - ace - ERROR - Simulation failed. {'id': '1ziqsB2nU4FVb5A10V2YpY5X', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'vRn00qqA', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'tail(mdl25_21v, lower=-999999, upper=-2, newval=1)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:15:21-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:15:22-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7770305, 'bookSize': 20000000, 'longCount': 1078, 'shortCount': 909, 'turnover': 0.0208, 'returns': 0.0753, 'drawdown': 0.1047, 'margin': 0.007249, 'sharpe': 2.02, 'fitness': 1.57, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 7042850, 'bookSize': 20000000, 'longCount': 1059, 'shortCount': 936, 'turnover': 0.0169, 'returns': 0.0682, 'drawdown': 0.103, 'margin': 0.008076, 'fitness': 1.37, 'sharpe': 1.85}, 'riskNeutralized': {'pnl': 2701785, 'bookSize': 20000000, 'longCount': 1078, 'shortCount': 909, 'turnover': 0.0208, 'returns': 0.0262, 'drawdown': 0.0432, 'margin': 0.002521, 'fitness': 0.66, 'sharpe': 1.45}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.02}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.57}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0208}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0208}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.05, 'value': 0.91}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.65, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'P0reeW77', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'days_from_last_change(mdl25_01v)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:15:28-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:15:29-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.59'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1350651, 'bookSize': 20000000, 'longCount': 855, 'shortCount': 1955, 'turnover': 0.0227, 'returns': 0.0131, 'drawdown': 0.1059, 'margin': 0.001154, 'sharpe': 0.37, 'fitness': 0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1384166, 'bookSize': 20000000, 'longCount': 881, 'shortCount': 1939, 'turnover': 0.0175, 'returns': 0.0134, 'drawdown': 0.1172, 'margin': 0.001536, 'fitness': 0.09, 'sharpe': 0.29}, 'riskNeutralized': {'pnl': 810550, 'bookSize': 20000000, 'longCount': 855, 'shortCount': 1955, 'turnover': 0.0227, 'returns': 0.0079, 'drawdown': 0.0201, 'margin': 0.000693, 'fitness': 0.12, 'sharpe': 0.48}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.37}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0227}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0227}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2014-01-02', 'limit': 0.1, 'value': 0.128388}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.19, 'value': 0.39}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.15, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'QPreeJWX', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_delta(mdl25_21v,5), ts_delta(mdl25_vrv421_71v,5))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:15:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:15:31-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 9253957, 'bookSize': 20000000, 'longCount': 967, 'shortCount': 1003, 'turnover': 0.5921, 'returns': 0.0897, 'drawdown': 0.0932, 'margin': 0.000303, 'sharpe': 1.31, 'fitness': 0.51, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 735929, 'bookSize': 20000000, 'longCount': 957, 'shortCount': 1028, 'turnover': 0.1655, 'returns': 0.0071, 'drawdown': 0.2576, 'margin': 8.6e-05, 'fitness': 0.02, 'sharpe': 0.09}, 'riskNeutralized': {'pnl': 9137573, 'bookSize': 20000000, 'longCount': 967, 'shortCount': 1003, 'turnover': 0.5921, 'returns': 0.0885, 'drawdown': 0.0865, 'margin': 0.000299, 'fitness': 0.56, 'sharpe': 1.46}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'WARNING', 'limit': 1.58, 'value': 1.31}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.51}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5921}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5921}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.68, 'value': 1.01}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 0.21, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '88kAAoN7', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(sign(ts_zscore(mdl25_vrv421_71v,10)), sign(ts_zscore(mdl25_vrv421_81v,10)))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:15:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:15:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 827303, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 19, 'turnover': 1.0205, 'returns': 0.008, 'drawdown': 0.2286, 'margin': 1.6e-05, 'sharpe': 0.08, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -3008482, 'bookSize': 20000000, 'longCount': 1386, 'shortCount': 620, 'turnover': 0.1496, 'returns': -0.0292, 'drawdown': 0.3641, 'margin': -0.00039, 'fitness': -0.14, 'sharpe': -0.31}, 'riskNeutralized': {'pnl': 1162712, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 19, 'turnover': 1.0205, 'returns': 0.0113, 'drawdown': 0.28, 'margin': 2.2e-05, 'fitness': 0.01, 'sharpe': 0.12}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.08}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0205}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0205}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-01-12', 'limit': 0.1, 'value': 0.500001}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.04, 'value': 0.1}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.23, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Xgwqg3N8', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(mdl25_vrv421_71v)', 'description': 'Used SUGGESTION1 by using single high-coverage, high-userCount field mdl25_vrv421_71v (FCF Yield) because it has the highest user/alpha counts; SUGGESTION2 not applicable (no VECTOR); SUGGESTION3 not applied (coverage=0.9607>0.6); SUGGESTION4 applied by choosing a high userCount field. Kept KEEP_IN_MIND1-5: implementation short, <=7 operators, 1 datafield, no GROUP, no VECTOR wrapping. Confidence set to 0.72 based on strong coverage and common use in value signals.', 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:05:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:05:38-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6512354, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 1055, 'turnover': 0.0437, 'returns': 0.0631, 'drawdown': 0.1363, 'margin': 0.00289, 'sharpe': 0.82, 'fitness': 0.58, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 5160223, 'bookSize': 20000000, 'longCount': 1014, 'shortCount': 1053, 'turnover': 0.0288, 'returns': 0.05, 'drawdown': 0.1347, 'margin': 0.003473, 'fitness': 0.48, 'sharpe': 0.76}, 'riskNeutralized': {'pnl': 3074460, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 1055, 'turnover': 0.0437, 'returns': 0.0298, 'drawdown': 0.1059, 'margin': 0.001364, 'fitness': 0.27, 'sharpe': 0.56}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.82}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.58}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0437}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0437}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499978}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.43, 'value': 0.44}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.58, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Gr0VVaNG', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_21v,30), ts_zscore(mdl25_01v,30))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:15:33-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:15:33-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:15:40,938 - ace - ERROR - Simulation failed. {'id': '1TNzJZ1YR5aQarq1eJIo0ZUN', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 19, 'end': 48, 'property': 'regular'}}

{'id': 'Gr0VVaNG', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_21v,30), ts_zscore(mdl25_01v,30))', 'description': 'Difference between earnings quality by cash flow (mdl25_21v) and accruals (mdl25_01v) to detect accounting-driven earnings. Applied SUGGESTION1 combining two fields; coverage high so no backfill. Confidence 0.70.', 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:15:33-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:15:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1J66q2g', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_delta(mdl25_vrv421_91v,10)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:16:52-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:16:52-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 9352210, 'bookSize': 20000000, 'longCount': 988, 'shortCount': 1005, 'turnover': 0.6034, 'returns': 0.0906, 'drawdown': 0.3048, 'margin': 0.0003, 'sharpe': 0.59, 'fitness': 0.23, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 6268052, 'bookSize': 20000000, 'longCount': 1065, 'shortCount': 947, 'turnover': 0.131, 'returns': 0.0607, 'drawdown': 0.2271, 'margin': 0.000927, 'fitness': 0.31, 'sharpe': 0.46}, 'riskNeutralized': {'pnl': 5216868, 'bookSize': 20000000, 'longCount': 988, 'shortCount': 1005, 'turnover': 0.6034, 'returns': 0.0506, 'drawdown': 0.3544, 'margin': 0.000168, 'fitness': 0.11, 'sharpe': 0.38}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.59}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.23}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6034}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6034}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499995}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.31, 'value': 0.46}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.44, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'N1WMMkEq', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_max_diff(mdl25_vrv421_71v,7)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:16:53-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:16:53-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.57'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 10897694, 'bookSize': 20000000, 'longCount': 1573, 'shortCount': 471, 'turnover': 0.4274, 'returns': 0.1056, 'drawdown': 0.5056, 'margin': 0.000494, 'sharpe': 0.6, 'fitness': 0.3, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2584776, 'bookSize': 20000000, 'longCount': 1468, 'shortCount': 599, 'turnover': 0.1191, 'returns': 0.025, 'drawdown': 0.4498, 'margin': 0.000421, 'fitness': 0.08, 'sharpe': 0.18}, 'riskNeutralized': {'pnl': 8427004, 'bookSize': 20000000, 'longCount': 1573, 'shortCount': 471, 'turnover': 0.4274, 'returns': 0.0817, 'drawdown': 0.1988, 'margin': 0.000382, 'fitness': 0.28, 'sharpe': 0.65}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.6}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.3}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4274}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4274}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-26', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.31, 'value': 0.49}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.23, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1J66qeE', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_arg_max(mdl25_vrv421_71v,60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:16:50-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:16:51-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -2866328, 'bookSize': 20000000, 'longCount': 1054, 'shortCount': 1012, 'turnover': 0.1023, 'returns': -0.0278, 'drawdown': 0.2919, 'margin': -0.000543, 'sharpe': -1.13, 'fitness': -0.53, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2091383, 'bookSize': 20000000, 'longCount': 1066, 'shortCount': 1006, 'turnover': 0.0604, 'returns': -0.0203, 'drawdown': 0.2191, 'margin': -0.000671, 'fitness': -0.35, 'sharpe': -0.86}, 'riskNeutralized': {'pnl': -2393548, 'bookSize': 20000000, 'longCount': 1054, 'shortCount': 1012, 'turnover': 0.1023, 'returns': -0.0232, 'drawdown': 0.2471, 'margin': -0.000454, 'fitness': -0.63, 'sharpe': -1.47}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.13}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.53}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1023}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1023}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.59, 'value': -0.62}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.19, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'xAwMMXEN', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(mdl25_vrv421_71v,20), ts_ir(mdl25_vrv421_71v,60))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:16:52-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:16:52-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.74'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1684582, 'bookSize': 20000000, 'longCount': 1042, 'shortCount': 1002, 'turnover': 0.5131, 'returns': 0.0163, 'drawdown': 0.0746, 'margin': 6.4e-05, 'sharpe': 0.45, 'fitness': 0.08, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 842138, 'bookSize': 20000000, 'longCount': 1062, 'shortCount': 996, 'turnover': 0.1482, 'returns': 0.0082, 'drawdown': 0.0708, 'margin': 0.00011, 'fitness': 0.07, 'sharpe': 0.28}, 'riskNeutralized': {'pnl': -1904670, 'bookSize': 20000000, 'longCount': 1042, 'shortCount': 1002, 'turnover': 0.5131, 'returns': -0.0185, 'drawdown': 0.1951, 'margin': -7.2e-05, 'fitness': -0.2, 'sharpe': -1.03}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.45}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.08}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5131}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5131}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.23, 'value': 0.52}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.21, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Gr0VV093', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(mdl25_vrv421_81v,252)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:17:06-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:17:07-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6226352, 'bookSize': 20000000, 'longCount': 993, 'shortCount': 1015, 'turnover': 0.0954, 'returns': 0.0603, 'drawdown': 0.0278, 'margin': 0.001265, 'sharpe': 2.45, 'fitness': 1.7, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4018266, 'bookSize': 20000000, 'longCount': 997, 'shortCount': 1019, 'turnover': 0.0474, 'returns': 0.0389, 'drawdown': 0.0287, 'margin': 0.001643, 'fitness': 0.91, 'sharpe': 1.64}, 'riskNeutralized': {'pnl': 4411210, 'bookSize': 20000000, 'longCount': 993, 'shortCount': 1015, 'turnover': 0.0954, 'returns': 0.0427, 'drawdown': 0.0178, 'margin': 0.000896, 'fitness': 1.4, 'sharpe': 2.4}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.45}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.7}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0954}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0954}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 1.27, 'value': 1.37}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 2.03, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:18:58,070 - ace - ERROR - Simulation failed. {'id': '1kUgTzf2c56f9FDSfC21bNY', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'le6xx8q2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(mdl25_vrv421_81v,7)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:20:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:20:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6125244, 'bookSize': 20000000, 'longCount': 917, 'shortCount': 938, 'turnover': 0.749, 'returns': 0.0594, 'drawdown': 0.0457, 'margin': 0.000158, 'sharpe': 2.09, 'fitness': 0.59, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3110768, 'bookSize': 20000000, 'longCount': 937, 'shortCount': 1002, 'turnover': 0.1872, 'returns': 0.0301, 'drawdown': 0.0595, 'margin': 0.000322, 'fitness': 0.46, 'sharpe': 1.15}, 'riskNeutralized': {'pnl': 2244372, 'bookSize': 20000000, 'longCount': 917, 'shortCount': 938, 'turnover': 0.749, 'returns': 0.0217, 'drawdown': 0.0378, 'margin': 5.8e-05, 'fitness': 0.21, 'sharpe': 1.22}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.09}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.59}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.749}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.749}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 1.09, 'value': 1.14}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.67, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'mL2OOgpx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'normalize(ts_zscore(mdl25_vrv421_71v,30))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:20:03-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:20:03-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6373966, 'bookSize': 20000000, 'longCount': 1011, 'shortCount': 1043, 'turnover': 0.3628, 'returns': 0.0618, 'drawdown': 0.0479, 'margin': 0.000341, 'sharpe': 2.26, 'fitness': 0.93, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3773731, 'bookSize': 20000000, 'longCount': 1004, 'shortCount': 1059, 'turnover': 0.118, 'returns': 0.0366, 'drawdown': 0.0665, 'margin': 0.00062, 'fitness': 0.79, 'sharpe': 1.46}, 'riskNeutralized': {'pnl': 2784763, 'bookSize': 20000000, 'longCount': 1011, 'shortCount': 1043, 'turnover': 0.3628, 'returns': 0.027, 'drawdown': 0.0327, 'margin': 0.000149, 'fitness': 0.42, 'sharpe': 1.54}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.26}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.93}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3628}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3628}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.17, 'value': 1.14}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.75, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'zqwaaY8K', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_01v,20),0), less(ts_delta(mdl25_vrv421_71v,20),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:20:10-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:20:11-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -3051911, 'bookSize': 20000000, 'longCount': 205, 'shortCount': 1551, 'turnover': 0.1994, 'returns': -0.0296, 'drawdown': 0.3441, 'margin': -0.000297, 'sharpe': -0.8, 'fitness': -0.31, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1821740, 'bookSize': 20000000, 'longCount': 466, 'shortCount': 1579, 'turnover': 0.0846, 'returns': -0.0177, 'drawdown': 0.2045, 'margin': -0.000417, 'fitness': -0.18, 'sharpe': -0.49}, 'riskNeutralized': {'pnl': -2661566, 'bookSize': 20000000, 'longCount': 205, 'shortCount': 1551, 'turnover': 0.1994, 'returns': -0.0258, 'drawdown': 0.3032, 'margin': -0.000259, 'fitness': -0.31, 'sharpe': -0.87}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.8}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.31}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1994}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1994}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.42, 'value': -0.12}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.24, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'bl2pp6zl', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_av_diff(mdl25_vrv421_71v,252)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:21:07-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:21:08-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1770035, 'bookSize': 20000000, 'longCount': 1020, 'shortCount': 1042, 'turnover': 0.0631, 'returns': 0.0172, 'drawdown': 0.2325, 'margin': 0.000544, 'sharpe': 0.19, 'fitness': 0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 448365, 'bookSize': 20000000, 'longCount': 1013, 'shortCount': 1053, 'turnover': 0.0399, 'returns': 0.0043, 'drawdown': 0.2794, 'margin': 0.000218, 'fitness': 0.01, 'sharpe': 0.06}, 'riskNeutralized': {'pnl': 2539592, 'bookSize': 20000000, 'longCount': 1020, 'shortCount': 1042, 'turnover': 0.0631, 'returns': 0.0246, 'drawdown': 0.165, 'margin': 0.00078, 'fitness': 0.16, 'sharpe': 0.36}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.19}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0631}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0631}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499988}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.1, 'value': 0.17}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.31, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'O0weeAzb', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_scale(mdl25_vrv421_71v,90),30)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:21:07-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:21:08-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 4353742, 'bookSize': 20000000, 'longCount': 1003, 'shortCount': 1043, 'turnover': 0.4025, 'returns': 0.0422, 'drawdown': 0.0504, 'margin': 0.00021, 'sharpe': 1.67, 'fitness': 0.54, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2175335, 'bookSize': 20000000, 'longCount': 1000, 'shortCount': 1056, 'turnover': 0.1264, 'returns': 0.0211, 'drawdown': 0.0664, 'margin': 0.000334, 'fitness': 0.38, 'sharpe': 0.92}, 'riskNeutralized': {'pnl': 1181880, 'bookSize': 20000000, 'longCount': 1003, 'shortCount': 1043, 'turnover': 0.4025, 'returns': 0.0115, 'drawdown': 0.0488, 'margin': 5.7e-05, 'fitness': 0.11, 'sharpe': 0.68}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.67}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.54}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4025}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4025}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.87, 'value': 0.88}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 1.23, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'XgwqqNE8', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_corr(mdl25_vrv421_71v, mdl25_21v,60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:21:23-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:21:23-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1495441, 'bookSize': 20000000, 'longCount': 1552, 'shortCount': 790, 'turnover': 0.0671, 'returns': -0.0145, 'drawdown': 0.21, 'margin': -0.000432, 'sharpe': -0.53, 'fitness': -0.18, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -519944, 'bookSize': 20000000, 'longCount': 1583, 'shortCount': 884, 'turnover': 0.0444, 'returns': -0.005, 'drawdown': 0.1367, 'margin': -0.000227, 'fitness': -0.04, 'sharpe': -0.18}, 'riskNeutralized': {'pnl': -1731901, 'bookSize': 20000000, 'longCount': 1552, 'shortCount': 790, 'turnover': 0.0671, 'returns': -0.0168, 'drawdown': 0.1937, 'margin': -0.0005, 'fitness': -0.4, 'sharpe': -1.08}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.53}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.18}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0671}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0671}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.28, 'value': -0.35}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.72, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:26:39,439 - ace - ERROR - Simulation failed. {'id': '29RIZb5Ic4QwbxxIHS9EKvA', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 0, 'end': 44, 'property': 'regular'}}

{'id': 'bl2p7WdZ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_vrv421_71v,10),0), greater(ts_delta(mdl25_21v,10),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:27:47-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:27:47-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 207857, 'bookSize': 20000000, 'longCount': 153, 'shortCount': 1485, 'turnover': 0.4531, 'returns': 0.002, 'drawdown': 0.1325, 'margin': 9e-06, 'sharpe': 0.06, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1077971, 'bookSize': 20000000, 'longCount': 397, 'shortCount': 1587, 'turnover': 0.1224, 'returns': 0.0104, 'drawdown': 0.1071, 'margin': 0.000171, 'fitness': 0.07, 'sharpe': 0.25}, 'riskNeutralized': {'pnl': -695893, 'bookSize': 20000000, 'longCount': 153, 'shortCount': 1485, 'turnover': 0.4531, 'returns': -0.0067, 'drawdown': 0.2012, 'margin': -3e-05, 'fitness': -0.03, 'sharpe': -0.22}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.06}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4531}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4531}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.03, 'value': 0.11}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.57, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E503orx9', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_01v,30), ts_zscore(mdl25_vrv421_91v,30))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:27:51-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:27:52-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'wpw6Xnmp', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'divide(ts_zscore(mdl25_01v,20), ts_std_dev(mdl25_01v,20))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:27:55-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:27:55-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'zqwaXP91', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(mdl25_21v,20), ts_returns(mdl25_21v,21))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:27:59-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:28:00-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -532713, 'bookSize': 20000000, 'longCount': 214, 'shortCount': 634, 'turnover': 0.4186, 'returns': -0.0052, 'drawdown': 0.4289, 'margin': -2.5e-05, 'sharpe': -0.07, 'fitness': -0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -3597797, 'bookSize': 20000000, 'longCount': 374, 'shortCount': 805, 'turnover': 0.109, 'returns': -0.0349, 'drawdown': 0.5176, 'margin': -0.00064, 'fitness': -0.23, 'sharpe': -0.44}, 'riskNeutralized': {'pnl': 345396, 'bookSize': 20000000, 'longCount': 214, 'shortCount': 634, 'turnover': 0.4186, 'returns': 0.0033, 'drawdown': 0.4233, 'margin': 1.6e-05, 'fitness': 0.0, 'sharpe': 0.05}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.07}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4186}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4186}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2014-02-21', 'limit': 0.1, 'value': 0.309567}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.04, 'value': 0.23}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.17, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'KPYexXQE', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'add(reverse(ts_av_diff(mdl25_01v,60)), ts_zscore(mdl25_vrv421_71v,30))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T03:28:04-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:28:05-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 4038499, 'bookSize': 20000000, 'longCount': 1485, 'shortCount': 557, 'turnover': 0.092, 'returns': 0.0391, 'drawdown': 0.0866, 'margin': 0.00085, 'sharpe': 0.99, 'fitness': 0.55, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1656151, 'bookSize': 20000000, 'longCount': 1393, 'shortCount': 657, 'turnover': 0.0609, 'returns': 0.016, 'drawdown': 0.1808, 'margin': 0.000527, 'fitness': 0.14, 'sharpe': 0.4}, 'riskNeutralized': {'pnl': 3248679, 'bookSize': 20000000, 'longCount': 1485, 'shortCount': 557, 'turnover': 0.092, 'returns': 0.0315, 'drawdown': 0.056, 'margin': 0.000684, 'fitness': 0.57, 'sharpe': 1.13}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.99}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.55}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.092}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.092}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.51, 'value': 0.49}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.83, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'd58qeERv', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_max_diff(mdl25_vrv421_81v,90)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:28:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:28:01-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -6556862, 'bookSize': 20000000, 'longCount': 1530, 'shortCount': 480, 'turnover': 0.1636, 'returns': -0.0635, 'drawdown': 0.9262, 'margin': -0.000777, 'sharpe': -0.38, 'fitness': -0.24, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 5341207, 'bookSize': 20000000, 'longCount': 1365, 'shortCount': 653, 'turnover': 0.055, 'returns': 0.0518, 'drawdown': 0.4916, 'margin': 0.001881, 'fitness': 0.21, 'sharpe': 0.33}, 'riskNeutralized': {'pnl': -2677018, 'bookSize': 20000000, 'longCount': 1530, 'shortCount': 480, 'turnover': 0.1636, 'returns': -0.0259, 'drawdown': 0.7652, 'margin': -0.000317, 'fitness': -0.07, 'sharpe': -0.17}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.38}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.24}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1636}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1636}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-12-18', 'limit': 0.1, 'value': 0.499986}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.2, 'value': 0.06}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.62, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:28:09,354 - ace - ERROR - Simulation failed. {'id': '1E0htubKw4Cr9ARsPaZf9OI', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 8, 'end': 51, 'property': 'regular'}}

{'id': 'le6xJ37x', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_mean(mdl25_vrv421_91v,30), inverse(ts_std_dev(mdl25_vrv421_91v,30)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T03:29:19-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:29:19-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3553148, 'bookSize': 20000000, 'longCount': 857, 'shortCount': 1160, 'turnover': 0.1148, 'returns': 0.0344, 'drawdown': 0.109, 'margin': 0.0006, 'sharpe': 0.68, 'fitness': 0.36, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1956404, 'bookSize': 20000000, 'longCount': 884, 'shortCount': 1139, 'turnover': 0.063, 'returns': 0.019, 'drawdown': 0.1417, 'margin': 0.000602, 'fitness': 0.14, 'sharpe': 0.37}, 'riskNeutralized': {'pnl': 1102961, 'bookSize': 20000000, 'longCount': 857, 'shortCount': 1160, 'turnover': 0.1148, 'returns': 0.0107, 'drawdown': 0.0785, 'margin': 0.000186, 'fitness': 0.11, 'sharpe': 0.38}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.68}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.36}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1148}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1148}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.35, 'value': 0.34}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.93, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'pwJ0QKrb', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_vrv421_71v,10), ts_zscore(mdl25_vrv421_71v,120))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:29:16-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:29:16-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1647950, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 1013, 'turnover': 0.4252, 'returns': -0.016, 'drawdown': 0.1903, 'margin': -7.5e-05, 'sharpe': -0.64, 'fitness': -0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1658694, 'bookSize': 20000000, 'longCount': 1027, 'shortCount': 1019, 'turnover': 0.1178, 'returns': -0.0161, 'drawdown': 0.1731, 'margin': -0.000273, 'fitness': -0.25, 'sharpe': -0.71}, 'riskNeutralized': {'pnl': -2500736, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 1013, 'turnover': 0.4252, 'returns': -0.0242, 'drawdown': 0.2586, 'margin': -0.000114, 'fitness': -0.34, 'sharpe': -1.43}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.64}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4252}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4252}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.33, 'value': -0.4}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.46, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E503oeEJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_01v,10),0), less(ts_delta(mdl25_vrv421_71v,10),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:29:20-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:29:20-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -6295969, 'bookSize': 20000000, 'longCount': 102, 'shortCount': 1375, 'turnover': 0.3087, 'returns': -0.061, 'drawdown': 0.7084, 'margin': -0.000395, 'sharpe': -1.24, 'fitness': -0.55, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2305478, 'bookSize': 20000000, 'longCount': 488, 'shortCount': 1562, 'turnover': 0.1088, 'returns': -0.0223, 'drawdown': 0.3391, 'margin': -0.00041, 'fitness': -0.17, 'sharpe': -0.41}, 'riskNeutralized': {'pnl': -5848768, 'bookSize': 20000000, 'longCount': 102, 'shortCount': 1375, 'turnover': 0.3087, 'returns': -0.0567, 'drawdown': 0.6311, 'margin': -0.000367, 'fitness': -0.59, 'sharpe': -1.38}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.24}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.55}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3087}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3087}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2017-01-26', 'limit': 0.1, 'value': 0.108794}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.64, 'value': -0.42}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.39, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '0mkonMr8', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_vrv421_91v,10),0), less(ts_std_dev(mdl25_vrv421_91v,30), ts_std_dev(mdl25_vrv421_91v,90)))', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-04T03:29:21-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:29:22-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3464457, 'bookSize': 20000000, 'longCount': 765, 'shortCount': 1209, 'turnover': 0.4256, 'returns': 0.0336, 'drawdown': 0.0353, 'margin': 0.000158, 'sharpe': 1.33, 'fitness': 0.37, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2337762, 'bookSize': 20000000, 'longCount': 794, 'shortCount': 1218, 'turnover': 0.1252, 'returns': 0.0227, 'drawdown': 0.0527, 'margin': 0.000362, 'fitness': 0.41, 'sharpe': 0.97}, 'riskNeutralized': {'pnl': 11266, 'bookSize': 20000000, 'longCount': 765, 'shortCount': 1209, 'turnover': 0.4256, 'returns': 0.0001, 'drawdown': 0.0553, 'margin': 1e-06, 'fitness': 0.0, 'sharpe': 0.01}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'WARNING', 'limit': 1.58, 'value': 1.33}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.37}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4256}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4256}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.69, 'value': 0.81}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 0.99, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'bl2p7jJm', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'greater(ts_ir(mdl25_vrv421_71v,30),0)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:29:50-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:29:51-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6040140, 'bookSize': 20000000, 'longCount': 1550, 'shortCount': 449, 'turnover': 0.0174, 'returns': 0.0585, 'drawdown': 0.1206, 'margin': 0.006734, 'sharpe': 1.8, 'fitness': 1.23, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 5921408, 'bookSize': 20000000, 'longCount': 1536, 'shortCount': 533, 'turnover': 0.0159, 'returns': 0.0574, 'drawdown': 0.1243, 'margin': 0.007216, 'fitness': 1.19, 'sharpe': 1.75}, 'riskNeutralized': {'pnl': 2109037, 'bookSize': 20000000, 'longCount': 1550, 'shortCount': 449, 'turnover': 0.0174, 'returns': 0.0204, 'drawdown': 0.0309, 'margin': 0.002351, 'fitness': 0.45, 'sharpe': 1.12}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.8}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.23}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0174}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0174}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.94, 'value': 0.7}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.68, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'VkwnK7zM', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_vrv421_71v,5),0), greater(ts_delta(mdl25_vrv421_71v,20),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:29:51-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:29:51-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 4506190, 'bookSize': 20000000, 'longCount': 622, 'shortCount': 1389, 'turnover': 0.4979, 'returns': 0.0437, 'drawdown': 0.0321, 'margin': 0.000175, 'sharpe': 1.75, 'fitness': 0.52, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2358748, 'bookSize': 20000000, 'longCount': 674, 'shortCount': 1385, 'turnover': 0.1356, 'returns': 0.0229, 'drawdown': 0.0979, 'margin': 0.000337, 'fitness': 0.4, 'sharpe': 0.98}, 'riskNeutralized': {'pnl': 1574639, 'bookSize': 20000000, 'longCount': 622, 'shortCount': 1389, 'turnover': 0.4979, 'returns': 0.0153, 'drawdown': 0.0435, 'margin': 6.1e-05, 'fitness': 0.16, 'sharpe': 0.94}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.75}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.52}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4979}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4979}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.91, 'value': 0.7}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.35, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:30:12,209 - ace - ERROR - Simulation failed. {'id': 'aZxIvdhh5bKawIvEj1mAfh', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 19, 'end': 41, 'property': 'regular'}}
2026-02-04 17:30:12,527 - ace - ERROR - Simulation failed. {'id': '4CtpwS7Do4QuboD9FWQ3EpE', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'ZYwZkXMd', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_count_nans(mdl25_21v,90))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:31:21-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:31:21-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.58'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1068585, 'bookSize': 20000000, 'longCount': 1945, 'shortCount': 855, 'turnover': 0.0118, 'returns': -0.0104, 'drawdown': 0.1567, 'margin': -0.001755, 'sharpe': -0.31, 'fitness': -0.09, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -967687, 'bookSize': 20000000, 'longCount': 1935, 'shortCount': 886, 'turnover': 0.0118, 'returns': -0.0094, 'drawdown': 0.1497, 'margin': -0.001588, 'fitness': -0.08, 'sharpe': -0.28}, 'riskNeutralized': {'pnl': -336551, 'bookSize': 20000000, 'longCount': 1945, 'shortCount': 855, 'turnover': 0.0118, 'returns': -0.0033, 'drawdown': 0.0367, 'margin': -0.000553, 'fitness': -0.04, 'sharpe': -0.23}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.31}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.09}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0118}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0118}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.16, 'value': -0.39}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.22, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'zqwaXA8K', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_ir(mdl25_vrv421_91v,60),0), greater(ts_delta(mdl25_vrv421_91v,10),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:31:17-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:31:18-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6365857, 'bookSize': 20000000, 'longCount': 837, 'shortCount': 1134, 'turnover': 0.4414, 'returns': 0.0617, 'drawdown': 0.0362, 'margin': 0.000279, 'sharpe': 2.02, 'fitness': 0.76, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 5137522, 'bookSize': 20000000, 'longCount': 858, 'shortCount': 1154, 'turnover': 0.1277, 'returns': 0.0498, 'drawdown': 0.0269, 'margin': 0.00078, 'fitness': 1.18, 'sharpe': 1.89}, 'riskNeutralized': {'pnl': 1007482, 'bookSize': 20000000, 'longCount': 837, 'shortCount': 1134, 'turnover': 0.4414, 'returns': 0.0098, 'drawdown': 0.0354, 'margin': 4.4e-05, 'fitness': 0.1, 'sharpe': 0.67}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.02}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.76}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4414}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4414}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 1.05, 'value': 1.29}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.73, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'O0weK6rq', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_delta(mdl25_vrv421_81v,20), ts_delta(mdl25_vrv421_91v,20))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:31:17-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:31:18-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -3337364, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 986, 'turnover': 0.4126, 'returns': -0.0323, 'drawdown': 0.726, 'margin': -0.000157, 'sharpe': -0.28, 'fitness': -0.08, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2539829, 'bookSize': 20000000, 'longCount': 947, 'shortCount': 1060, 'turnover': 0.1061, 'returns': -0.0246, 'drawdown': 0.6204, 'margin': -0.000464, 'fitness': -0.12, 'sharpe': -0.28}, 'riskNeutralized': {'pnl': 1596536, 'bookSize': 20000000, 'longCount': 1007, 'shortCount': 986, 'turnover': 0.4126, 'returns': 0.0155, 'drawdown': 0.2818, 'margin': 7.5e-05, 'fitness': 0.03, 'sharpe': 0.18}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.28}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.08}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4126}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4126}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2018-03-21', 'limit': 0.1, 'value': 0.499232}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.15, 'value': -0.07}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.36, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E503oNZr', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(mdl25_01v,15)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:31:24-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:31:24-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'le6xJ9k7', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'add(multiply(ts_zscore(mdl25_vrv421_71v,10),1), multiply(ts_zscore(mdl25_vrv421_71v,120),0.5))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:32:07-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:32:07-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7814806, 'bookSize': 20000000, 'longCount': 1002, 'shortCount': 1017, 'turnover': 0.541, 'returns': 0.0757, 'drawdown': 0.0478, 'margin': 0.00028, 'sharpe': 2.65, 'fitness': 0.99, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4369616, 'bookSize': 20000000, 'longCount': 1003, 'shortCount': 1043, 'turnover': 0.1474, 'returns': 0.0423, 'drawdown': 0.0585, 'margin': 0.000574, 'fitness': 0.86, 'sharpe': 1.6}, 'riskNeutralized': {'pnl': 3592295, 'bookSize': 20000000, 'longCount': 1002, 'shortCount': 1017, 'turnover': 0.541, 'returns': 0.0348, 'drawdown': 0.0294, 'margin': 0.000129, 'fitness': 0.49, 'sharpe': 1.95}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.65}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.99}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.541}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.541}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 1.38, 'value': 1.52}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 2.14, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'd58qeoNK', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_corr(mdl25_21v, mdl25_vrv421_71v,60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:32:16-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:32:16-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -1495441, 'bookSize': 20000000, 'longCount': 1552, 'shortCount': 790, 'turnover': 0.0671, 'returns': -0.0145, 'drawdown': 0.21, 'margin': -0.000432, 'sharpe': -0.53, 'fitness': -0.18, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -519944, 'bookSize': 20000000, 'longCount': 1583, 'shortCount': 884, 'turnover': 0.0444, 'returns': -0.005, 'drawdown': 0.1367, 'margin': -0.000227, 'fitness': -0.04, 'sharpe': -0.18}, 'riskNeutralized': {'pnl': -1731901, 'bookSize': 20000000, 'longCount': 1552, 'shortCount': 790, 'turnover': 0.0671, 'returns': -0.0168, 'drawdown': 0.1937, 'margin': -0.0005, 'fitness': -0.4, 'sharpe': -1.08}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.53}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.18}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0671}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0671}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.28, 'value': -0.35}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.72, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[BEST ALPHA SAVED] Sharpe=2.6500, ID=le6xJ9k7, File=good_alpha_list.json
[SAVED] 6 results to ./results/EUR_TOP2500_model.csv
--- Simulating alpha batch 88 to 96 ---

2026-02-04 17:32:24,059 - ace - ERROR - Simulation failed. {'id': '2Hh0C8P34tNaQnQdHYSeqa', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Invalid number of inputs : 2, should be exactly 1 input(s)', 'location': {'line': 1, 'start': 0, 'end': 37, 'property': 'regular'}}

{'id': 'mL2OevO2', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'if_else(greater(ts_zscore(mdl25_vrv421_71v,30),2), -1, if_else(less(ts_zscore(mdl25_vrv421_71v,30),-2), 1, 0))', 'description': None, 'operatorCount': 6}, 'dateCreated': '2026-02-04T03:33:36-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:33:36-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -7471591, 'bookSize': 20000000, 'longCount': 813, 'shortCount': 898, 'turnover': 0.7782, 'returns': -0.0724, 'drawdown': 0.7559, 'margin': -0.000186, 'sharpe': -1.89, 'fitness': -0.58, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2057438, 'bookSize': 20000000, 'longCount': 1011, 'shortCount': 1050, 'turnover': 0.1812, 'returns': -0.0199, 'drawdown': 0.2141, 'margin': -0.00022, 'fitness': -0.15, 'sharpe': -0.46}, 'riskNeutralized': {'pnl': -4251474, 'bookSize': 20000000, 'longCount': 813, 'shortCount': 898, 'turnover': 0.7782, 'returns': -0.0412, 'drawdown': 0.453, 'margin': -0.000106, 'fitness': -0.3, 'sharpe': -1.32}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.89}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.58}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.7782}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.7782}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.98, 'value': -1.22}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.92, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'KPYex1dj', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'divide(ts_mean(mdl25_01v,30), ts_std_dev(mdl25_01v,30))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:33:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:33:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 695780, 'bookSize': 20000000, 'longCount': 262, 'shortCount': 356, 'turnover': 0.4318, 'returns': 0.0067, 'drawdown': 0.2136, 'margin': 3.1e-05, 'sharpe': 0.11, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -728942, 'bookSize': 20000000, 'longCount': 468, 'shortCount': 511, 'turnover': 0.1024, 'returns': -0.0071, 'drawdown': 0.2581, 'margin': -0.000138, 'fitness': -0.03, 'sharpe': -0.12}, 'riskNeutralized': {'pnl': -1230753, 'bookSize': 20000000, 'longCount': 262, 'shortCount': 356, 'turnover': 0.4318, 'returns': -0.0119, 'drawdown': 0.2337, 'margin': -5.5e-05, 'fitness': -0.04, 'sharpe': -0.27}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.11}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4318}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4318}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.06, 'value': -0.24}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.09, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'N1WMkZWo', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'hump(mdl25_vrv421_81v, hump=0.01)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:33:36-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:33:37-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2385383, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 1005, 'turnover': 0.1552, 'returns': 0.0231, 'drawdown': 0.143, 'margin': 0.000298, 'sharpe': 0.31, 'fitness': 0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2052305, 'bookSize': 20000000, 'longCount': 1001, 'shortCount': 1018, 'turnover': 0.0422, 'returns': 0.0199, 'drawdown': 0.163, 'margin': 0.000944, 'fitness': 0.12, 'sharpe': 0.31}, 'riskNeutralized': {'pnl': 1289317, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 1005, 'turnover': 0.1552, 'returns': 0.0125, 'drawdown': 0.1337, 'margin': 0.000161, 'fitness': 0.06, 'sharpe': 0.2}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.31}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1552}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1552}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499975}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.16, 'value': 0.06}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.18, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '6XPbLbXp', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_delta(mdl25_vrv421_71v, 252)', 'description': 'S1: single-field mdl25_vrv421_71v to capture improvement in FCF yield. S2 N/A. S3 not needed. S4 used popular FCF Yield field. KEEP_IN_MIND: concise implementation. Confidence: 0.69', 'operatorCount': 1}, 'dateCreated': '2026-02-04T01:02:48-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T01:02:53-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 554347, 'bookSize': 20000000, 'longCount': 963, 'shortCount': 990, 'turnover': 0.0619, 'returns': 0.0054, 'drawdown': 0.2376, 'margin': 0.000174, 'sharpe': 0.07, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 465762, 'bookSize': 20000000, 'longCount': 961, 'shortCount': 998, 'turnover': 0.0369, 'returns': 0.0045, 'drawdown': 0.2206, 'margin': 0.000245, 'fitness': 0.01, 'sharpe': 0.07}, 'riskNeutralized': {'pnl': 69310, 'bookSize': 20000000, 'longCount': 963, 'shortCount': 990, 'turnover': 0.0619, 'returns': 0.0007, 'drawdown': 0.2235, 'margin': 2.2e-05, 'fitness': 0.0, 'sharpe': 0.01}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.07}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0619}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0619}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.49998}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.04, 'value': 0.0}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.31, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'rK6kQZaj', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_21v,10),0), greater(ts_delta(mdl25_vrv421_71v,10),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:33:58-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:33:59-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 207857, 'bookSize': 20000000, 'longCount': 153, 'shortCount': 1485, 'turnover': 0.4531, 'returns': 0.002, 'drawdown': 0.1325, 'margin': 9e-06, 'sharpe': 0.06, 'fitness': 0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1077971, 'bookSize': 20000000, 'longCount': 397, 'shortCount': 1587, 'turnover': 0.1224, 'returns': 0.0104, 'drawdown': 0.1071, 'margin': 0.000171, 'fitness': 0.07, 'sharpe': 0.25}, 'riskNeutralized': {'pnl': -695893, 'bookSize': 20000000, 'longCount': 153, 'shortCount': 1485, 'turnover': 0.4531, 'returns': -0.0067, 'drawdown': 0.2012, 'margin': -3e-05, 'fitness': -0.03, 'sharpe': -0.22}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.06}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4531}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4531}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.03, 'value': 0.11}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.57, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:34:16,031 - ace - ERROR - Simulation failed. {'id': '2UhEQJ52m4xcaqOB18WBH2B', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Required attribute "k" must have a value', 'location': {'line': 1, 'start': 0, 'end': 34, 'property': 'regular'}}

{'id': 'ak2J2qK9', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(sign(ts_zscore(mdl25_vrv421_71v,10)), sign(ts_zscore(mdl25_vrv421_91v,10)))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:35:26-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:35:26-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1662089, 'bookSize': 20000000, 'longCount': 1596, 'shortCount': 217, 'turnover': 0.1462, 'returns': 0.0161, 'drawdown': 0.117, 'margin': 0.00022, 'sharpe': 0.52, 'fitness': 0.17, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1410617, 'bookSize': 20000000, 'longCount': 1631, 'shortCount': 378, 'turnover': 0.0493, 'returns': 0.0137, 'drawdown': 0.1014, 'margin': 0.000554, 'fitness': 0.14, 'sharpe': 0.42}, 'riskNeutralized': {'pnl': 831624, 'bookSize': 20000000, 'longCount': 1596, 'shortCount': 217, 'turnover': 0.1462, 'returns': 0.0081, 'drawdown': 0.0774, 'margin': 0.00011, 'fitness': 0.08, 'sharpe': 0.32}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.52}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.17}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1462}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1462}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.27, 'value': 0.27}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.32, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '0mkok01v', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_21v,20), ts_zscore(mdl25_21v,180))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:35:29-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:35:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -2759439, 'bookSize': 20000000, 'longCount': 422, 'shortCount': 425, 'turnover': 0.376, 'returns': -0.0267, 'drawdown': 0.3099, 'margin': -0.000142, 'sharpe': -0.83, 'fitness': -0.22, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2610282, 'bookSize': 20000000, 'longCount': 592, 'shortCount': 609, 'turnover': 0.0968, 'returns': -0.0253, 'drawdown': 0.3014, 'margin': -0.000523, 'fitness': -0.36, 'sharpe': -0.8}, 'riskNeutralized': {'pnl': -1622506, 'bookSize': 20000000, 'longCount': 422, 'shortCount': 425, 'turnover': 0.376, 'returns': -0.0157, 'drawdown': 0.2007, 'margin': -8.4e-05, 'fitness': -0.12, 'sharpe': -0.58}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.83}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.22}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.376}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.376}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.43, 'value': -0.24}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.04, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'xAwMw0JW', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_01v,30), ts_mean(mdl25_vrv421_81v,180))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:35:29-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:35:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '9qPoP0q1', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'and(greater(ts_delta(mdl25_21v,10),0), greater(ts_ir(mdl25_21v,60),0))', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T03:35:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:35:30-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -644554, 'bookSize': 20000000, 'longCount': 234, 'shortCount': 1195, 'turnover': 0.4277, 'returns': -0.0062, 'drawdown': 0.2101, 'margin': -2.9e-05, 'sharpe': -0.19, 'fitness': -0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 397535, 'bookSize': 20000000, 'longCount': 427, 'shortCount': 1288, 'turnover': 0.1195, 'returns': 0.0039, 'drawdown': 0.099, 'margin': 6.4e-05, 'fitness': 0.02, 'sharpe': 0.11}, 'riskNeutralized': {'pnl': -560237, 'bookSize': 20000000, 'longCount': 234, 'shortCount': 1195, 'turnover': 0.4277, 'returns': -0.0054, 'drawdown': 0.2092, 'margin': -2.5e-05, 'fitness': -0.02, 'sharpe': -0.2}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.19}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4277}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4277}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2019-08-06', 'limit': 0.1, 'value': 0.170852}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.1, 'value': -0.19}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.18, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Jj0lq6wl', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(ts_mean(mdl25_01v,30))', 'description': 'Single-field ts_mean(mdl25_01v,30) then zscore per SUGGESTION1; SUGGESTION3 not required. KEEP_IN_MINDs kept. Confidence 0.65 smoothing reduces noise in accrual measures.', 'operatorCount': 2}, 'dateCreated': '2026-02-04T02:25:25-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:25:31-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 557287, 'bookSize': 20000000, 'longCount': 1393, 'shortCount': 671, 'turnover': 0.0333, 'returns': 0.0054, 'drawdown': 0.0976, 'margin': 0.000324, 'sharpe': 0.12, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1188851, 'bookSize': 20000000, 'longCount': 1352, 'shortCount': 719, 'turnover': 0.0295, 'returns': 0.0115, 'drawdown': 0.1205, 'margin': 0.00078, 'fitness': 0.08, 'sharpe': 0.26}, 'riskNeutralized': {'pnl': -1113957, 'bookSize': 20000000, 'longCount': 1393, 'shortCount': 671, 'turnover': 0.0333, 'returns': -0.0108, 'drawdown': 0.1152, 'margin': -0.000648, 'fitness': -0.12, 'sharpe': -0.41}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.12}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0333}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0333}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.06, 'value': -0.01}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.12, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'Jj0l001x', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_ir(mdl25_vrv421_71v,60), ts_returns(mdl25_vrv421_71v,21))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:36:35-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:36:35-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.73'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3362762, 'bookSize': 20000000, 'longCount': 995, 'shortCount': 1053, 'turnover': 0.3221, 'returns': 0.0326, 'drawdown': 0.0762, 'margin': 0.000202, 'sharpe': 0.62, 'fitness': 0.2, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2686332, 'bookSize': 20000000, 'longCount': 990, 'shortCount': 1068, 'turnover': 0.1142, 'returns': 0.026, 'drawdown': 0.0845, 'margin': 0.000456, 'fitness': 0.26, 'sharpe': 0.56}, 'riskNeutralized': {'pnl': 735800, 'bookSize': 20000000, 'longCount': 995, 'shortCount': 1053, 'turnover': 0.3221, 'returns': 0.0071, 'drawdown': 0.1551, 'margin': 4.4e-05, 'fitness': 0.02, 'sharpe': 0.16}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.62}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.2}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3221}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3221}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499672}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.32, 'value': 0.2}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.34, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:51:24,495 - ace - ERROR - Simulation failed. {'id': '1S90uq8XR4V29a2DAAxMMNF', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'At least one of "buckets", "range" is required', 'location': {'line': 1, 'start': 0, 'end': 47, 'property': 'regular'}}

{'id': 'qMkbvJqV', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(mdl25_vrv421_91v, 30), ts_zscore(mdl25_vrv421_71v, 30))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:52:27-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:52:28-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2528568, 'bookSize': 20000000, 'longCount': 748, 'shortCount': 1240, 'turnover': 0.6103, 'returns': 0.0245, 'drawdown': 0.0834, 'margin': 8e-05, 'sharpe': 0.75, 'fitness': 0.15, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 919108, 'bookSize': 20000000, 'longCount': 832, 'shortCount': 1173, 'turnover': 0.1483, 'returns': 0.0089, 'drawdown': 0.1061, 'margin': 0.00012, 'fitness': 0.07, 'sharpe': 0.27}, 'riskNeutralized': {'pnl': 1268356, 'bookSize': 20000000, 'longCount': 748, 'shortCount': 1240, 'turnover': 0.6103, 'returns': 0.0123, 'drawdown': 0.0664, 'margin': 4e-05, 'fitness': 0.07, 'sharpe': 0.49}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.75}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.15}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6103}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6103}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.39, 'value': 0.34}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.14, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '6XPx3LqO', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'winsorize(ts_zscore(mdl25_vrv421_81v, 30), std=3)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:52:29-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:52:29-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.65'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6380280, 'bookSize': 20000000, 'longCount': 980, 'shortCount': 1009, 'turnover': 0.3552, 'returns': 0.0618, 'drawdown': 0.0423, 'margin': 0.000348, 'sharpe': 2.29, 'fitness': 0.96, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3629568, 'bookSize': 20000000, 'longCount': 978, 'shortCount': 1028, 'turnover': 0.1153, 'returns': 0.0352, 'drawdown': 0.0656, 'margin': 0.00061, 'fitness': 0.75, 'sharpe': 1.41}, 'riskNeutralized': {'pnl': 2963606, 'bookSize': 20000000, 'longCount': 980, 'shortCount': 1009, 'turnover': 0.3552, 'returns': 0.0287, 'drawdown': 0.037, 'margin': 0.000162, 'fitness': 0.46, 'sharpe': 1.61}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.29}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.96}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3552}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3552}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.19, 'value': 1.16}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.86, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '6XPx3LPL', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_av_diff(mdl25_vrv421_81v, 30))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:52:28-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:52:29-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1191963, 'bookSize': 20000000, 'longCount': 1010, 'shortCount': 999, 'turnover': 0.4114, 'returns': 0.0116, 'drawdown': 0.511, 'margin': 5.6e-05, 'sharpe': 0.07, 'fitness': 0.01, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -2971965, 'bookSize': 20000000, 'longCount': 1006, 'shortCount': 1012, 'turnover': 0.0972, 'returns': -0.0288, 'drawdown': 0.4715, 'margin': -0.000592, 'fitness': -0.11, 'sharpe': -0.23}, 'riskNeutralized': {'pnl': 1721206, 'bookSize': 20000000, 'longCount': 1010, 'shortCount': 999, 'turnover': 0.4114, 'returns': 0.0167, 'drawdown': 0.4347, 'margin': 8.1e-05, 'fitness': 0.03, 'sharpe': 0.13}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.07}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.01}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4114}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4114}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499994}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.04, 'value': -0.02}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.79, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1J6Y8Vg', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_ir(mdl25_21v, 90)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:52:33-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:52:34-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5632799, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 1156, 'turnover': 0.1028, 'returns': 0.0546, 'drawdown': 0.0578, 'margin': 0.001061, 'sharpe': 1.7, 'fitness': 1.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4707879, 'bookSize': 20000000, 'longCount': 691, 'shortCount': 1174, 'turnover': 0.0484, 'returns': 0.0456, 'drawdown': 0.0701, 'margin': 0.001886, 'fitness': 0.83, 'sharpe': 1.37}, 'riskNeutralized': {'pnl': 3580526, 'bookSize': 20000000, 'longCount': 650, 'shortCount': 1156, 'turnover': 0.1028, 'returns': 0.0347, 'drawdown': 0.0388, 'margin': 0.000675, 'fitness': 0.84, 'sharpe': 1.59}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.7}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1028}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1028}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.88, 'value': 0.88}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 1.55, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'E503orx9', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_01v,30), ts_zscore(mdl25_vrv421_91v,30))', 'description': 'Subtract CFO/EV zscore from accruals quality to find accounting-driven names (mdl25_01v - mdl25_vrv421_91v). SUGGESTION1 two fields; concise. Confidence 0.66.', 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:27:51-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:27:55-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'kqkRbprP', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_rank(mdl25_01v, 60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:52:38-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:52:39-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -2777193, 'bookSize': 20000000, 'longCount': 869, 'shortCount': 1189, 'turnover': 0.0954, 'returns': -0.0269, 'drawdown': 0.3072, 'margin': -0.000564, 'sharpe': -0.95, 'fitness': -0.44, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1221348, 'bookSize': 20000000, 'longCount': 943, 'shortCount': 1126, 'turnover': 0.0602, 'returns': -0.0118, 'drawdown': 0.1487, 'margin': -0.000393, 'fitness': -0.12, 'sharpe': -0.39}, 'riskNeutralized': {'pnl': -3003452, 'bookSize': 20000000, 'longCount': 869, 'shortCount': 1189, 'turnover': 0.0954, 'returns': -0.0291, 'drawdown': 0.3119, 'margin': -0.00061, 'fitness': -0.86, 'sharpe': -1.79}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.95}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.44}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0954}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0954}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.49, 'value': -0.34}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.54, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:55:17,384 - ace - ERROR - Simulation failed. {'id': 'cchTs3kf4FL8WIZhQsQnwR', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Required attribute "k" must have a value', 'location': {'line': 1, 'start': 0, 'end': 29, 'property': 'regular'}}

{'id': 'd58qeERv', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_max_diff(mdl25_vrv421_81v,90)', 'description': 'Use ts_max_diff on FCF/EV (mdl25_vrv421_81v) to find sudden drops from historical peaks potentially oversold. SUGGESTION1 single field; implementation minimal. Confidence 0.60.', 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:28:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:28:06-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.7'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -6556862, 'bookSize': 20000000, 'longCount': 1530, 'shortCount': 480, 'turnover': 0.1636, 'returns': -0.0635, 'drawdown': 0.9262, 'margin': -0.000777, 'sharpe': -0.38, 'fitness': -0.24, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 5341207, 'bookSize': 20000000, 'longCount': 1365, 'shortCount': 653, 'turnover': 0.055, 'returns': 0.0518, 'drawdown': 0.4916, 'margin': 0.001881, 'fitness': 0.21, 'sharpe': 0.33}, 'riskNeutralized': {'pnl': -2677018, 'bookSize': 20000000, 'longCount': 1530, 'shortCount': 480, 'turnover': 0.1636, 'returns': -0.0259, 'drawdown': 0.7652, 'margin': -0.000317, 'fitness': -0.07, 'sharpe': -0.17}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.38}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.24}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1636}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1636}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-12-18', 'limit': 0.1, 'value': 0.499986}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.2, 'value': 0.06}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.62, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'XgwqLL81', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_product(sign(ts_delta(mdl25_21v, 1)), 5)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T03:56:28-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:56:28-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.56'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -755961, 'bookSize': 20000000, 'longCount': 11, 'shortCount': 12, 'turnover': 0.5195, 'returns': -0.0073, 'drawdown': 0.8351, 'margin': -2.8e-05, 'sharpe': -0.04, 'fitness': -0.0, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -6733303, 'bookSize': 20000000, 'longCount': 1089, 'shortCount': 901, 'turnover': 0.2707, 'returns': -0.0654, 'drawdown': 0.831, 'margin': -0.000483, 'fitness': -0.14, 'sharpe': -0.28}, 'riskNeutralized': {'pnl': 1769006, 'bookSize': 20000000, 'longCount': 11, 'shortCount': 12, 'turnover': 0.5195, 'returns': 0.0172, 'drawdown': 0.5468, 'margin': 6.6e-05, 'fitness': 0.02, 'sharpe': 0.1}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.04}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.0}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.5195}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.5195}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2017-09-11', 'limit': 0.1, 'value': 0.500004}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.02, 'value': -0.15}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.32, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'le6x22jA', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'tail(ts_zscore(mdl25_01v, 30), lower=-3, upper=3, newval=0)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:56:28-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:56:29-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.6'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'gJqvKRYv', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_zscore(ts_mean(mdl25_01v, 10), 30)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T03:57:00-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:57:00-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'VkwnEYAJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_rank(mdl25_vrv421_91v, 20)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:56:59-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:57:00-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6562753, 'bookSize': 20000000, 'longCount': 993, 'shortCount': 1010, 'turnover': 0.453, 'returns': 0.0636, 'drawdown': 0.047, 'margin': 0.000281, 'sharpe': 1.95, 'fitness': 0.73, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4143883, 'bookSize': 20000000, 'longCount': 983, 'shortCount': 1034, 'turnover': 0.134, 'returns': 0.0402, 'drawdown': 0.0682, 'margin': 0.000599, 'fitness': 0.76, 'sharpe': 1.39}, 'riskNeutralized': {'pnl': 1322527, 'bookSize': 20000000, 'longCount': 993, 'shortCount': 1010, 'turnover': 0.453, 'returns': 0.0128, 'drawdown': 0.04, 'margin': 5.7e-05, 'fitness': 0.13, 'sharpe': 0.79}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.95}, {'name': 'LOW_FITNESS', 'result': 'WARNING', 'limit': 1.0, 'value': 0.73}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.453}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.453}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'WARNING'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 1.01, 'value': 1.18}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'WARNING', 'value': 1.31, 'limit': 1.58}, {'name': 'POWER_POOL_CORRELATION', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'j2lLX90E', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_quantile(mdl25_vrv421_71v, 30, driver="gaussian")', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T03:57:06-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T03:57:06-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.71'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5889588, 'bookSize': 20000000, 'longCount': 1029, 'shortCount': 1032, 'turnover': 0.4108, 'returns': 0.0571, 'drawdown': 0.0417, 'margin': 0.000278, 'sharpe': 2.07, 'fitness': 0.77, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3855289, 'bookSize': 20000000, 'longCount': 1018, 'shortCount': 1049, 'turnover': 0.1268, 'returns': 0.0374, 'drawdown': 0.075, 'margin': 0.000589, 'fitness': 0.8, 'sharpe': 1.47}, 'riskNeutralized': {'pnl': 2153947, 'bookSize': 20000000, 'longCount': 1029, 'shortCount': 1032, 'turnover': 0.4108, 'returns': 0.0209, 'drawdown': 0.0278, 'margin': 0.000102, 'fitness': 0.28, 'sharpe': 1.25}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.07}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.77}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.4108}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.4108}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.08, 'value': 0.97}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.91, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 17:59:30,260 - ace - ERROR - Simulation failed. {'id': '8TLlvewF4Bda224bufGlct', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': '6XPx1ZA7', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(pasteurize(mdl25_21v))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T04:00:37-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:00:37-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7770304, 'bookSize': 20000000, 'longCount': 1079, 'shortCount': 910, 'turnover': 0.0208, 'returns': 0.0753, 'drawdown': 0.1047, 'margin': 0.007249, 'sharpe': 2.02, 'fitness': 1.57, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 7042850, 'bookSize': 20000000, 'longCount': 1059, 'shortCount': 936, 'turnover': 0.0169, 'returns': 0.0682, 'drawdown': 0.103, 'margin': 0.008076, 'fitness': 1.37, 'sharpe': 1.85}, 'riskNeutralized': {'pnl': 2701785, 'bookSize': 20000000, 'longCount': 1079, 'shortCount': 910, 'turnover': 0.0208, 'returns': 0.0262, 'drawdown': 0.0432, 'margin': 0.002521, 'fitness': 0.66, 'sharpe': 1.45}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 2.02}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.57}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0208}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0208}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.05, 'value': 0.91}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.65, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'kqkRXvag', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_ir(mdl25_vrv421_81v, 20)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T04:00:38-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:00:38-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 9035669, 'bookSize': 20000000, 'longCount': 954, 'shortCount': 1059, 'turnover': 0.254, 'returns': 0.0876, 'drawdown': 0.3954, 'margin': 0.000689, 'sharpe': 0.32, 'fitness': 0.19, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 11461099, 'bookSize': 20000000, 'longCount': 979, 'shortCount': 1041, 'turnover': 0.1271, 'returns': 0.1111, 'drawdown': 0.3815, 'margin': 0.001748, 'fitness': 0.56, 'sharpe': 0.6}, 'riskNeutralized': {'pnl': 3641956, 'bookSize': 20000000, 'longCount': 954, 'shortCount': 1059, 'turnover': 0.254, 'returns': 0.0353, 'drawdown': 0.553, 'margin': 0.000278, 'fitness': 0.05, 'sharpe': 0.14}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.32}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.19}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.254}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.254}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2015-07-20', 'limit': 0.1, 'value': 0.489345}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.17, 'value': 0.31}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.22, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'e78AKNQJ', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_max_diff(mdl25_vrv421_91v, 60)', 'description': None, 'operatorCount': 1}, 'dateCreated': '2026-02-04T04:00:37-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:00:37-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.67'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -9329206, 'bookSize': 20000000, 'longCount': 1538, 'shortCount': 472, 'turnover': 0.1903, 'returns': -0.0904, 'drawdown': 1.1864, 'margin': -0.00095, 'sharpe': -0.51, 'fitness': -0.35, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1547419, 'bookSize': 20000000, 'longCount': 1421, 'shortCount': 596, 'turnover': 0.0616, 'returns': 0.015, 'drawdown': 0.4817, 'margin': 0.000487, 'fitness': 0.03, 'sharpe': 0.09}, 'riskNeutralized': {'pnl': -6050968, 'bookSize': 20000000, 'longCount': 1538, 'shortCount': 472, 'turnover': 0.1903, 'returns': -0.0586, 'drawdown': 0.8742, 'margin': -0.000616, 'fitness': -0.21, 'sharpe': -0.37}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.51}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.35}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1903}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1903}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-11-15', 'limit': 0.1, 'value': 0.499992}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.27, 'value': -0.09}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.95, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'qMkbdYbj', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'hump(ts_zscore(mdl25_21v, 20), hump=0.01)', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T04:00:44-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:00:45-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2118094, 'bookSize': 20000000, 'longCount': 430, 'shortCount': 419, 'turnover': 0.181, 'returns': 0.0205, 'drawdown': 0.0848, 'margin': 0.000227, 'sharpe': 0.62, 'fitness': 0.21, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1447119, 'bookSize': 20000000, 'longCount': 624, 'shortCount': 596, 'turnover': 0.074, 'returns': 0.014, 'drawdown': 0.0908, 'margin': 0.000379, 'fitness': 0.15, 'sharpe': 0.44}, 'riskNeutralized': {'pnl': 1646347, 'bookSize': 20000000, 'longCount': 430, 'shortCount': 419, 'turnover': 0.181, 'returns': 0.016, 'drawdown': 0.113, 'margin': 0.000176, 'fitness': 0.18, 'sharpe': 0.59}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.62}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.21}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.181}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.181}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.32, 'value': 0.39}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.38, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'omw28Jl6', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'ts_covariance(mdl25_vrv421_71v, mdl25_vrv421_91v,60)', 'description': 'Two-field covariance using mdl25_vrv421_71v and mdl25_vrv421_91v per SUGGESTION1 to measure joint movement; SUGGESTION3 unnecessary. KEEP_IN_MINDs kept. Confidence 0.59 exploratory but can reveal structural alignment.', 'operatorCount': 1}, 'dateCreated': '2026-02-04T02:13:30-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T02:13:33-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.59'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 12153849, 'bookSize': 20000000, 'longCount': 359, 'shortCount': 1663, 'turnover': 0.0762, 'returns': 0.1178, 'drawdown': 0.4096, 'margin': 0.00309, 'sharpe': 0.59, 'fitness': 0.57, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1455596, 'bookSize': 20000000, 'longCount': 618, 'shortCount': 1410, 'turnover': 0.0478, 'returns': 0.0141, 'drawdown': 0.3919, 'margin': 0.000591, 'fitness': 0.03, 'sharpe': 0.09}, 'riskNeutralized': {'pnl': 3297782, 'bookSize': 20000000, 'longCount': 359, 'shortCount': 1663, 'turnover': 0.0762, 'returns': 0.032, 'drawdown': 0.4589, 'margin': 0.000838, 'fitness': 0.1, 'sharpe': 0.19}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.59}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.57}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0762}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0762}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-12-29', 'limit': 0.1, 'value': 0.5}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.31, 'value': 0.31}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.45, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'A1J6brad', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_zscore(mdl25_vrv421_81v, 20), ts_zscore(mdl25_21v, 90))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:00:46-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:00:47-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1136496, 'bookSize': 20000000, 'longCount': 823, 'shortCount': 838, 'turnover': 0.3801, 'returns': 0.011, 'drawdown': 0.0623, 'margin': 5.8e-05, 'sharpe': 0.39, 'fitness': 0.07, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1003315, 'bookSize': 20000000, 'longCount': 862, 'shortCount': 878, 'turnover': 0.1091, 'returns': 0.0097, 'drawdown': 0.0899, 'margin': 0.000178, 'fitness': 0.1, 'sharpe': 0.36}, 'riskNeutralized': {'pnl': -670426, 'bookSize': 20000000, 'longCount': 823, 'shortCount': 838, 'turnover': 0.3801, 'returns': -0.0065, 'drawdown': 0.1257, 'margin': -3.4e-05, 'fitness': -0.04, 'sharpe': -0.34}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.39}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.07}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.3801}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.3801}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.2, 'value': 0.2}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.88, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 18:06:24,491 - ace - ERROR - Simulation failed. {'id': '3qV5bXc5i4Ou8W6YRb2ZCoU', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}

{'id': 'O0wem99b', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(mdl25_vrv421_71v, 20), sign(ts_delta(mdl25_01v, 5)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T04:07:37-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:07:38-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 7488595, 'bookSize': 20000000, 'longCount': 714, 'shortCount': 778, 'turnover': 0.6587, 'returns': 0.0726, 'drawdown': 0.1037, 'margin': 0.00022, 'sharpe': 1.35, 'fitness': 0.45, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3228311, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 1037, 'turnover': 0.1622, 'returns': 0.0313, 'drawdown': 0.1013, 'margin': 0.000386, 'fitness': 0.2, 'sharpe': 0.45}, 'riskNeutralized': {'pnl': 5975209, 'bookSize': 20000000, 'longCount': 714, 'shortCount': 778, 'turnover': 0.6587, 'returns': 0.0579, 'drawdown': 0.1094, 'margin': 0.000176, 'fitness': 0.35, 'sharpe': 1.19}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 1.35}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.45}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.6587}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.6587}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2022-01-06', 'limit': 0.1, 'value': 0.118669}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.7, 'value': 0.69}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.39, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '88kA6LEz', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(mdl25_21v, 10), ts_zscore(mdl25_21v, 60))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:07:41-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:07:42-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.69'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -4572347, 'bookSize': 20000000, 'longCount': 180, 'shortCount': 316, 'turnover': 0.8983, 'returns': -0.0443, 'drawdown': 0.5422, 'margin': -9.9e-05, 'sharpe': -0.84, 'fitness': -0.19, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 996184, 'bookSize': 20000000, 'longCount': 398, 'shortCount': 484, 'turnover': 0.1423, 'returns': 0.0097, 'drawdown': 0.1246, 'margin': 0.000136, 'fitness': 0.04, 'sharpe': 0.17}, 'riskNeutralized': {'pnl': -3844525, 'bookSize': 20000000, 'longCount': 180, 'shortCount': 316, 'turnover': 0.8983, 'returns': -0.0373, 'drawdown': 0.4222, 'margin': -8.3e-05, 'fitness': -0.16, 'sharpe': -0.8}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.84}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.19}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.8983}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 0.8983}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.44, 'value': -0.66}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.3, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '0mkoQ8Yq', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'divide(ts_mean(mdl25_21v, 60), ts_std_dev(mdl25_21v, 60))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:07:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:07:41-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 5552848, 'bookSize': 20000000, 'longCount': 630, 'shortCount': 973, 'turnover': 0.1608, 'returns': 0.0538, 'drawdown': 0.049, 'margin': 0.000669, 'sharpe': 1.76, 'fitness': 1.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4777052, 'bookSize': 20000000, 'longCount': 706, 'shortCount': 1035, 'turnover': 0.0632, 'returns': 0.0463, 'drawdown': 0.0572, 'margin': 0.001465, 'fitness': 0.91, 'sharpe': 1.49}, 'riskNeutralized': {'pnl': 3628504, 'bookSize': 20000000, 'longCount': 630, 'shortCount': 973, 'turnover': 0.1608, 'returns': 0.0352, 'drawdown': 0.0278, 'margin': 0.000437, 'fitness': 0.76, 'sharpe': 1.63}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.76}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1608}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1608}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.91, 'value': 0.67}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'PASS', 'value': 1.66, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '587R6vJn', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'winsorize(ts_zscore(ts_mean(mdl25_vrv421_71v, 10), 30), std=3)', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:07:40-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:07:41-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.72'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 4950121, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 1042, 'turnover': 0.1453, 'returns': 0.048, 'drawdown': 0.0267, 'margin': 0.00066, 'sharpe': 1.92, 'fitness': 1.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 3363960, 'bookSize': 20000000, 'longCount': 1002, 'shortCount': 1057, 'turnover': 0.0814, 'returns': 0.0326, 'drawdown': 0.0578, 'margin': 0.000801, 'fitness': 0.69, 'sharpe': 1.36}, 'riskNeutralized': {'pnl': 2711306, 'bookSize': 20000000, 'longCount': 1005, 'shortCount': 1042, 'turnover': 0.1453, 'returns': 0.0263, 'drawdown': 0.0223, 'margin': 0.000362, 'fitness': 0.67, 'sharpe': 1.58}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'PASS', 'limit': 1.58, 'value': 1.92}, {'name': 'LOW_FITNESS', 'result': 'PASS', 'limit': 1.0, 'value': 1.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1453}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1453}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 1.0, 'value': 0.79}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.51, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVvmgPX', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'if_else(equal(ts_arg_max(mdl25_vrv421_91v, 10), 0), reverse(ts_zscore(mdl25_vrv421_91v, 5)), 0)', 'description': None, 'operatorCount': 5}, 'dateCreated': '2026-02-04T04:07:42-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:07:43-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -6074245, 'bookSize': 20000000, 'longCount': 1514, 'shortCount': 289, 'turnover': 1.0075, 'returns': -0.0589, 'drawdown': 0.6075, 'margin': -0.000117, 'sharpe': -1.53, 'fitness': -0.37, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -1566862, 'bookSize': 20000000, 'longCount': 1335, 'shortCount': 681, 'turnover': 0.2081, 'returns': -0.0152, 'drawdown': 0.2942, 'margin': -0.000146, 'fitness': -0.05, 'sharpe': -0.19}, 'riskNeutralized': {'pnl': -2254716, 'bookSize': 20000000, 'longCount': 1514, 'shortCount': 289, 'turnover': 1.0075, 'returns': -0.0218, 'drawdown': 0.2268, 'margin': -4.3e-05, 'fitness': -0.12, 'sharpe': -0.8}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.53}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.37}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 1.0075}, {'name': 'HIGH_TURNOVER', 'result': 'FAIL', 'limit': 0.7, 'value': 1.0075}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.8, 'value': -0.95}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -0.83, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'RRZXarga', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(ts_zscore(mdl25_01v, 30), inverse(ts_std_dev(mdl25_01v, 30)))', 'description': None, 'operatorCount': 4}, 'dateCreated': '2026-02-04T04:07:44-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:07:44-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.62'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 0, 'bookSize': 0, 'longCount': 0, 'shortCount': 0, 'turnover': 0.0, 'returns': 0.0, 'drawdown': 0.0, 'margin': 0.0, 'sharpe': 0.0, 'fitness': None, 'startDate': '2014-01-01', 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.0}, {'name': 'LOW_FITNESS', 'result': 'ERROR', 'limit': 1.0}, {'name': 'LOW_TURNOVER', 'result': 'FAIL', 'limit': 0.01, 'value': 0.0}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'ERROR'}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'IS_LADDER_SHARPE', 'result': 'PENDING'}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}

2026-02-04 18:23:25,684 - ace - ERROR - Simulation failed. {'id': '40Kl4cfBb4UD9QJikkXzst1', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Expression ends with group unit value', 'location': {'property': 'regular'}}
2026-02-04 18:23:25,691 - ace - ERROR - Simulation failed. {'id': '3eREGV4AD5evbrX19vLkAiFn', 'type': 'REGULAR', 'status': 'ERROR', 'message': 'Required attribute "k" must have a value', 'location': {'line': 1, 'start': 9, 'end': 38, 'property': 'regular'}}

{'id': '2rqEaQ9Z', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_returns(mdl25_vrv421_81v,20), ts_returns(mdl25_vrv421_91v,20))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:24:33-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:24:33-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.66'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -2974819, 'bookSize': 20000000, 'longCount': 1031, 'shortCount': 961, 'turnover': 0.2138, 'returns': -0.0288, 'drawdown': 0.5746, 'margin': -0.00027, 'sharpe': -0.27, 'fitness': -0.1, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 718164, 'bookSize': 20000000, 'longCount': 1032, 'shortCount': 974, 'turnover': 0.0902, 'returns': 0.007, 'drawdown': 0.295, 'margin': 0.000154, 'fitness': 0.02, 'sharpe': 0.07}, 'riskNeutralized': {'pnl': -526078, 'bookSize': 20000000, 'longCount': 1031, 'shortCount': 961, 'turnover': 0.2138, 'returns': -0.0051, 'drawdown': 0.3749, 'margin': -4.8e-05, 'fitness': -0.01, 'sharpe': -0.05}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -0.27}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.1}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2138}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2138}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499925}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': -0.14, 'value': -0.35}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.11, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '9qPoabGx', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(ts_returns(mdl25_vrv421_91v,20), ts_returns(mdl25_vrv421_91v,60))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:24:32-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:24:33-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.63'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 1053649, 'bookSize': 20000000, 'longCount': 1029, 'shortCount': 946, 'turnover': 0.2017, 'returns': 0.0102, 'drawdown': 0.253, 'margin': 0.000101, 'sharpe': 0.11, 'fitness': 0.02, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 4021630, 'bookSize': 20000000, 'longCount': 985, 'shortCount': 999, 'turnover': 0.0752, 'returns': 0.039, 'drawdown': 0.3759, 'margin': 0.001037, 'fitness': 0.19, 'sharpe': 0.34}, 'riskNeutralized': {'pnl': 1401327, 'bookSize': 20000000, 'longCount': 1029, 'shortCount': 946, 'turnover': 0.2017, 'returns': 0.0136, 'drawdown': 0.1908, 'margin': 0.000135, 'fitness': 0.04, 'sharpe': 0.15}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.11}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.02}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.2017}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.2017}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2022-04-29', 'limit': 0.1, 'value': 0.499871}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.06, 'value': 0.33}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.28, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'e78AdgEz', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'zscore(winsorize(mdl25_vrv421_81v, std=4))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T04:24:34-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:24:34-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.64'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 6979933, 'bookSize': 20000000, 'longCount': 1014, 'shortCount': 996, 'turnover': 0.1437, 'returns': 0.0676, 'drawdown': 0.0673, 'margin': 0.000941, 'sharpe': 1.3, 'fitness': 0.89, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 5541317, 'bookSize': 20000000, 'longCount': 1009, 'shortCount': 1009, 'turnover': 0.0444, 'returns': 0.0537, 'drawdown': 0.149, 'margin': 0.002416, 'fitness': 0.73, 'sharpe': 1.12}, 'riskNeutralized': {'pnl': 3793439, 'bookSize': 20000000, 'longCount': 1014, 'shortCount': 996, 'turnover': 0.1437, 'returns': 0.0368, 'drawdown': 0.0607, 'margin': 0.000511, 'fitness': 0.47, 'sharpe': 0.92}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 1.3}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.89}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1437}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1437}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499658}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.68, 'value': 0.63}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 1.11, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '6XPxa10K', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'multiply(quantile(mdl25_vrv421_71v), quantile(mdl25_21v))', 'description': None, 'operatorCount': 3}, 'dateCreated': '2026-02-04T04:24:45-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:24:46-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.68'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': -5100803, 'bookSize': 20000000, 'longCount': 728, 'shortCount': 1254, 'turnover': 0.0321, 'returns': -0.0494, 'drawdown': 0.5347, 'margin': -0.003083, 'sharpe': -1.32, 'fitness': -0.83, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': -5265541, 'bookSize': 20000000, 'longCount': 763, 'shortCount': 1226, 'turnover': 0.0226, 'returns': -0.051, 'drawdown': 0.5466, 'margin': -0.004512, 'fitness': -0.87, 'sharpe': -1.36}, 'riskNeutralized': {'pnl': -1921700, 'bookSize': 20000000, 'longCount': 728, 'shortCount': 1254, 'turnover': 0.0321, 'returns': -0.0186, 'drawdown': 0.2113, 'margin': -0.001162, 'fitness': -0.33, 'sharpe': -0.86}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': -1.32}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': -0.83}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.0321}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.0321}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': -0.69, 'value': -0.52}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': -1.31, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': 'mL2OrA19', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'subtract(mdl25_vrv421_71v, ts_mean(mdl25_vrv421_71v,90))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T04:24:45-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:24:46-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.61'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 2864296, 'bookSize': 20000000, 'longCount': 1024, 'shortCount': 1038, 'turnover': 0.1078, 'returns': 0.0278, 'drawdown': 0.2373, 'margin': 0.000515, 'sharpe': 0.26, 'fitness': 0.12, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 2433776, 'bookSize': 20000000, 'longCount': 1024, 'shortCount': 1043, 'turnover': 0.0582, 'returns': 0.0236, 'drawdown': 0.231, 'margin': 0.000811, 'fitness': 0.12, 'sharpe': 0.28}, 'riskNeutralized': {'pnl': 2356159, 'bookSize': 20000000, 'longCount': 1024, 'shortCount': 1038, 'turnover': 0.1078, 'returns': 0.0228, 'drawdown': 0.2296, 'margin': 0.000424, 'fitness': 0.12, 'sharpe': 0.28}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.26}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.12}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.1078}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.1078}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'FAIL', 'date': '2023-10-24', 'limit': 0.1, 'value': 0.499996}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'PASS', 'limit': 0.14, 'value': 0.21}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.15, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
{'id': '1YVvaL0W', 'type': 'REGULAR', 'author': 'PS40111', 'settings': {'instrumentType': 'EQUITY', 'region': 'EUR', 'universe': 'TOP2500', 'delay': 1, 'decay': 0, 'neutralization': 'INDUSTRY', 'truncation': 0.08, 'pasteurization': 'ON', 'unitHandling': 'VERIFY', 'nanHandling': 'OFF', 'maxTrade': 'OFF', 'language': 'FASTEXPR', 'visualization': False, 'startDate': '2014-01-01', 'endDate': '2023-12-31'}, 'regular': {'code': 'reverse(ts_std_dev(mdl25_01v,30))', 'description': None, 'operatorCount': 2}, 'dateCreated': '2026-02-04T04:24:45-05:00', 'dateSubmitted': None, 'dateModified': '2026-02-04T04:24:46-05:00', 'name': None, 'favorite': False, 'hidden': False, 'color': None, 'category': None, 'tags': ['ace_tag', 'llm_test', 'confidence_0.56'], 'classifications': [{'id': 'DATA_USAGE:SINGLE_DATA_SET', 'name': 'Single Data Set Alpha'}], 'grade': None, 'stage': 'IS', 'status': 'UNSUBMITTED', 'is': {'pnl': 3773326, 'bookSize': 20000000, 'longCount': 1651, 'shortCount': 361, 'turnover': 0.093, 'returns': 0.0366, 'drawdown': 0.055, 'margin': 0.000787, 'sharpe': 0.82, 'fitness': 0.44, 'startDate': '2014-01-01', 'investabilityConstrained': {'pnl': 1139709, 'bookSize': 20000000, 'longCount': 1558, 'shortCount': 512, 'turnover': 0.0652, 'returns': 0.011, 'drawdown': 0.1723, 'margin': 0.000339, 'fitness': 0.07, 'sharpe': 0.24}, 'riskNeutralized': {'pnl': 2762034, 'bookSize': 20000000, 'longCount': 1651, 'shortCount': 361, 'turnover': 0.093, 'returns': 0.0268, 'drawdown': 0.0614, 'margin': 0.000576, 'fitness': 0.35, 'sharpe': 0.75}, 'checks': [{'name': 'LOW_SHARPE', 'result': 'FAIL', 'limit': 1.58, 'value': 0.82}, {'name': 'LOW_FITNESS', 'result': 'FAIL', 'limit': 1.0, 'value': 0.44}, {'name': 'LOW_TURNOVER', 'result': 'PASS', 'limit': 0.01, 'value': 0.093}, {'name': 'HIGH_TURNOVER', 'result': 'PASS', 'limit': 0.7, 'value': 0.093}, {'name': 'CONCENTRATED_WEIGHT', 'result': 'PASS'}, {'name': 'LOW_SUB_UNIVERSE_SHARPE', 'result': 'FAIL', 'limit': 0.43, 'value': 0.34}, {'name': 'SELF_CORRELATION', 'result': 'PENDING'}, {'name': 'DATA_DIVERSITY', 'result': 'PENDING'}, {'name': 'PROD_CORRELATION', 'result': 'PENDING'}, {'name': 'REGULAR_SUBMISSION', 'result': 'PENDING'}, {'name': 'LOW_2Y_SHARPE', 'result': 'FAIL', 'value': 0.65, 'limit': 1.58}, {'name': 'MATCHES_COMPETITION', 'result': 'PENDING', 'competitions': [{'id': 'AIACv2', 'name': 'AI Alphas Competition 2.0'}]}, {'result': 'PASS', 'name': 'MATCHES_PYRAMID', 'effective': 1, 'multiplier': 1.4, 'pyramids': [{'name': 'EUR/D1/MODEL', 'multiplier': 1.4}]}, {'result': 'WARNING', 'name': 'MATCHES_THEMES', 'themes': [{'id': 'EDrKL34', 'multiplier': 2.0, 'name': 'JPN Dataset Utilization Theme'}, {'id': 'M4ZYx3D', 'multiplier': 2.0, 'name': 'AMR Dataset Utilization Theme'}, {'id': '9B3qxZ4', 'multiplier': 2.0, 'name': 'KOR Dataset Utilization Theme'}, {'id': 'PBVkEJD', 'multiplier': 2.0, 'name': 'TWN Dataset Utilization Theme'}, {'id': 'by88rqy', 'multiplier': 2.0, 'name': 'HKG Dataset Utilization Theme'}, {'id': 'V45896D', 'multiplier': 1.0, 'name': 'GLB/D1 TOPDIV3000 Power Pool Feb`26 Theme'}]}]}, 'os': None, 'train': None, 'test': None, 'prod': None, 'competitions': None, 'themes': None, 'pyramids': None, 'pyramidThemes': None, 'team': None, 'osmosisPoints': None}
[BEST ALPHA SAVED] Sharpe=1.3000, ID=e78AdgEz, File=good_alpha_list.json

# LLM 함수 해설

In [ ]:
import random
# def generate_expressions_from_dataset(s, alpha_region, alpha_universe, dataset_id, model = 'gpt-5-mini-2025-08-07', datafields_num_cap = 500, alpha_num = 100, top_n_datafields = 3):

# 함수 인풋들
# 🔧 REGION / UNIVERSE GLOBALIZED
alpha_region = REGION
alpha_universe = UNIVERSE
dataset_id = TARGET_DATASET_ID
datafields_num_cap = 500
alpha_num = 100

# 🔧 NEW: 상위 N개 datafield만 사용하는 설정
top_n_datafields = 3

# 데이터셋에서 데이터필드 불러오기
data_fields = ace.get_datafields(s, region=alpha_region, universe=alpha_universe, dataset_id=dataset_id, data_type='ALL')
data_fields = data_fields[data_fields['type'] != "GROUP"]

# 🔧 NEW: alphaCount 기준 상위 N개 datafield만 선택
top_fields_df = data_fields.nlargest(top_n_datafields, "alphaCount")

# 🔧 NEW: LLM 입력용 compact datafield spec 생성 (토큰 절약)
# 필요한 키만 포함: id, description, subcategory, coverage, userCount, alphaCount, type
selected_datafields_spec = top_fields_df[[
    "id",
    "description", 
    "subcategory",
    "coverage",
    "userCount",
    "alphaCount",
    "type"  # VECTOR / MATRIX 구분용
]].to_dict("records")

print(f"[INFO] Selected top {len(selected_datafields_spec)} datafields for dataset '{dataset_id}':")
for df_spec in selected_datafields_spec:
    print(f"  - {df_spec.get('id', 'N/A')} (alphaCount: {df_spec.get('alphaCount', 'N/A')}, type: {df_spec.get('type', 'N/A')})")

# 오퍼레이터도 같은 방식으로 만들어 줌
operators = ace.get_operators(s)
operators_list = [row.to_dict() for row in operators[operators['scope']=='REGULAR'].iloc]

# rank는 LLM이 너무 많이 씀 - 빼줌
operator_exclude = ['rank']
operators_list = [x for x in operators_list if x['name'] not in operator_exclude]


answer_form = '''{
    "results":[
        {
            "idea":...,
            "description":...,
            "implementation":...,
            "confidence_level":...
        }
    ]
}'''

# 🔧 MODIFIED: 프롬프트에 ALLOWED_DATAFIELDS 섹션 추가 및 KEEP_IN_MIND 업데이트
prompt = f"""
<MISSION>
Based on the OPERATORS and ALLOWED_DATAFIELDS below,
1. SUGGEST {alpha_num} SEPARATED and DIVERSIFIED Alpha ideas which can create excess return in the market
2. Divide your idea into 4 parts, "idea", "description", "implementation", and "target".
3. "idea" must contain the core idea of the alpha.
4. "description" must include how you considered SUGGESTIONS and KEEP_IN_MINDs, and how much you set the confidence of this alpha. Consider SUGGESTIONS and write the reason you applied or didn't apply each of the SUGGESTIONS.
5. "implementation" must contain implementation of the variation, including specific template (in OPERATOR(MATRIX) form) or exact name of datafield.
6. "confidence_level" should be numerical value set in description, in 0-1 scale. Bigger value means higher confidence of this alpha idea.
Very new user can understand the idea and how to implement this idea.
</MISSION>

<SUGGESTIONS>
SUGGESTION1: Actively use MULTIPLE datafields from ALLOWED_DATAFIELDS. Your main mission is finding great combinations of the allowed datafields.
SUGGESTION2: If a datafield has type=VECTOR, wrap it with vec_avg() or vec_sum() operator.
SUGGESTION3: If the datafield's coverage is lower than 0.6, try using ts_backfill() to preprocess the data.
SUGGESTION4: datafields' userCount and alphaCount are the count of users and alphas submitted. Try to use high user and alphaCount so that you can catch the signal easily.
</SUGGESTIONS>

<KEEP_IN_MIND>
KEEP_IN_MIND1: Final implementation MUST NOT be too long.
KEEP_IN_MIND2: Final implementation MUST NOT contain over 7 operators and over 2 datafields.
KEEP_IN_MIND3: You MUST ONLY use datafield IDs from ALLOWED_DATAFIELDS. Using any datafield outside this list is INVALID.
KEEP_IN_MIND4: You CANNOT use type=GROUP field by itself. You need to use it as "group" parameter in Group operator.
KEEP_IN_MIND5: If a datafield has type=VECTOR, it MUST be wrapped with vec_avg() or vec_sum() operator.
KEEP_IN_MIND6: you should ONLY use Datafields which is in {selected_datafields_spec}. Do not use other datafield.
</KEEP_IN_MIND>

<OPERATORS>
You can use those operators: {operators_list}
</OPERATORS>

<ALLOWED_DATAFIELDS>
Available datafields = {selected_datafields_spec}

</ALLOWED_DATAFIELDS>

<ANSWER_FORMAT>
You must answer in this form 
{answer_form}
</ANSWER_FORMAT>
""".strip()


print(prompt)

[INFO] Selected top 3 datafields for dataset 'model25':
  - mdl25_vrv421_71v (alphaCount: 1255, type: MATRIX)
  - mdl25_21v (alphaCount: 720, type: MATRIX)
  - mdl25_vrv421_81v (alphaCount: 628, type: MATRIX)
<MISSION>
Based on the OPERATORS and ALLOWED_DATAFIELDS below,
1. SUGGEST 100 SEPARATED and DIVERSIFIED Alpha ideas which can create excess return in the market
2. Divide your idea into 4 parts, "idea", "description", "implementation", and "target".
3. "idea" must contain the core idea of the alpha.
4. "description" must include how you considered SUGGESTIONS and KEEP_IN_MINDs, and how much you set the confidence of this alpha. Consider SUGGESTIONS and write the reason you applied or didn't apply each of the SUGGESTIONS.
5. "implementation" must contain implementation of the variation, including specific template (in OPERATOR(MATRIX) form) or exact name of datafield.
6. "confidence_level" should be numerical value set in description, in 0-1 scale. Bigger value means higher confidence of this alpha idea.
Very new user can understand the idea and how to implement this idea.
</MISSION>

<SUGGESTIONS>
SUGGESTION1: Actively use MULTIPLE datafields from ALLOWED_DATAFIELDS. Your main mission is finding great combinations of the allowed datafields.
SUGGESTION2: If a datafield has type=VECTOR, wrap it with vec_avg() or vec_sum() operator.
SUGGESTION3: If the datafield's coverage is lower than 0.6, try using ts_backfill() to preprocess the data.
SUGGESTION4: datafields' userCount and alphaCount are the count of users and alphas submitted. Try to use high user and alphaCount so that you can catch the signal easily.
</SUGGESTIONS>

<KEEP_IN_MIND>
KEEP_IN_MIND1: Final implementation MUST NOT be too long.
KEEP_IN_MIND2: Final implementation MUST NOT contain over 7 operators and over 2 datafields.
KEEP_IN_MIND3: You MUST ONLY use datafield IDs from ALLOWED_DATAFIELDS. Using any datafield outside this list is INVALID.
KEEP_IN_MIND4: You CANNOT use type=GROUP field by itself. You need to use it as "group" parameter in Group operator.
KEEP_IN_MIND5: If a datafield has type=VECTOR, it MUST be wrapped with vec_avg() or vec_sum() operator.
</KEEP_IN_MIND>

<OPERATORS>