In [34]:
# !pip install pandas
# !pip install numpy
# !pip install matplotlib
# !pip install networkx
# !pip install requests
# !pip install openai
# !pip install nest_asyncio
# !pip install tqdm
# !pip install Jinja2
# USA = [TOP3000, TOP1000, TOP500, TOP200, ILLIQUID_MINVOL1M, TOPSP500]

# GLB = [TOP3000, MINVOL1M, TOPDIV3000]

# EUR = [TOP2500, TOP1200, TOP800, TOP400, ILLIQUID_MINVOL1M]

# ASI = [MINVOL1M, ILLIQUID_MINVOL1M]

# LLM으로 알파 생성하기
* LLM이 발달하면서 이제 mini 등 가벼운 모델로도 알파를 꽤나 쉽게 만들 수 있는 환경이 되었습니다. 
* 오늘 돌리면서 한 쿼리를 6번 정도 날렸는데 $0.4 정도가 나왔습니다. 
* 한 번 알파 100개 만드는 시도를 할 때 약 100원 정도 들어간다고 생각하시면 될 것 같습니다.
* 사양이 괜찮으신 분들은 (또는 최신 맥북을 쓰신다면) ollama로 로컬 LLM도 한번 써보세요! 생각보다 괜찮습니다 성능이

# 데이터필드 정보 저장하기
현재 설정: **REGION / UNIVERSE** (글로벌 변수 참조)
처음 실행 시 30분-1시간 정도 걸리는 작업입니다.

In [35]:
# 처음에만 진행하시면 됩니다.
# 🔧 REGION / UNIVERSE GLOBALIZED - 글로벌 설정
REGION = "EUR"
UNIVERSE = "TOP2500"
DELAY = "1"

import AAF as aaf
import ace_lib as ace

# 세팅 
settings = {

    "nan_handling" : "OFF",
    "instrumentType": "EQUITY",      # FIXED
    "delay"          : 1,
    "universe"       : UNIVERSE,     # 🔧 REGION / UNIVERSE GLOBALIZED
    "truncation"     : 0.01,
    "unitHandling"   : "VERIFY",     # FIXED
    "pasteurization" : "ON",
    "region"         : REGION,       # 🔧 REGION / UNIVERSE GLOBALIZED
    "language"       : "FASTEXPR",   # FIXED
    "neutralization" : "INDUSTRY",     # Can be varied
    "visualization"  : False
}

In [36]:
s = ace.start_session()
operators = ace.get_operators(s)

# aaf.initiate_datafield(s,settings)

Complete biometrics authentication and press any key to continue:
https://api.worldquantbrain.com/authentication/persona?inquiry=inq_WaTMmpYU5vRLH3dHEgF2wE2M3GP3

In [37]:
# 🔧 REGION / UNIVERSE GLOBALIZED
datasets_df = ace.get_datasets(
    s, 
    instrument_type='EQUITY', 
    region=REGION, 
    universe=UNIVERSE,
    delay=1, 
)
selected_datasets_df = datasets_df[
    (datasets_df["alphaCount"] >-1)]
selected_datasets_df

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
0,analyst10,Performance-Weighted Analyst Estimates,"This dataset provides ""smart estimates,"" which...","{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.7760,...,926,3515,916,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
1,analyst11,ESG scores,This dataset provides a comprehensive mapping ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8489,...,179,426,445,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
2,analyst14,Estimations of Key Fundamentals,This dataset reports many items from financial...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.5000,...,819,2859,121,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
3,analyst15,Earnings forecasts,This dataset provides bottom-up forecast data ...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-analyst-estimates', 'name': 'A...",EUR,1,TOP2500,1.0,0.9102,...,1448,10756,1701,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-analyst-estimates,Analyst Estimates
4,analyst39,Analyst estimates & financial ratios,This dataset contains detailed point-in-time c...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8755,...,597,3148,24,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,shortinterest6,SmartHoldings Model,This dataset is a global stock selection model...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-estimates-models', 'name': 'Esti...",EUR,1,TOP2500,1.0,1.0000,...,50,130,11,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-estimates-models,Estimates Models
126,socialmedia12,Sentiment Data for Equity,This dataset aggregates and analyzes social me...,"{'id': 'socialmedia', 'name': 'Social Media'}","{'id': 'socialmedia-social-media', 'name': 'So...",EUR,1,TOP2500,1.0,0.7836,...,474,1367,6,1.1,[],"[{'type': 'research', 'title': 'Creating D0 Al...",socialmedia,Social Media,socialmedia-social-media,Social Media
127,socialmedia15,Sentiment Indicators,A dataset model providing normalized sentiment...,"{'id': 'socialmedia', 'name': 'Social Media'}","{'id': 'socialmedia-social-media', 'name': 'So...",EUR,1,TOP2500,1.0,0.2726,...,290,740,13,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",socialmedia,Social Media,socialmedia-social-media,Social Media
128,univ1,Universe Dataset,No dataset description,"{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",EUR,1,TOP2500,1.0,0.7500,...,0,0,4,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",pv,Price Volume,pv-price-volume,Price Volume
129,univ2,Universe Dataset,No dataset description,"{'id': 'pv', 'name': 'Price Volume'}","{'id': 'pv-price-volume', 'name': 'Price Volume'}",EUR,1,TOP2500,NaN,0.6700,...,0,0,1,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",pv,Price Volume,pv-price-volume,Price Volume

In [ ]:
selected_df = datasets_df[datasets_df['alphaCount']>1]
#     "USA": ['analyst12', 'analyst2', 'analyst48', 'analyst9', 'fundamental21', 'fundamental85',
#  'fundamental91', 'macro10', 'macro52', 'model239', 'model240', 'model46', 'model54',
#  'model57', 'news31', 'news5', 'news50', 'news54', 'news79', 'option10', 'option13',
#  'option22', 'other323', 'other492', 'other696', 'sentiment18', 'shortinterest3',
#  'shortinterest36', 'socialmedia3', 'socialmedia8']
# ,
#     "EUR": ['analyst39', 'earnings3', 'model109', 'model138', 'model139', 'model176', 'model25',
#  'model28', 'model30', 'model39', 'news104', 'news17', 'news23', 'news46', 'news79',
#  'other197', 'other455', 'other696', 'risk59', 'risk60', 'risk88',
#  'shortinterest3', 'shortinterest37', 'socialmedia39']
# ,
#     "ASI": ['analyst44', 'analyst48', 'analyst69', 'analyst9', 'fundamental17', 'fundamental21',
#  'fundamental23', 'fundamental28', 'fundamental44', 'fundamental6', 'fundamental72',
#  'model106', 'model109', 'model138', 'model16', 'model262', 'model53', 'model77',
#  'other128', 'other455', 'other463', 'other675', 'pv13', 'risk74', 'risk88',
#  'shortinterest37']
# ,
#     "GLB": ['analyst11', 'analyst35', 'analyst44', 'analyst48', 'analyst82', 'analyst9',
#  'fundamental45', 'fundamental46', 'fundamental6', 'fundamental7', 'fundamental72',
#  'model106', 'model16', 'model162', 'model262', 'news52', 'news76', 'other128',
#  'other169', 'other463', 'other675', 'pv13', 'pv30', 'pv53', 'risk74', 'risk88',
#  'shortinterest37']
dataset_ids =  ['analyst39', 'earnings3', 'model109', 'model138', 'model139', 'model176', 'model25',
  'model28', 'model30', 'model39', 'news104', 'news17', 'news23', 'news46', 'news79',
  'other197', 'other455', 'other696', 'risk59', 'risk60', 'risk88',
  'shortinterest3', 'shortinterest37', 'socialmedia39']
saved_fields =[]

# 🔧 REGION / UNIVERSE GLOBALIZED
for i in range (0,len(dataset_ids)):
    datafields_df = ace.get_datafields(s, dataset_id=dataset_ids[i], delay=1, region=REGION, universe=UNIVERSE)
    saved_fields.append(datafields_df[:2])

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:44,930 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=model109

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:45,497 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=model176

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:52,705 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=news104
2026-02-07 14:58:52,898 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=news17

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:53,461 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=news79

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}
get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:54,025 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=other696

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:57,681 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=risk60
2026-02-07 14:58:58,094 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=risk88

get_datafields unexpected response status= 429 text= {
  "message":"API rate limit exceeded"
}

2026-02-07 14:58:58,468 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=shortinterest37
2026-02-07 14:58:58,660 - ace - WARNING - No fields found: region=EUR, delay=1, universe=TOP2500, type=MATRIX, dataset.id=socialmedia39

In [49]:
filtered_df = selected_df[
    selected_df['id'].str.split('_').str[0].isin(dataset_ids)
]
filtered_df = filtered_df.sort_values(
    by='alphaCount',
    ascending=False
)

filtered_df

,id,name,description,category,subcategory,region,delay,universe,dateCoverage,coverage,...,userCount,alphaCount,fieldCount,pyramidMultiplier,themes,researchPapers,category_id,category_name,subcategory_id,subcategory_name
41,model25,Earnings Quality,This model dataset provides with financial sta...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-revisions-models', 'name': 'Revi...",EUR,1,TOP2500,1.0,0.6591,...,1156,7036,199,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-revisions-models,Revisions Models
4,analyst39,Analyst estimates & financial ratios,This dataset contains detailed point-in-time c...,"{'id': 'analyst', 'name': 'Analyst'}","{'id': 'analyst-esg', 'name': 'ESG'}",EUR,1,TOP2500,1.0,0.8755,...,597,3148,24,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",analyst,Analyst,analyst-esg,ESG
32,model138,Stock Selection from Accounting-based Factors,This dataset contains a comprehensive suite of...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-mlai-models', 'name': 'ML/AI Mod...",EUR,1,TOP2500,1.0,0.5537,...,651,2723,120,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-mlai-models,ML/AI Models
92,other455,Relationship enhanced with AI/ML,Grouping data. Generated using deep learning m...,"{'id': 'other', 'name': 'Other'}","{'id': 'other-aiml-data', 'name': 'AI/ML Data'}",EUR,1,TOP2500,1.0,0.6380,...,495,2596,1200,1.6,[],"[{'type': 'discussion', 'title': 'Getting star...",other,Other,other-aiml-data,AI/ML Data
47,model30,EPS Estimate Model,This dataset provides detailed metrics on anal...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-estimates-models', 'name': 'Esti...",EUR,1,TOP2500,1.0,0.7130,...,448,1358,77,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-estimates-models,Estimates Models
115,risk60,Securities Lending Insight Data,"The dataset provides list of metrics, covering...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,1.0,0.9372,...,484,978,4,1.1,[],"[{'type': 'discussion', 'title': 'Getting star...",risk,Risk,risk-risk-models,Risk Models
55,model39,Valuation Momentum Data,This dataset integrates two advanced quantitat...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-valuation-models', 'name': 'Valu...",EUR,1,TOP2500,1.0,0.8044,...,285,954,24,1.4,[],"[{'type': 'research', 'title': 'Research Paper...",model,Model,model-valuation-models,Valuation Models
60,news17,PR Edition Data,"This dataset analyzes and structures news, pre...","{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",EUR,1,TOP2500,1.0,0.8014,...,214,516,75,1.5,[],"[{'type': 'discussion', 'title': 'Getting star...",news,News,news-news,News
69,news46,Relevant News Analytics Data,This dataset provides a comprehensive mapping ...,"{'id': 'news', 'name': 'News'}","{'id': 'news-news-sentiment', 'name': 'News Se...",EUR,1,TOP2500,1.0,0.9382,...,125,263,30,1.5,[],"[{'type': 'research', 'title': 'Creating D0 Al...",news,News,news-news-sentiment,News Sentiment
46,model28,Structural Credit Risk Model,This dataset provides a comprehensive mapping ...,"{'id': 'model', 'name': 'Model'}","{'id': 'model-risk-based-models', 'name': 'Ris...",EUR,1,TOP2500,1.0,0.8281,...,103,247,43,1.4,[],"[{'type': 'discussion', 'title': 'Getting star...",model,Model,model-risk-based-models,Risk Based Models
64,news23,MnA Deals Data,This dataset offers detailed information on me...,"{'id': 'news', 'name': 'News'}","{'id': 'news-news', 'name': 'News'}",EUR,1,TOP2500,1.0,0.4462,...,88,145,136,1.5,[],"[{'type': 'discussion', 'title': 'Getting star...",news,News,news-news,News

In [ ]:
# 특정 dataset_id에 속하는 datafield 스펙 보기
TARGET_DATASET_IDS = ["model25"]  # 원하는 dataset id로 변경 (복수 가능)

# 🔧 REGION / UNIVERSE GLOBALIZED
for _ds_id in TARGET_DATASET_IDS:
    # Brain API에서 해당 dataset의 datafield 목록 가져오기
    datafields_spec = ace.get_datafields(
        s, 
        region=REGION,
        universe=UNIVERSE,
        dataset_id=_ds_id,
        data_type='ALL'
    )

    # 표시할 컬럼 선택 (존재하는 컬럼만)
    display_cols = ['id', 'description', 'type', 'alphaCount', 'userCount', 'coverage']
    display_cols = [col for col in display_cols if col in datafields_spec.columns]

    # alphaCount 기준 내림차순 정렬 후 표시
    # datafields_spec = datafields_spec[display_cols].sort_values(by='alphaCount', ascending=False)
    print(f"\nDataset: {_ds_id} | Total datafields: {len(datafields_spec)}")
    display(datafields_spec)

Dataset: risk60 | Total datafields: 4

,id,description,dataset,category,subcategory,region,delay,universe,type,dateCoverage,...,userCount,alphaCount,pyramidMultiplier,themes,dataset_id,dataset_name,category_id,category_name,subcategory_id,subcategory_name
0,rsk60_crowding,Crowding is a daily score for shorting and cov...,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,0.8089,...,67,124,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models
1,rsk60_datatime,Time data,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,1.0000,...,50,94,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models
2,rsk60_last,The last rate is the financing rate at which w...,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,1.0000,...,262,434,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models
3,rsk60_offer,The offer rate is the financing rate at which ...,"{'id': 'risk60', 'name': 'Securities Lending I...","{'id': 'risk', 'name': 'Risk'}","{'id': 'risk-risk-models', 'name': 'Risk Models'}",EUR,1,TOP2500,VECTOR,1.0000,...,253,442,1.1,[],risk60,Securities Lending Insight Data,risk,Risk,risk-risk-models,Risk Models

# Expression Sanity checker
데이터필드 정보를 이용해서, LLM이 만든 expression이 실제 브레인에서 돌아갈 수 있는지를 체크합니다.

In [42]:
import llm_functions as llm
from parser import *
import ace_lib as ace
import numpy as np
import pandas as pd
import os 
import json
import asyncio



# 🔧 REGION / UNIVERSE GLOBALIZED
datafields = llm.import_json(f'datafield/1/{REGION}/{UNIVERSE}/1_{REGION}_{UNIVERSE}_total.json')
operators = llm.import_json('operators_list.json')

def return_type(node, operators, datafields):
    if node.node_type == 'operator':
        return operators[node.value]['output']

    elif node.node_type == 'number':
        return "NUMBER"

    elif node.node_type == 'datafield':
        if node.value.lower() == 'nan':
            return "MATRIX"
        return datafields[node.value]['type']

    else:
        return "SPECIAL_ARGUMENT"


def check_input(operator_inputs, children_types, _debug = False):
    if _debug: print(operator_inputs)
    while len(operator_inputs) != 0:

        operator_input = operator_inputs.pop(0)
        if _debug: print(f"operator input: {operator_input}, remain inputs: {len(operator_inputs)}" )

        if operator_input == '_SPECIAL_ARGUMENT':
            if len(children_types) == 0:
                pass
            elif children_types[0] == '_SPECIAL_ARGUMENT':
                if _debug: print(operator_input)
                if _debug: print(children_types.pop(0))
            else:
                pass

        else:
            if len(children_types) == 0:
                return False

            children_type = children_types.pop(0)
            if operator_input == "MATRIX" and children_type == "NUMBER":
                pass
            elif operator_input != children_type:
                if _debug: print(operator_input ,children_type, operator_input == children_type)
                return False

    return True


def sanity_checker(exp, _debug=False):

    try:
        exp_tree = tree_node(exp)

        for node in [node for node in exp_tree.collect_all_nodes() if node.node_type == "operator"]:

            if check_input(eval(operators[node.value]['input']), [return_type(x,operators, datafields) for x in node.children]):
                if _debug: print(check_input(eval(operators[node.value]['input']), [return_type(x) for x in node.children]))
            else:
                return False
        if return_type(exp_tree,operators, datafields)=="MATRIX":
            return True

        else:
            return False
    except Exception as e:
        print(f"err: {e}")
        return False

## Sanity check 예시

In [43]:
sanity_checker('bucet(rank(mdl138_4idpc), range="0,100,10)")') # 이상한 수식, False

err: 'bucet'

False

In [44]:
sanity_checker('ts_backfill(mdl138_4idpc,60)') # 정상적인 expression, True

True

# 탐색 데이터셋 설정
여기서는 데이터셋 카테고리별로 User Count가 가장 높은 순으로 정렬해서 탐색

In [45]:
#s = ace.start_session()

# 🔧 REGION / UNIVERSE GLOBALIZED - 글로벌 변수 사용
region = REGION
universe = UNIVERSE

datafields = llm.import_json(f'datafield/1/{region}/{universe}/1_{region}_{universe}_total.json')
operators = llm.import_json('operators_list.json')

# ============================================================
# 탐색할 dataset 직접 지정 (하드코딩)
# ============================================================
ALLOWED_DATASETS = TARGET_DATASET_IDS  # 위에서 설정한 리스트 그대로 사용

# Brain API에서 전체 datasets 정보 가져오기 (datasets_dict 구성용)
datasets = ace.get_datasets(s, region=region, universe=universe)
datasets = datasets.drop_duplicates(['id'])

# ALLOWED_DATASETS에 있는 것만 datasets_dict에 포함
datasets_filtered = datasets[datasets['id'].isin(ALLOWED_DATASETS)]
datasets_dict = {row['id']: row.to_dict() for _, row in datasets_filtered.iterrows()}

# datasets_list는 ALLOWED_DATASETS 그대로 사용
datasets_list = ALLOWED_DATASETS

print(f"Exploring datasets: {datasets_list}")

Exploring datasets: ['risk60']

## 시뮬레이션 하기에 앞서...
* 저카운트와 필드카운트에 따라 몇번 expression을 생성하고 돌릴지 결정 
* llm으로 만드는 알파들을 따로 json으로 저장
* csv 로드하고 저장하는 함수

In [ ]:
# ============================================================
# Seed-Alpha Pipeline: Utility Functions
# ============================================================
import os
import re
import json
import numpy as np
from parser import tree_node, classify_node

# ------------------------------------------------------------
# Kept from original: batch count calculator
# ------------------------------------------------------------
def datset_to_simnum(dataset):
    score = int(np.log10(datasets_dict[dataset]['userCount']+1) + datasets_dict[dataset]['fieldCount'])
    if score <= 3:
        return 1
    elif score <= 10:
        return 2
    elif score <= 50:
        return 3
    elif score <= 100:
        return 10
    else:
        return 20

# Kept from original: gen_json index helper
def get_json_num(dataset):
    json_list = [x for x in os.listdir('./gen_json/') if dataset in x]
    if len(json_list) == 0:
        return 0
    nums = [int(x.split('_')[-1].split('.')[0]) for x in json_list]
    return max(nums)+1


# ------------------------------------------------------------
# Seed-alpha structural validator
# ------------------------------------------------------------
HELPER_FIELDS = {'cap', 'industry', 'sector', 'subindustry'}

def is_valid_seed_alpha(expression):
    """
    Validate that an expression conforms to seed-alpha structural rules.
    
    Rules:
    - Must pass sanity_checker() type validation
    - Max tree depth: 3
    - Max operator count: 3
    - Only 1 unique non-helper datafield (helpers: cap, industry, sector, subindustry)
    
    Returns: (bool, reason_string)
    """
    # 1. Type validation via existing sanity_checker
    if not sanity_checker(expression):
        return (False, "failed sanity_checker type validation")
    
    # 2. Parse to tree
    try:
        root = tree_node(expression)
    except Exception as e:
        return (False, f"parse error: {e}")
    
    all_nodes = root.collect_all_nodes()
    
    # Classify all nodes
    for node in all_nodes:
        classify_node(node)
    
    # 3. Max depth check
    depth = root.calculate_depth()
    if depth > 3:
        return (False, f"depth {depth} > 3")
    
    # 4. Count operators
    op_nodes = [n for n in all_nodes if n.node_type == 'operator']
    if len(op_nodes) > 3:
        return (False, f"operator count {len(op_nodes)} > 3")
    
    # 5. Single signal datafield (only 1 unique non-helper)
    df_nodes = [n for n in all_nodes if n.node_type == 'datafield']
    signal_fields = set()
    for n in df_nodes:
        field_name = n.value.lower()
        if field_name not in HELPER_FIELDS and field_name != 'nan':
            signal_fields.add(field_name)
    
    if len(signal_fields) == 0:
        return (False, "no signal datafield found")
    if len(signal_fields) > 1:
        return (False, f"multiple signal datafields: {signal_fields}")
    
    return (True, "valid seed alpha")


# ============================================================
# Alpha Selection Criteria for per-dataset .txt files
# ============================================================
# SELECTION RULES:
#   Include alpha if ALL of:
#     (1) sharpe > 1.5
#     (2) fail_count == 0 (PASS) OR fail_count == 1
#
#   Discard if:
#     - sharpe <= 1.5
#     - fail_count >= 2
#     - simulation did not complete (record is None)
#
#   Warnings are always displayed but NEVER cause exclusion.
# ============================================================

def should_save_alpha(record):
    """
    Check if an alpha record meets the selection criteria for saving.
    
    Selection rules:
      - sharpe > 1.5
      - fail_count in {0, 1}
    
    Warnings do NOT affect selection - an alpha with warnings
    but sharpe > 1.5 and fail_count <= 1 is still saved.
    """
    if record is None:
        return False
    sharpe = record.get('sharpe', 0)
    if sharpe is None:
        sharpe = 0
    fail_count = record.get('fail_count', 99)
    return sharpe > 1.5 and fail_count <= 1


# ------------------------------------------------------------
# Extract simulation record from Brain API raw response
# ------------------------------------------------------------
def extract_sim_record(sim_result):
    """
    Extract structured dict from a single Brain API simulation result.
    
    Extracts:
      - Failed checks  (check result == 'FAIL')
      - Warning checks (check result not in {'PASS','FAIL'}, e.g. 'WARNING')
      - Top-level or is-level 'warnings' list if present
    
    Returns None if the result is invalid or simulation did not complete.
    """
    if not isinstance(sim_result, dict) or 'id' not in sim_result:
        return None
    
    is_data = sim_result.get('is', {})
    if not is_data:
        return None
    
    checks = is_data.get('checks', [])
    
    # Separate FAIL checks and WARNING checks
    failed = [c.get('name', '') for c in checks if c.get('result') == 'FAIL']
    warnings = [c.get('name', '') for c in checks
                if c.get('result') not in ('PASS', 'FAIL') and c.get('result')]
    
    # Also pick up any top-level or is-level 'warnings' list from the API
    for source in (is_data, sim_result):
        extra_w = source.get('warnings')
        if isinstance(extra_w, list):
            warnings.extend(str(w) for w in extra_w)
    
    settings = sim_result.get('settings', {})
    
    return {
        'alpha_id': sim_result['id'],
        'region': settings.get('region', ''),
        'universe': settings.get('universe', ''),
        'sharpe': is_data.get('sharpe', 0),
        'fitness': is_data.get('fitness', 0),
        'turnover': is_data.get('turnover', 0),
        'expression': sim_result.get('regular', {}).get('code', ''),
        'fail_count': len(failed),
        'failed_checks': failed,
        'warnings': warnings,
    }


# ------------------------------------------------------------
# Format one alpha entry for {dataset}.txt output
# ------------------------------------------------------------
# OUTPUT FORMAT (per entry block):
#
# ------------------------------------------------
# --- #<index> | FAIL: <fail_count> (<PASS/FAIL>) ---
# ID: <alpha_id>
# Region: <region>, Universe: <universe>
# Sharpe: <value>, Fitness: <value>, Turnover: <value>
# Expression: <full_expression>
# Status: <PASS/FAIL> (WARNINGS: <...>) (FAIL_REASONS: <...>)
# ------------------------------------------------
#
# - FAIL_REASONS omitted when fail_count == 0
# - WARNINGS omitted when no warnings exist
# - Expression kept on a single line
# ------------------------------------------------------------

def format_alpha_entry(idx, record):
    """Format one alpha record into the exact block format for {dataset}.txt."""
    fail_count = record.get('fail_count', 0)
    failed = record.get('failed_checks', [])
    warnings = record.get('warnings', [])
    
    label = "PASS" if fail_count == 0 else "FAIL"
    
    lines = []
    lines.append('-' * 48)
    lines.append(f"--- #{idx} | FAIL: {fail_count} ({label}) ---")
    lines.append(f"ID: {record.get('alpha_id', 'N/A')}")
    lines.append(f"Region: {record.get('region', '')}, Universe: {record.get('universe', '')}")
    lines.append(f"Sharpe: {record.get('sharpe', 0)}, Fitness: {record.get('fitness', 0)}, Turnover: {record.get('turnover', 0)}")
    lines.append(f"Expression: {record.get('expression', '')}")
    
    # Build Status line
    status_line = f"Status: {label}"
    if warnings:
        status_line += f" (WARNINGS: {', '.join(warnings)})"
    if failed:
        status_line += f" (FAIL_REASONS: {', '.join(failed)})"
    lines.append(status_line)
    
    lines.append('-' * 48)
    
    return '\n'.join(lines)


# ------------------------------------------------------------
# Load existing {dataset}.txt records
# Supports both old format ("Failed:" line) and new format
# ("Status:" line with WARNINGS/FAIL_REASONS).
# ------------------------------------------------------------
def load_existing_txt_records(dataset, output_dir='.'):
    """
    Parse existing {dataset}.txt back into record dicts.
    
    Returns list of dicts with keys:
      alpha_id, region, universe, sharpe, fitness, turnover,
      expression, fail_count, failed_checks, warnings
    """
    txt_path = os.path.join(output_dir, f"{dataset}.txt")
    if not os.path.exists(txt_path):
        return []
    
    records = []
    current = None
    
    with open(txt_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            
            # Skip separator / header / summary lines
            if line.startswith('=' * 10) or line.startswith('-' * 10):
                continue
            
            # Entry header: --- #N | FAIL: X ... ---
            m = re.match(r'^--- #\d+ \| FAIL: (\d+)', line)
            if m:
                if current and current.get('alpha_id'):
                    records.append(current)
                current = {
                    'fail_count': int(m.group(1)),
                    'failed_checks': [],
                    'warnings': [],
                    'alpha_id': '', 'region': '', 'universe': '',
                    'sharpe': 0, 'fitness': 0, 'turnover': 0,
                    'expression': '',
                }
                continue
            
            if current is None:
                continue
            
            if line.startswith('ID: '):
                current['alpha_id'] = line[4:].strip()
            
            elif line.startswith('Region: '):
                parts = line.split(', ')
                current['region'] = parts[0].replace('Region: ', '').strip()
                if len(parts) > 1:
                    current['universe'] = parts[1].replace('Universe: ', '').strip()
            
            elif line.startswith('Sharpe: '):
                for part in line.split(', '):
                    kv = part.split(': ', 1)
                    if len(kv) == 2:
                        k = kv[0].strip().lower()
                        try:
                            current[k] = float(kv[1].strip())
                        except (ValueError, TypeError):
                            current[k] = 0
            
            elif line.startswith('Expression: '):
                current['expression'] = line[12:].strip()
            
            # New format: "Status: PASS/FAIL (WARNINGS: ...) (FAIL_REASONS: ...)"
            elif line.startswith('Status: '):
                status_str = line[8:]
                warn_match = re.search(r'\(WARNINGS: ([^)]+)\)', status_str)
                if warn_match:
                    current['warnings'] = [w.strip() for w in warn_match.group(1).split(',')]
                fail_match = re.search(r'\(FAIL_REASONS: ([^)]+)\)', status_str)
                if fail_match:
                    current['failed_checks'] = [f.strip() for f in fail_match.group(1).split(',')]
            
            # Old format: "Failed: ..."
            elif line.startswith('Failed: '):
                current['failed_checks'] = [x.strip() for x in line[8:].split(',')]
    
    # Last entry
    if current and current.get('alpha_id'):
        records.append(current)
    
    return records


# ------------------------------------------------------------
# Write sorted, filtered, deduplicated {dataset}.txt
# ------------------------------------------------------------
# SORTING ORDER (applied after filtering & dedup):
#   1) fail_count ascending  (0 first, then 1)
#   2) sharpe descending     (highest first within same fail_count)
#
# DEDUPLICATION: by expression text (same expression not saved twice).
#   When duplicates exist, keep the one with lower fail_count / higher sharpe.
#
# The entire file is rewritten after each batch to guarantee sorting.
# ------------------------------------------------------------

def write_dataset_txt(dataset, records, region, universe, output_dir='.'):
    """
    Filter, deduplicate, sort, and write entries to {dataset}.txt.
    
    Selection filter (applied to every record):
      - sharpe > 1.5
      - fail_count in {0, 1}
    """
    # 1. Apply selection filter: sharpe > 1.5 AND fail_count in {0, 1}
    filtered = [r for r in records if should_save_alpha(r)]
    
    # 2. Pre-sort so best records come first (for dedup: keep first occurrence)
    filtered.sort(key=lambda r: (r.get('fail_count', 99), -(_safe_float(r.get('sharpe')))))
    
    # 3. Deduplicate by expression (keep first = best per sort above)
    seen_expr = set()
    unique_records = []
    for r in filtered:
        expr = r.get('expression', '').strip()
        if expr and expr not in seen_expr:
            seen_expr.add(expr)
            unique_records.append(r)
    
    # 4. Final sort: fail_count ASC, sharpe DESC (stable, reproducible)
    unique_records.sort(key=lambda r: (r.get('fail_count', 99), -(_safe_float(r.get('sharpe')))))
    
    # 5. Build output text
    dataset_upper = dataset.upper()
    lines = []
    lines.append('=' * 80)
    lines.append(f"{dataset_upper} SEED ALPHA LIST (Sorted: fail_count ASC, sharpe DESC)")
    lines.append(f"Region: {region}, Universe: {universe}")
    lines.append(f"Selection: sharpe > 1.5 AND fail_count <= 1")
    lines.append(f"Total: {len(unique_records)} alphas")
    lines.append('=' * 80)
    lines.append('')
    
    for idx, record in enumerate(unique_records, 1):
        lines.append(format_alpha_entry(idx, record))
        lines.append('')
    
    # Summary
    pass_count = sum(1 for r in unique_records if r.get('fail_count', 0) == 0)
    fail1_count = sum(1 for r in unique_records if r.get('fail_count', 0) == 1)
    warn_count = sum(1 for r in unique_records if r.get('warnings'))
    best_sharpe = max((_safe_float(r.get('sharpe')) for r in unique_records), default=0)
    
    lines.append('=' * 80)
    lines.append('Summary:')
    lines.append(f"- Total: {len(unique_records)} alphas")
    lines.append(f"- PASS (fail_count=0): {pass_count}")
    lines.append(f"- FAIL: 1 (fail_count=1): {fail1_count}")
    lines.append(f"- With warnings: {warn_count}")
    lines.append(f"- Best Sharpe: {best_sharpe}")
    lines.append('=' * 80)
    
    txt_path = os.path.join(output_dir, f"{dataset}.txt")
    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"[WRITTEN] {txt_path} ({len(unique_records)} alphas | PASS: {pass_count}, FAIL:1: {fail1_count}, warnings: {warn_count})")
    return unique_records


def _safe_float(val):
    """Convert a value to float safely, returning 0.0 for None or invalid."""
    if val is None:
        return 0.0
    try:
        return float(val)
    except (ValueError, TypeError):
        return 0.0

# 시뮬레이션 돌리기
* 데이터셋에 따라 정해진 횟수에 맞추어 시뮬레이션 돌리기
* 원한다면 datasets_list를 조작하여 원하는 데이터셋에 맞추어 돌릴 수 있음

In [ ]:
# ============================================================
# Seed-Alpha Generation Pipeline (Resume 지원)
# - LLM으로 simple seed-alpha 후보 생성
# - is_valid_seed_alpha()로 구조 필터링 후 시뮬레이션
# - 결과를 per-dataset .txt 파일로 저장 (incremental append)
#
# SELECTION: sharpe > 1.5 AND fail_count in {0, 1}
# SORTING:   fail_count ASC, sharpe DESC
# DEDUP:     by expression (same expression not saved twice)
# ============================================================

import os
import json
import re
import llm_functions as llm
import ace_lib as ace

# 🔧 CONFIG
TOP_N_DATAFIELDS = 10    # 각 dataset에서 alphaCount 상위 N개만 LLM에 전달
SEED_ALPHA_NUM = 100     # LLM에게 요청할 알파 개수 per batch
OUTPUT_DIR = '.'         # .txt 파일 저장 디렉토리


# ------------------------------------------------------------
# Resume 지원 함수들 (원본 유지)
# ------------------------------------------------------------

def get_existing_json_count(dataset, gen_dir="./gen_json"):
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir, exist_ok=True)
        return 0
    pattern = re.compile(rf"^{re.escape(dataset)}_(\d+)\.json$")
    count = 0
    for filename in os.listdir(gen_dir):
        if pattern.match(filename):
            count += 1
    return count


def get_next_json_index(dataset, gen_dir="./gen_json"):
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir, exist_ok=True)
        return 0
    pattern = re.compile(rf"^{re.escape(dataset)}_(\d+)\.json$")
    max_k = -1
    for filename in os.listdir(gen_dir):
        match = pattern.match(filename)
        if match:
            k = int(match.group(1))
            if k > max_k:
                max_k = k
    return max_k + 1


def save_json_safe(data, filepath):
    if os.path.exists(filepath):
        print(f"[WARN] File already exists, skipping: {filepath}")
        return False
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return True


# ------------------------------------------------------------
# Helper: operators_list.json → compact string for LLM prompt
# ------------------------------------------------------------

def format_operators_compact(operators_dict):
    """
    operators_list.json을 카테고리별로 정리하여 compact string으로 변환.
    LLM 프롬프트의 OPERATORS_LIST 섹션에 사용.
    """
    ops_by_category = {}
    for op_name, op_info in operators_dict.items():
        cat = op_info.get('category', 'Other')
        if cat not in ops_by_category:
            ops_by_category[cat] = []
        ops_by_category[cat].append(op_info.get('definition', op_name))

    lines = []
    for cat, defs in ops_by_category.items():
        lines.append(f"[{cat}] " + " | ".join(defs))
    return "\n".join(lines)


# ------------------------------------------------------------
# NEW: Seed-alpha LLM prompt & generation
# ------------------------------------------------------------

def generate_seed_expressions(s, alpha_region, alpha_universe, dataset_id,
                               model='gpt-5-mini-2025-08-07',
                               alpha_num=100,
                               top_n_datafields=10):
    """
    Generate seed-alpha candidates via LLM.
    ~70-80% follow 4 strict seed patterns, ~20-30% use free-form operators from operators_list.json.
    Returns raw LLM response string.
    """
    # Get datafields for this dataset
    data_fields = ace.get_datafields(
        s, region=alpha_region, universe=alpha_universe,
        dataset_id=dataset_id, data_type='ALL'
    )
    data_fields = data_fields[data_fields['type'] != "GROUP"]

    # Top N by alphaCount
    top_fields_df = data_fields.nlargest(top_n_datafields, "alphaCount")

    # Compact spec for LLM
    spec_keys = ['id', 'description', 'coverage', 'userCount', 'alphaCount', 'type']
    available_keys = [k for k in spec_keys if k in top_fields_df.columns]
    selected_datafields_spec = top_fields_df[available_keys].to_dict("records")

    print(f"[INFO] Selected top {len(selected_datafields_spec)} datafields for dataset '{dataset_id}':")
    for df_spec in selected_datafields_spec:
        print(f"  - {df_spec.get('id', 'N/A')} (alphaCount: {df_spec.get('alphaCount', 'N/A')}, type: {df_spec.get('type', 'N/A')})")

    # Load operators list for FREE_PATTERN section
    operators_dict = llm.import_json('operators_list.json')
    operators_compact = format_operators_compact(operators_dict)

    answer_form = '''{
"results":[
    {
        "idea":...,
        "description":...,
        "implementation":...,
        "confidence_level":...
    }
]
}'''

    prompt = f"""
<MISSION>
Based on the ALLOWED_PATTERNS, FREE_PATTERN, and ALLOWED_DATAFIELDS below,
generate {alpha_num} SEPARATED and DIVERSIFIED simple seed-alpha expressions.

Each result must have 4 parts:
- "idea": core idea of the alpha
- "description": which pattern you used, which datafield, which window parameter, and why
- "implementation": the FASTEXPR expression
- "confidence_level": 0-1 scale, higher = more confident
</MISSION>

<GENERATION_RATIO>
- About 70-80% of generated alphas MUST follow one of the 4 ALLOWED_PATTERNS exactly.
- About 20-30% of generated alphas may use FREE_PATTERN: creative combinations of operators from OPERATORS_LIST.
</GENERATION_RATIO>

<ALLOWED_PATTERNS>
These 4 patterns are the primary building blocks (use for ~70-80% of alphas):

Pattern 1 - Backfill: ts_backfill(DATA, window)
  Example: ts_backfill(rsk60_offer, 252)
  Use when: coverage < 0.6, to fill missing data

Pattern 2 - Time-series Z-score: ts_zscore(DATA, window)
  Example: ts_zscore(mdl138_4idpc, 252)
  If DATA is VECTOR type, wrap with vec_avg(): ts_zscore(vec_avg(rsk60_offer), 252)
  Use when: normalize signal over time

Pattern 3 - Cross-sectional Scale Normalization: rank or zscore of DATA
  Intent: remove scale/size effects without using market cap (cap is NOT available).
  Approaches (pick one):
    - rank(DATA): pure cross-sectional rank (simplest, 1 operator)
    - zscore(rank(DATA)): ranked then standardized (2 operators)
    - ts_zscore(rank(DATA), window): temporal z-score of ranked signal (2 operators)
  Example: ts_zscore(rank(mdl25_vrv421_81v), 126)
  Use when: the raw signal has large cross-sectional dispersion or scale bias

Pattern 4 - Bucket-based Group Normalization: group_zscore with bucket grouping
  Intent: normalize within peer-like groups to reduce concentration.
  IMPORTANT: `industry` and `sector` are NOT available. Use bucket() to build groups.
  The group argument MUST be: bucket(rank(DATA), buckets=N) where N is 5..20.
  Example: group_zscore(DATA, bucket(rank(DATA), buckets=10))
  Use when: signal benefits from within-group normalization
  NOTE: this uses 3 operators (group_zscore, bucket, rank) at max allowed depth.
</ALLOWED_PATTERNS>

<BANNED_FIELDS>
These field names DO NOT EXIST in Brain and WILL cause simulation errors:
- cap, market_cap, mktcap
- industry, sector, subindustry
NEVER use these as datafields or as group arguments.
For scale normalization: use rank() or zscore() instead of dividing by cap.
For group normalization: use bucket(rank(DATA), buckets=N) as the group argument.
</BANNED_FIELDS>

<FREE_PATTERN>
For about 20-30% of generated alphas, you may create expressions using any combination
of operators from OPERATORS_LIST below. Be creative and explore different operator combos.

These free-form expressions must still follow STRUCTURAL LIMITS:
- Maximum 3 operators per expression
- Only 1 signal datafield from ALLOWED_DATAFIELDS (no other fields allowed)
- NEVER use cap, industry, sector, subindustry (they do not exist)
- VECTOR type fields must use vec_* operators (vec_avg, vec_sum, vec_max, etc.)
- Time-series window parameters: use values between 5 and 252

Examples of free patterns:
- ts_rank(DATA, 63)
- quantile(ts_delta(DATA, 21))
- ts_decay_linear(DATA, 126)
- zscore(ts_mean(DATA, 63))
- ts_ir(DATA, 126)
- winsorize(ts_zscore(DATA, 63))
- rank(ts_kurtosis(DATA, 126))
- group_zscore(DATA, bucket(rank(DATA), buckets=10))
</FREE_PATTERN>

<OPERATORS_LIST>
{operators_compact}
</OPERATORS_LIST>

<STRICT_RULES>
RULE1: You MUST ONLY use datafield IDs from ALLOWED_DATAFIELDS. No other datafields.
RULE2: Each expression must use exactly ONE signal datafield from ALLOWED_DATAFIELDS.
RULE3: If a datafield has type=VECTOR, you MUST wrap it with vec_avg() or other vec_* operators before using.
RULE4: Window parameters should be diverse: use various values between 5 and 252.
RULE5: Maximum 3 operators per expression. Keep it simple.
RULE6: NEVER use cap, industry, sector, or subindustry -- they do not exist in Brain.
RULE7: For group_* operators, the group argument MUST be bucket(rank(DATA), buckets=N) with N in 5..20.
</STRICT_RULES>

<DIVERSITY_GUIDANCE>
- Use ALL available datafields, not just the top one
- Vary window parameters (5, 10, 21, 42, 63, 126, 189, 252, etc.)
- Mix ALLOWED_PATTERNS and FREE_PATTERN
- For VECTOR fields, always wrap with vec_* operators
- For low-coverage fields (coverage < 0.6), prefer Pattern 1 (ts_backfill)
</DIVERSITY_GUIDANCE>

<ALLOWED_DATAFIELDS>
{selected_datafields_spec}
</ALLOWED_DATAFIELDS>

<ANSWER_FORMAT>
You must answer in this form:
{answer_form}
</ANSWER_FORMAT>
""".strip()

    result_json = llm.call_llm_stream(prompt, answer_form, model)
    return result_json


# ------------------------------------------------------------
# 메인 루프 (Seed-Alpha Pipeline)
# ------------------------------------------------------------

GEN_DIR = "./gen_json"
os.makedirs(GEN_DIR, exist_ok=True)

# 🔧 REGION / UNIVERSE from global variables
region = REGION
universe = UNIVERSE

print(f"[CONFIG] Region: {region}, Universe: {universe}")
print(f"[CONFIG] Using top {TOP_N_DATAFIELDS} datafields per dataset")
print(f"[CONFIG] Selection: sharpe > 1.5 AND fail_count <= 1")
print(f"[CONFIG] Sorting: fail_count ASC, sharpe DESC | Dedup by expression")
print(f"[CONFIG] Datasets: {datasets_list}")

for dataset in datasets_list:
    
    # 목표 생성 횟수
    target_simnum = datset_to_simnum(dataset)
    
    # 현재 존재하는 파일 개수
    existing_count = get_existing_json_count(dataset, GEN_DIR)
    
    # 남은 생성 횟수
    remaining = target_simnum - existing_count
    
    # 다음 저장할 인덱스
    start_index = get_next_json_index(dataset, GEN_DIR)
    
    print(f"\n{'='*60}")
    print(f"[DATASET] {dataset}")
    print(f"  existing={existing_count}  target={target_simnum}  remaining={remaining}  start_index={start_index}")
    print(f"{'='*60}")
    
    if remaining <= 0:
        print(f"[SKIP] dataset={dataset} already complete ({existing_count}/{target_simnum})")
        continue
    
    # Load existing .txt records for this dataset (for incremental merge)
    all_records = load_existing_txt_records(dataset, OUTPUT_DIR)
    print(f"[INFO] Loaded {len(all_records)} existing records from {dataset}.txt")
    
    for i in range(remaining):
        
        current_index = start_index + i
        save_path = f"{GEN_DIR}/{dataset}_{current_index}.json"
        
        if os.path.exists(save_path):
            print(f"[SKIP] {save_path} already exists")
            continue
        
        print(f"\n--- [{dataset}] Batch {i+1}/{remaining} (index={current_index}) ---")
        print("--- Generating seed alphas with LLM ---")
        
        # 1. LLM Generate
        try:
            response = generate_seed_expressions(
                s, region, universe, dataset,
                model='gpt-5-mini-2025-08-07',
                alpha_num=SEED_ALPHA_NUM,
                top_n_datafields=TOP_N_DATAFIELDS
            )
        except Exception as e:
            print(f"[ERROR] LLM generation failed: {e}")
            continue
        
        print("--- Received response ---")
        
        # 2. Parse JSON
        try:
            json_response = llm.cut_first_to_last_brace(response)
            alphas = json.loads(json_response)
        except Exception as e:
            print(f"[ERROR] JSON parsing failed: {e}")
            continue
        
        # 3. Save raw JSON
        if not save_json_safe(alphas, save_path):
            print(f"[WARN] Could not save {save_path}, skipping")
            continue
        print(f"[SAVED] {save_path}")
        
        # 4. Filter with is_valid_seed_alpha (BEFORE simulation to save API calls)
        raw_results = alphas.get("results", [])
        seed_candidates = []
        rejected = 0
        
        for x in raw_results:
            expr = x.get('implementation', '')
            valid, reason = is_valid_seed_alpha(expr)
            if valid:
                seed_candidates.append(x)
            else:
                rejected += 1
                # Uncomment for debug:
                # print(f"  [REJECT] {reason}: {expr[:80]}")
        
        print(f"[FILTER] {len(seed_candidates)} valid seeds, {rejected} rejected out of {len(raw_results)}")
        
        if len(seed_candidates) == 0:
            print(f"[WARN] No valid seed alphas after filtering")
            continue
        
        # 5. Build alpha list for simulation
        alpha_list = [
            ace.generate_alpha(
                regular=x['implementation'],
                region=region,
                universe=universe,
                neutralization="INDUSTRY"
            )
            for x in seed_candidates
        ]
        
        tags_list = [
            ['seed_alpha', f"confidence_{x.get('confidence_level', 0)}"]
            for x in seed_candidates
        ]
        descs_list = [x.get('description', '') for x in seed_candidates]
        
        len_alpha_list = len(alpha_list)
        print(f"[INFO] Simulating {len_alpha_list} seed alphas")
        
        # 6. Simulate in 8-alpha batches
        for rep in range(0, len_alpha_list, 8):
            
            # Session timeout check
            if ace.check_session_timeout(s) < 500:
                print("[INFO] Session timeout approaching, refreshing...")
                s = ace.start_session()
            
            batch_end = min(rep + 8, len_alpha_list)
            
            try:
                print(f"--- Simulating batch {rep} to {batch_end} ---")
                
                sim_results = list(
                    ace.multi_simulate_alphas_map(
                        s,
                        alpha_list[rep:batch_end],
                        tags_list[rep:batch_end],
                        descs_list[rep:batch_end],
                        batch_end - rep
                    )
                )
                
                # Extract records and track selection stats
                batch_total = 0
                batch_saved = 0
                for result in sim_results:
                    record = extract_sim_record(result)
                    if record:
                        batch_total += 1
                        all_records.append(record)
                        if should_save_alpha(record):
                            batch_saved += 1
                
                print(f"  [SELECT] {batch_saved}/{batch_total} pass selection (sharpe>1.5, fail<=1)")
                
            except Exception as e:
                print(f"[ERROR] Simulation failed: {e}")
                continue
        
        # 7. Write sorted, filtered, deduplicated .txt after each LLM batch
        #    write_dataset_txt handles: filter → dedup by expression → sort → rewrite
        write_dataset_txt(dataset, all_records, region, universe, OUTPUT_DIR)

print("\n" + "="*60)
print("[DONE] All datasets processed")
print("="*60)

# LLM 함수 해설

In [ ]:
# ============================================================
# LLM Seed-Alpha Prompt 데모
# generate_seed_expressions() 함수에서 사용하는 프롬프트 구조 확인용
# ============================================================
import random

# 🔧 REGION / UNIVERSE GLOBALIZED
alpha_region = REGION
alpha_universe = UNIVERSE
dataset_id = "risk60"

# 🔧 CONFIG
top_n_datafields = 3
alpha_num = 100

# 데이터셋에서 데이터필드 불러오기
data_fields = ace.get_datafields(s, region=alpha_region, universe=alpha_universe, dataset_id=dataset_id, data_type='ALL')
data_fields = data_fields[data_fields['type'] != "GROUP"]

# alphaCount 기준 상위 N개 datafield만 선택
top_fields_df = data_fields.nlargest(top_n_datafields, "alphaCount")

# LLM 입력용 compact datafield spec
spec_keys = ['id', 'description', 'coverage', 'userCount', 'alphaCount', 'type']
available_keys = [k for k in spec_keys if k in top_fields_df.columns]
selected_datafields_spec = top_fields_df[available_keys].to_dict("records")

print(f"[INFO] Selected top {len(selected_datafields_spec)} datafields for dataset '{dataset_id}':")
for df_spec in selected_datafields_spec:
    print(f"  - {df_spec.get('id', 'N/A')} (alphaCount: {df_spec.get('alphaCount', 'N/A')}, type: {df_spec.get('type', 'N/A')})")

# Load operators list for FREE_PATTERN section
operators_dict = llm.import_json('operators_list.json')
operators_compact = format_operators_compact(operators_dict)

answer_form = '''{
"results":[
    {
        "idea":...,
        "description":...,
        "implementation":...,
        "confidence_level":...
    }
]
}'''

# Seed-Alpha 전용 프롬프트 (70-80% 패턴 + 20-30% 자유 조합)
prompt = f"""
<MISSION>
Based on the ALLOWED_PATTERNS, FREE_PATTERN, and ALLOWED_DATAFIELDS below,
generate {alpha_num} SEPARATED and DIVERSIFIED simple seed-alpha expressions.

Each result must have 4 parts:
- "idea": core idea of the alpha
- "description": which pattern you used, which datafield, which window parameter, and why
- "implementation": the FASTEXPR expression
- "confidence_level": 0-1 scale, higher = more confident
</MISSION>

<GENERATION_RATIO>
- About 70-80% of generated alphas MUST follow one of the 4 ALLOWED_PATTERNS exactly.
- About 20-30% of generated alphas may use FREE_PATTERN: creative combinations of operators from OPERATORS_LIST.
</GENERATION_RATIO>

<ALLOWED_PATTERNS>
These 4 patterns are the primary building blocks (use for ~70-80% of alphas):

Pattern 1 - Backfill: ts_backfill(DATA, window)
  Example: ts_backfill(rsk60_offer, 252)
  Use when: coverage < 0.6, to fill missing data

Pattern 2 - Time-series Z-score: ts_zscore(DATA, window)
  Example: ts_zscore(mdl138_4idpc, 252)
  If DATA is VECTOR type, wrap with vec_avg(): ts_zscore(vec_avg(rsk60_offer), 252)
  Use when: normalize signal over time

Pattern 3 - Cross-sectional Scale Normalization: rank or zscore of DATA
  Intent: remove scale/size effects without using market cap (cap is NOT available).
  Approaches (pick one):
    - rank(DATA): pure cross-sectional rank (simplest, 1 operator)
    - zscore(rank(DATA)): ranked then standardized (2 operators)
    - ts_zscore(rank(DATA), window): temporal z-score of ranked signal (2 operators)
  Example: ts_zscore(rank(mdl25_vrv421_81v), 126)
  Use when: the raw signal has large cross-sectional dispersion or scale bias

Pattern 4 - Bucket-based Group Normalization: group_zscore with bucket grouping
  Intent: normalize within peer-like groups to reduce concentration.
  IMPORTANT: `industry` and `sector` are NOT available. Use bucket() to build groups.
  The group argument MUST be: bucket(rank(DATA), buckets=N) where N is 5..20.
  Example: group_zscore(DATA, bucket(rank(DATA), buckets=10))
  Use when: signal benefits from within-group normalization
  NOTE: this uses 3 operators (group_zscore, bucket, rank) at max allowed depth.
</ALLOWED_PATTERNS>

<BANNED_FIELDS>
These field names DO NOT EXIST in Brain and WILL cause simulation errors:
- cap, market_cap, mktcap
- industry, sector, subindustry
NEVER use these as datafields or as group arguments.
For scale normalization: use rank() or zscore() instead of dividing by cap.
For group normalization: use bucket(rank(DATA), buckets=N) as the group argument.
</BANNED_FIELDS>

<FREE_PATTERN>
For about 20-30% of generated alphas, you may create expressions using any combination
of operators from OPERATORS_LIST below. Be creative and explore different operator combos.

These free-form expressions must still follow STRUCTURAL LIMITS:
- Maximum 3 operators per expression
- Only 1 signal datafield from ALLOWED_DATAFIELDS (no other fields allowed)
- NEVER use cap, industry, sector, subindustry (they do not exist)
- VECTOR type fields must use vec_* operators (vec_avg, vec_sum, vec_max, etc.)
- Time-series window parameters: use values between 5 and 252

Examples of free patterns:
- ts_rank(DATA, 63)
- quantile(ts_delta(DATA, 21))
- ts_decay_linear(DATA, 126)
- zscore(ts_mean(DATA, 63))
- ts_ir(DATA, 126)
- winsorize(ts_zscore(DATA, 63))
- rank(ts_kurtosis(DATA, 126))
- group_zscore(DATA, bucket(rank(DATA), buckets=10))
</FREE_PATTERN>

<OPERATORS_LIST>
{operators_compact}
</OPERATORS_LIST>

<STRICT_RULES>
RULE1: You MUST ONLY use datafield IDs from ALLOWED_DATAFIELDS. No other datafields.
RULE2: Each expression must use exactly ONE signal datafield from ALLOWED_DATAFIELDS.
RULE3: If a datafield has type=VECTOR, you MUST wrap it with vec_avg() or other vec_* operators before using.
RULE4: Window parameters should be diverse: use various values between 5 and 252.
RULE5: Maximum 3 operators per expression. Keep it simple.
RULE6: NEVER use cap, industry, sector, or subindustry -- they do not exist in Brain.
RULE7: For group_* operators, the group argument MUST be bucket(rank(DATA), buckets=N) with N in 5..20.
</STRICT_RULES>

<DIVERSITY_GUIDANCE>
- Use ALL available datafields, not just the top one
- Vary window parameters (5, 10, 21, 42, 63, 126, 189, 252, etc.)
- Mix ALLOWED_PATTERNS and FREE_PATTERN
- For VECTOR fields, always wrap with vec_* operators
- For low-coverage fields (coverage < 0.6), prefer Pattern 1 (ts_backfill)
</DIVERSITY_GUIDANCE>

<ALLOWED_DATAFIELDS>
{selected_datafields_spec}
</ALLOWED_DATAFIELDS>

<ANSWER_FORMAT>
You must answer in this form:
{answer_form}
</ANSWER_FORMAT>
""".strip()

print(prompt)